### ISSUE TITLE
Wondering how to share my map.

### ISSUE THREAD

**Issue by SpensrBeta** [overviewer/Minecraft-Overviewer#1035]
So I'm wondering how people go about sharing these maps.

I tried google drive, since the files end up being really big, but the index.html will only open as a document.

The only way that seems like it might work is if people downloaded the whole folder, but that would take hours at 2.4gb.

So is there a good way people can host the maps, and/or is there a way to make the files smaller?

**Comment by eminence** [comment]
It would be super if someone wanted to take up the task of writing up a good tutorial about how to setup and configure a webserver to share overviewer maps!
