### ISSUE TITLE
Optionally disable full map scanning to generate only manual POI's much faster

### ISSUE THREAD

**Issue by MEDVEDx64** [overviewer/Minecraft-Overviewer#1126]
Hello. On my >3 gb world I need to place only some manual POIs, and this useless scanning for entities takes pretty long time. Would be great to see some command-line option that skips the scanning and passes directly to manual POIs placement, it would be thousand times faster for me.

**Comment by CounterPillow** [comment]
Almost two years later, I finally did it. Hooray.
