### ISSUE TITLE
My dynamic markers no longer work in 0.12

### ISSUE THREAD

**Issue by BarRagedRick** [overviewer/Minecraft-Overviewer#1153]
Only some of my dynamic markers that are set by using signs work after upgrading overviewer.
I have no idea why, I haven't changed anything in game, even if I place new signs using the format below they don't show up.

Here's my config:
from optimizeimages import optipng

worlds["survival"] = "/home/shelter/multicraft/servers/server1/world"

def poiFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'POI':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def townFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Town':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def portalFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Portal':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def campFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Camp':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def mineFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Mine':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def templeFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Temple':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def waterFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Water':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

def tableFilter(poi):
    if poi['id'] == 'Sign':
        if poi['Text1'] == 'Table':
           return "\n".join([poi['Text2'], poi['Text3'], poi['Text4']])

renders["survivalday"] = {
    "world": "survival",
    "title": "Survival Daytime",
    "rendermode": smooth_lighting,
    "optimizeimg":[optipng()],
    "dimension": "overworld",
    'markers': [dict(name="POIs", filterFunction=poiFilter, icon="poi.png"),
                dict(name="Towns", filterFunction=townFilter, icon="town.png"),
                dict(name="Camps", filterFunction=campFilter, icon="camp.png"),
                dict(name="Mines", filterFunction=mineFilter, icon="mine.png"),
                dict(name="Temples", filterFunction=templeFilter, icon="temple.png"),
                dict(name="Portals", filterFunction=portalFilter, icon="portal.png"),
                dict(name="Waters", filterFunction=waterFilter, icon="water.png"),
                dict(name="Tables", filterFunction=tableFilter, icon="table.png")]
}

outputdir = "/var/www/web-mc/map"
#texturepath = "faithful32.zip"
texturepath = "minecraft.jar

**Comment by CounterPillow** [comment]
Has been fixed with an internal hack.
