### ISSUE TITLE
How to extract Resource Pack ?

### ISSUE THREAD

**Issue by sebastienhouzet** [overviewer/Minecraft-Overviewer#1159]
Hello,

I just install overviewer and i want to generate a map.
But the textures is not present on my serveur.

Could not find the textures while searching for 'assets/minecraft/textures/blocks/grass_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.8-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

I have download minecraft.jar but i doesn't work.
How to extract Resource pack to add it on my server ?

Thx

**Comment by eminence** [comment]
This is an old issue, please come back to us if you still need help.  Closing
