### ISSUE TITLE
Request: RCON Observer for Overviewer

### ISSUE THREAD

**Issue by djplasmid** [overviewer/Minecraft-Overviewer#1160]
I am currently running my server on a Win2k8R2 box and I would like to be able to report render progress in the Minecraft console. There does not seem to be any way to (easily) create a FIFO in Windows and therefore no way for me to pipe the data to the server this way. Is there another way to do this through Windows? Could this be done through RCON? If so, it would be awesome! Thanks for all the hard work guys.

**Comment by agrif** [comment]
Hello! Sorry for the late reply, we just got back around to this.

Check out the [new RconObserver](http://docs.overviewer.org/en/latest/config/#observers) which should be showing up in the [windows builds](http://overviewer.org/downloads) soon, if you use those.
