### ISSUE TITLE
Unicode characters not displayed for POI

### ISSUE THREAD

**Issue by Lcreager** [overviewer/Minecraft-Overviewer#1167]
When generating POIs some unicode characters are not being displayed.

Example from markersDB.js

root@apps:~# cat /var/www/markersDB.js
var markersDB={
  "All_signs6cd7_6d0d": {
    "raw": [
      {
        "y": 81,
        "text": "\\u003c-Subway\nMountain Paths-\\u003e\n\n",
        "hovertext": "\\u003c-Subway\nMountain Paths-\\u003e\n\n",
        "z": 5,
        "x": -154
      },

Version Info:

root@apps:~# overviewer.py --version
Minecraft Overviewer 0.12.10 (00c2782)
built on Wed Sep  3 20:25:01 2014

**Comment by markfickett** [comment]
I was having this problem with sign text. I worked around it following the advice of http://stackoverflow.com/questions/4020539/process-escape-sequences-in-a-string-in-python by adding this to my POI filter:

```
_ESCAPE_SEQUENCE_RE = re.compile(r'''
    ( \\U........      # 8-digit hex escapes
    | \\u....          # 4-digit hex escapes
    | \\x..            # 2-digit hex escapes
    | \\[0-7]{1,3}     # Octal escapes
    | \\N\{[^}]+\}     # Unicode characters by name
    | \\[\\'"abfnrtv]  # Single-character escapes
    )''', re.UNICODE | re.VERBOSE)

def _DecodeEscapes(s):
	def decode_match(match):
		return codecs.decode(match.group(0), 'unicode-escape')
	return _ESCAPE_SEQUENCE_RE.sub(decode_match, s)

def _SignText(poi):
	if poi['id'] != 'Sign':
		return
	texts = []
	for n in range(1, 5):
		t = poi.get('Text%d' % n)
		t = _DecodeEscapes(t.strip('"'))
		texts.append('' if t == 'null' else t)
	if any(texts):  # Omit blank signs (used for structure only).
		texts.append('y = %s' % poi['y'])
		return '\n'.join(texts).strip('\n')
```

**Comment by CounterPillow** [comment]
What version is your Overviewer? Pretty sure this should've been fixed with #1215

**Comment by markfickett** [comment]
Thanks for taking a look! This was at v0.12.0 / 5d13030 . Actually I just updated and am having trouble with sign POIs (#1220).

**Comment by markfickett** [comment]
Confirmed that my workaround is no longer necessary. Thanks!
