### ISSUE TITLE
Tried several times to read chunk -5,-137. Unknown error. Giving up

### ISSUE THREAD

**Issue by MikeyCarter** [overviewer/Minecraft-Overviewer#1190]
How do I debug if this is a bug or actual corruption.  Only started to come up with 1.8.1.

**Comment by CounterPillow** [comment]
Additional notes from Tunabrain related to the issue, made on IRC:

```
[10:28] <Tunabrain> Like recently when it turns out that Mojang writes unsigned length specifiers for strings, even though the spec says signed
[10:29] <Tunabrain> Sooo there was of course a string in the NBT with 55k characters that would read as length -9000 if you interpreted it according to the spec, and the entire thing thrashed itself to bits
```

Issue should be re-opened. Mojang may have buggered up their own format, but we still have to treat it right, i.e. read an unsigned short instead of signed.

**Comment by tunabrain** [comment]
Can confirm. It seems that string lengths are interpreted as unsigned shorts. At least, NBT that doesn't parse correctly under the spec will work if you change string lengths to unsigned.

I'm not sure whether this also applies to byte/int arrays, but I doubt Minecraft stores data large enough to run into that issue.

**Comment by agrif** [comment]
I've changed our NBT parser to use unsigned values for all array lengths, which ought to solve this issue. I'd close it, but... seems it's already closed. :smile:
