### ISSUE TITLE
Is there a technical reason that tiles are organized in recursive directory trees?

### ISSUE THREAD

**Issue by Taytay** [overviewer/Minecraft-Overviewer#1191]
Overviewer writes out the tiles in the quadtree format like:
1/2/1/1/3/1.png

For that reason, a custom algorithm is needed to get the correct URL for the tiles. Many map libraries use the URL format of base.com/{zoom}/{x}/{y}.png

Is there anything that would prevent such a structure, or a structure like {zoom}/{x},{y}.png (number of files getting too high in a single directory, etc)?

**Comment by eminence** [comment]
Closing now, please re-open if you want to continue the discussion.
