### ISSUE TITLE
Error when running against a spigot-generated world

### ISSUE THREAD

**Issue by eminence** [overviewer/Minecraft-Overviewer#1194]
```
Sorry, This version of Minecraft-Overviewer only works with the 'Anvil' chunk format
```

Several users have reported this in IRC.  apparently spigot is generating worlds with a version of zero in the level.dat file

**Comment by eminence** [comment]
See also https://hub.spigotmc.org/jira/browse/SPIGOT-354

**Comment by micaelbergeron** [comment]
I can confirm the workaround is working.

**Comment by CounterPillow** [comment]
Has been fixed in Spigot, and as far as I'm aware, we've already removed the workaround again.
