### ISSUE TITLE
genPOI complains about missing attribute and hangs

### ISSUE THREAD

**Issue by MatthiasMann** [overviewer/Minecraft-Overviewer#1218]
Output: https://gist.github.com/MatthiasMann/42a3a29760f7f38cfde6

Config File: https://gist.github.com/MatthiasMann/adeeacd962a4891cb7cc

I can't stop genpoi by pressing Ctrl-C - that will just create tons of additional stack traces but keeps running - I have to kill the process.

**Comment by MatthiasMann** [comment]
Output after pressing Ctrl-C: https://gist.github.com/MatthiasMann/3459a15330a6390ea9cb

**Comment by MasterofJOKers** [comment]
What version of Python are you using?

**Comment by CounterPillow** [comment]
I think he said on IRC that he's on Windows, so whatever the Windows builders use I guess.

However, we should aim to support anything from python 2.6 onwards, since that's what RHEL 6 comes with by default as far as I know.

**Comment by MasterofJOKers** [comment]
I've tried it on a linux machine with python 2.6 without error. Don't know what's going wrong on windows. I have no windows at hand at the moment, so cannot look into this really.

**Comment by agrif** [comment]
On windows, multiprocessing spawns entirely new processes, which means that setting attributes on a module will not be visible in the subprocesses.

(On systems with a `fork()` syscall, it just uses that, hence why this works)

I'm not entirely sure how to work around this yet, but that's the root problem at least.

**Comment by agrif** [comment]
I just pushed a fix for this to master, and builds of version 0.12.63 should be available soon!
