### ISSUE TITLE
Easier setup for Minecraft Overviewer

### ISSUE THREAD

**Issue by penguincoder** [overviewer/Minecraft-Overviewer#1226]
This isn't an actual issue, just more of an option.

So in order to reduce the barrier to get people to try to use and maintain a Minecraft Overviewer setup, I made a Vagrant repo that will automatically build, setup, and run everything you need to have a vanilla Minecraft server and the overviewer run at regular intervals.

http://github.com/penguincoder/vagrant-minecraft

**Comment by LeadMagnet** [comment]
Ya know what would be great, if someone built a pre-configured VirtualBox appliance with this! Maybe loaded to turnkeylinux.org or virtualboximages.com

:D

**Comment by blag** [comment]
I made a docker-compose that will download the Minecraft files, run Overviewer, and setup a web server. The project is at https://github.com/blag/minecraft-map. The only requirements are Docker and docker-compose.

Hope this helps!

**Comment by penguincoder** [comment]
It does. I have also updated my vagrant setup to include the overviewer. I think that should be sufficient.
