### ISSUE TITLE
GenPOI generates only one marker

### ISSUE THREAD

**Issue by cyber01** [overviewer/Minecraft-Overviewer#1228]
Use the latest version overviewer, point configured like this:
http://puu.sh/h5suT/4d646bbb52.png
The problem is that the map shows only the first point, all the rest does not seem to generate ...
Tell me what is wrong or what can be done?

**Comment by CounterPillow** [comment]
Where is your `teleportFilter`?

**Comment by cyber01** [comment]
teleportFilter same bankFilter (only changed name and id (in if))

**Comment by CounterPillow** [comment]
Can you tell me the output of `overviewer.exe --version`? This should have been fixed in #1217

**Comment by cyber01** [comment]
Minecraft Overviewer 0.12.58 (4cd47da)

**Comment by CounterPillow** [comment]
That is not the latest version. Please update here: http://overviewer.org/downloads

**Comment by cyber01** [comment]
Oops, sorry, did not notice right away that I have version 58, not 68 ...
