### ISSUE TITLE
Water blocks are not render on all visible faces

### ISSUE THREAD

**Issue by Hinara** [overviewer/Minecraft-Overviewer#1233]
I seen it on ExMaple (render of the 04 May 2015) render like here :
http://overviewer.org/example/#/-331/64/62/max/0/0
The faces which are against the border (certainly truncated by crop) are not rendered.

**Comment by CounterPillow** [comment]
I think solving this would require generating pseudo-ancildata for water blocks to override what Minecraft tells us, though I'm not too sure about that.

>The faces which are against the border (certainly truncated by crop)

Exmaple isn't actually truncated by a configuration crop. The world is just that small.
