### ISSUE TITLE
Webserver show no markers

### ISSUE THREAD

**Issue by Wyqer** [overviewer/Minecraft-Overviewer#1236]
Hello everybody.

I've the following issue.

I succesfully render the map and create the markers via --genpoi etc.
If i have a look at the map files on my own hd i can see the markers on the map which i've created.
But if i upload it on my webserver i can see the map without problems, also i have the "markers" drop down menu at the upper right corner. But if i check the boxes no markers appear on the map.
As i said if i look at the same index file on my own hdd and i check the boxes for the markers i can see them.
Any suggestions?

**Comment by CounterPillow** [comment]
Did you upload the entire output directory?

**Comment by Wyqer** [comment]
Yes, uploaded everything what have been in the output directory.
Maybe something with the directory permissions on the Webserver or something like that?
Map is here by the way:
http://minecraft.killahpotatoes.de

**Comment by CounterPillow** [comment]
It's missing the icons (`icons/marker_town.png`, `icons/marker_tower.png`, `icons/marker_town_red.png`)

**Comment by Wyqer** [comment]
That's strange. The Icons are uploaded and the structure of the directory etc. is exactly the same as on my hdd in the map folder.

**Comment by CounterPillow** [comment]
Looks like the icons/ directory is clashing with a builtin apache thing. See: http://minecraft.killahpotatoes.de/icons/

I recommend checking your webserver's documentation.

**Comment by Wyqer** [comment]
Oh, that's really weird o.O
Thanks a lot for the help :)

**Comment by CounterPillow** [comment]
Apparently, there's a sitewide alias in httpd.conf which aliases /icons/ to /var/www/icons/. Disable that and it should work.

**Comment by Wyqer** [comment]
Will do so, thanks again for your help. :)
