### ISSUE TITLE
McRegion

### ISSUE THREAD

**Issue by iBars** [overviewer/Minecraft-Overviewer#1238]
Please link me to download mcregion-compatible build of Overviewer:
https://github.com/overviewer/Minecraft-Overviewer/releases/tag/old-region-format

**Comment by CounterPillow** [comment]
1. For which operating system?

2. Are you sure you *really* need an mcregion compatible version? Any changes to overviewer since then will not be available to you; if you can, converting your world to the new format would likely be a better idea.

**Comment by agrif** [comment]
If you need it, there's a [Windows build here](http://overviewer.org/builds/win32/1/overviewer-old.region.0.zip). If you want a different build, feel free to ask. This code is almost two years old now though.

**Comment by CounterPillow** [comment]
I'm going to close this for now since the initial request appears to have been resolved. Let me know if any further questions or problems exist, and I shall re-open.

**Comment by NDruce** [comment]
_Sorry, This version of Minecraft-Overviewer only works with the 'Anvil' chunk format_
(with download from agrif)
