### ISSUE TITLE
Update when more chunks load

### ISSUE THREAD

**Issue by lasses** [overviewer/Minecraft-Overviewer#1239]
How do i update the map after I've loaded more chunks? And is there a way to pre-load all(not all but maybe 10k/10k) the chunks without me having to walk to make them all load?

**Comment by MasterofJOKers** [comment]
Regarding the "how do I preload chunks": I've "solved" this before by teleporting my character every second the distance of my view range. This can be automated with a little shell-code which writes the teleport command into the server console. It still takes a lot of time.

**Comment by lasses** [comment]
I solved the preloading but I still need help updating the map on the overviewer

**Comment by CounterPillow** [comment]
To update the map, simply run the overviewer with the same command again. It will update the map incrementally.

**Comment by lasses** [comment]
so i have to do all the thing in cmd again?

**Comment by lasses** [comment]
Or how do i make it update incrementally?

**Comment by CounterPillow** [comment]
yes, simply run the cmd command again.

**Comment by lasses** [comment]
I don't know which one :/

**Comment by CounterPillow** [comment]
the rendering command starting with `overviewer.exe`. Make sure to `cd` to the right directory again first though.

**Comment by lasses** [comment]
Like I did here? https://www.youtube.com/watch?v=uGN4cOAlFWE

**Comment by CounterPillow** [comment]
Please see the official Windows Beginner's Guide here: http://docs.overviewer.org/en/latest/win_tut/windowsguide/

**Comment by lasses** [comment]
Okay but I dont understand why it would make any difference doing the same thing again

**Comment by CounterPillow** [comment]
Overviewer sees that there already is an output directory, and only re-renders chunks which have been changed since the last time the map was rendered by using chunk modification times.

**Comment by lasses** [comment]
Thanks

**Comment by CounterPillow** [comment]
I'll close this for now because I assume your problem has been resolved. If not, let me know and I will reopen the issue.
