### ISSUE TITLE
world name when displaying corrupt region error

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1251]
Can you add a verbose option to error reporting giving the world name and exact filename that was trying to be processed.

The message "Found a corrupt region file at 7,17. Skipping it." does not help me when processing 10+ worlds at a time. They all have a region file for 7, 17. The world name would be good to identify which file needs terminating! :D

**Comment by eminence** [comment]
This is a good idea

**Comment by LeadMagnet** [comment]
Thanks CP, easier to deal with warnings now! :D
