### ISSUE TITLE
OpenJDK vs Oracle JDK textures issue

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [overviewer/Minecraft-Overviewer#1252]
Just a quick comment about the textures guide, the quickest way to get the minecraft server running on a headless linux server is to just install OpenJDK which works fine with the minecraft server jar, however with overviewer and a client installed in the correct directory you will still get the following error:

```
2015-09-28 10:35:57 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/grass_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.8-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

A comment in the textures section of the docs would be really handy... spent a good few hours trying to run overviewer and getting frustrated about the same error over and over:

http://docs.overviewer.org/en/latest/running/#installing-the-textures

Quick guide for installing Oracle Java on CentOS / Fedora servers:

```
Download RPM for example jdk-7u51-linux-x64.rpm (replace 51 with latest version number downloaded): http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

rpm -Uvh jdk-7u51-linux-x64.rpm

sudo alternatives --install /usr/bin/java java /usr/java/latest/jre/bin/java 200000
sudo alternatives --install /usr/bin/javaws javaws /usr/java/latest/jre/bin/javaws 200000
sudo alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000
sudo alternatives --install /usr/bin/jar jar /usr/java/latest/bin/jar 200000

sudo alternatives --config java
sudo alternatives --config javaws
sudo alternatives --config javac
sudo alternatives --config jar

vi .bashrc
export JAVA_HOME="/usr/java/latest"
```

**Comment by CounterPillow** [comment]
huh? Overviewer itself and the textures don't depend on Java at all, and the version of Java does not matter. We simply open the jar as an archive file. You can run Overviewer on servers without Java installed.

**Comment by eminence** [comment]
I agree, this is very strange is Overviewer doesn't require Java.   Are you able to reproduce this issue by switching back to the OpenJDK JRE?  If so, can you please run `overviewer.py --check-terrain --verbose` and copy the output into this issue?

**Comment by Caffe1neAdd1ct** [comment]
Sure, I'll give this a go tomorrow.

That's what I thought from the docs and the fact I could just run unzip on
the jar.

I ran the one liner command on the docs to install the latest client using
the user which runs both Minecraft and Overviewer so shouldn't have been
any issues.

It just started working after I switches over so I put it down to that..

Starting to wonder if it was a problem with wget / getting a corrupt jar....

**Comment by eminence** [comment]
If there is more to discuss on this topic, feel free to come back to us.  Closing for now.
