### ISSUE TITLE
repeated "Giving up" messages for region files

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1253]
I have recently been getting loads of...

WARNING:root:Tried several times to read chunk X,X. Its region (X,X) may be corrupt. Giving up.

I know the cause of this. The server owner bounces back and forth between Bukkit and Spigot. When he does, we always get corrupted regions. Luckily, they are area's nobody has visited/built in so no biggie.

What is strange is that when processing the mapps, I get this error over and over, for the exact same region file until overviewer crashes. This does not seem normal. If it's giving up, why try again? I'm not doing a forcerender or anything else to force a tile change re-detect. Just a base render.

Should Overviewer be doing what it says in the console? Yes it's broke, I know this, give up, move on!?

For ref: Windows Server 2012R2, 4GB mem, running nothing but Overviewer FTP Voyager client (scheduler) and FileZilla FTP Server

**Comment by robbix1206** [comment]
It's normal a region is 16*16 chunks so this message can appeares for each chunk of the region

**Comment by robbix1206** [comment]
Correction a region contain 32*32 chunks
Source :http://minecraft.gamepedia.com/Region_file_format

**Comment by LeadMagnet** [comment]
Yup! Fully understand that. 

So why, in region file r.165.130.mca is it trying to read chunk 5291, 4169 hundreds (literally) of times until overviewer finally crashes?

This does not seem like desired behaviour to me. It should attempt to read the chunk and, if a failure occurs (and after X retries (configurable?)), permanently ignore it on future passes of that region! Is that not the purpose of the --forcerender flag, to ignore "stuff" and reprocess everything?

ATM my render times are ten's of hours, full re-render is days. I would prefer OVR to skip it and move on fast, let me deal with the "why is this chunk borked". 99% of the time I know what is wrong even if OVR doesn't.

**Comment by Staric1982** [comment]
Are you try to fix or delete corrupted regions/chunks? I had similar problem (3 corrupted chunks in world), deleted it and this error gone.

**Comment by CounterPillow** [comment]
>Normally. If there was more logging (hint hint) maybe I could narrow it down.

Run with `--verbose`

**Comment by halfsight420** [comment]
I get this when people are active in the chunks. The chunks aren't actually corrupt. There is just somebody active in it. Once the player logs off, the overviewer scans with Zero errors.

I wish this error would show a minimal amount of times then go away.

**Comment by LeadMagnet** [comment]
Luckily I don't have to worry about that happening. I'm running Overviewer in isolation, so it doesn't effect the host server. The map server FTP's into the Host server, checks for updated world files, sync's then disconnects. Takes about 4 minutes for 10 worlds (and their all huge).

Overviewer rendering is scheduled for midnight GMT when most players are offline.

Just downloaded 0.12.135 and this issue isn't as bad as it used to be. In fact, most of the worlds didn't show this error at all. Weird.
