### ISSUE TITLE
GPG signed RPM packages

### ISSUE THREAD

**Issue by corpix** [overviewer/Minecraft-Overviewer#1255]
Please sign your packages or switch your [repo](http://overviewer.org/rpms/overviewer.repo) to https(poor solution, but better than nothing).

**Comment by agrif** [comment]
Hey I just added RPM signing ([example package](http://overviewer.org/builds/el6-32/13/overviewer-0.12.81.rpm)). The rest of the packages are building, and should be done by the time you read this.

The key used for signing is the same as for our debian packages, and can be imported with:

    rpm --import http://overviewer.org/rpms/overviewer.gpg.asc

Unfortunately this change could break people using our repo without this key, but this was a change we've needed to make for a long time now.

**Comment by corpix** [comment]
Awesome, thank you!
