### ISSUE TITLE
After `yum install Minecraft-Overviewer` I get a python2.7 numpy import error

### ISSUE THREAD

**Issue by positron** [overviewer/Minecraft-Overviewer#1257]
I'm running an updated Amazon Linux on AWS.

 `yum install Minecraft-Overviewer` reports:

```
Installed:
  Minecraft-Overviewer.x86_64 0:0.12.81-1.fc19

Dependency Installed:
  atlas.x86_64 0:3.8.4-2.6.amzn1                     libgfortran.x86_64 0:4.8.3-9.109.amzn1
  libquadmath.x86_64 0:4.8.3-9.109.amzn1             python26.x86_64 0:2.6.9-1.80.amzn1
  python26-backports.x86_64 0:1.0-3.14.amzn1         python26-backports-ssl_match_hostname.noarch 0:3.4.0.2-1.12.amzn1
  python26-imaging.x86_64 0:1.1.6-19.9.amzn1         python26-libs.x86_64 0:2.6.9-1.80.amzn1
  python26-nose.noarch 0:1.3.0-1.11.amzn1            python26-numpy.x86_64 0:1.7.2-8.16.amzn1
  python26-setuptools.noarch 0:12.2-1.30.amzn1
```

But when I run `overviewer.py` I get an error message: 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/overviewer_core/textures.py", line 16, in <module>
    import sys
ImportError: No module named numpy.core.multiarray
```

The installation page mentions installing python 2.6. Do I need python 2.6 installed?

**Comment by robbix1206** [comment]
Try to use the last 2.X of python 
The docs and package dependencies are maybe outdated and over viewer maybe need python 2.7 now.
If you want to compiled it by hand : https://www.python.org/downloads/release/python-2710/
Or make a search on your package manager

**Comment by CounterPillow** [comment]
@robbix1206 It's a problem with our pre-compiled RPMs which don't have their dependencies updated from what I remember, not a problem with the end-user.

**Comment by robbix1206** [comment]
I was not sure but i tried because all library which are shown as installed are display as 2.6 and the error is with a library in a python2.7 folder.
I think he may have python2.7 with python 2.6 libraries.

**Comment by positron** [comment]
It is a dependency problem. I investigated a little more today and all the installed dependencies are for python 2.7 except for numpy, which was `python26-numpy.x86_64`.

Running `sudo yum install python27-numpy.x86_64` fixed the problem.

**Comment by CounterPillow** [comment]
Somewhat related to #1204
