### ISSUE TITLE
Whole map wont render

### ISSUE THREAD

**Issue by ItzSkipper** [overviewer/Minecraft-Overviewer#1258]
Hi, I'm trying to render a map that I have for hardcore factions, it's the size of a normal minecraft world.
But the whole map won't render, only a few chunks away from the spawnpoint render.
Here is what it renders: https://drive.google.com/file/d/0Bz0tUYqMc6tHbXhVNjVpUHdJcTQ/view?usp=sharing (Sorry for the google drive download, I can't seem to make my host work with it)
Do I need to do something in the config or use a special flag for it to render it all?

**Comment by CounterPillow** [comment]
Overviewer can only render chunks which have been generated, i.e., which actually exist in the world directory.

**Comment by ItzSkipper** [comment]
How can I generate the chunks of the whole world? Is there a plugin/mod to do so?

**Comment by CounterPillow** [comment]
There are mods for the minecraft server to do so if I remember correctly, but I've never used any so unfortunately I can't give any recommendations for a specific one.

**Comment by chungy** [comment]
You might try [Minecraft Land Generator](https://sites.google.com/site/minecraftlandgenerator/) to force the server to generate a large square area. This can take some time depending on how much you do.

**Comment by ItzSkipper** [comment]
I want the structures and the spawnpoint I set to be rendered, but MLG re-creates the map again. Any ideas?

**Comment by chungy** [comment]
MLG won't overwrite already-generated chunks if you run it against your server directory as it is now. It basically just resets the world spawn to specific locations and starts up the minecraft server in rapid succession until all the chunks are generated (the server generates chunks around the spawn point automatically)

**Comment by ItzSkipper** [comment]
I see, I'll try again.

**Comment by Kyrluckechuck** [comment]
I know I'm almost resurrecting a dead post, but thought I'd mention the method that I've had success with for years!

I use WorldBorder and simply go to /spawn, set the shape I want my border to be in, set the distance x and y from spawn to create the border at as well as the padding (the amount extra generated outside of the actual border to make it look better to users at the border). Finally i use the /wb fill command to automatically generate all of the chunks within the border and it can even properly do elliptical shapes.

An example output if you want to see what I mean is available at:
http://map.mctango.com

This is good for high-volume servers as there will never need to be chunk generation during normal usage with your players, let alone multiple people all causing chunk generation at the same time!

Then you just rerun the Overviewer on it. It can take upwards of 48h depending on your server and if you want smooth_lighting on for your renders for a server with 4000 blocks x 4000 blocks elliptical!

**Comment by CounterPillow** [comment]
I'll close this for now since people have replied with ways to solve this. Let me know if you still have problems related to overviewer in this regard and wish to have the issue reopened.
