### ISSUE TITLE
Python.h missing

### ISSUE THREAD

**Issue by cloviswarlop229** [overviewer/Minecraft-Overviewer#1260]
This is the output from the build command.

running build
running build_py
copying overviewer_core/overviewer_version.py -> build/lib.linux-x86_64-2.7/overviewer_core
running build_ext
building 'overviewer_core.c_overviewer' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c overviewer_core/src/main.c -o build/temp.linux-x86_64-2.7/overviewer_core/src/main.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement
In file included from overviewer_core/src/main.c:18:0:
overviewer_core/src/overviewer.h:32:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Output for apt-get install python-dev

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Package 'python-dev' has no installation candidate

**Comment by CounterPillow** [comment]
Which platform?

**Comment by cloviswarlop229** [comment]
Linux 64 bit but i'm migrating servers to Amazon AMI so i will see if the problem persists or if it was a custom linux issue

**Comment by robbix1206** [comment]
What distribution of Linux x64 ? Your own ?

**Comment by andrelramos** [comment]
@cloviswarlop229, try this: sudo apt-get install python-dev

**Comment by CounterPillow** [comment]
@andrelramos They already said that package doesn't exist on their distribution.

**Comment by eminence** [comment]
Still waiting for feedback, so closing for now.  Please let us know if you still need help
