### ISSUE TITLE
The new Path block is not being renderd

### ISSUE THREAD

**Issue by MakerTim** [overviewer/Minecraft-Overviewer#1262]
We got a Overviewer at our site, and the special-render-blocks like Slimeblock and Path block is not being renderd at all. 
I was watching the config and some requests for it, can there be an option that this kind of blocks just render as full blocks, i dont care that there not transparant or 1/16 short, but this doesnt look at all what it supposted to look like!
http://render.imine.nl/iMineS3/#/-2026/64/1075/max/0/0

**Comment by CounterPillow** [comment]
Notes for anyone wanting to implement this:

* ID: 208
* Like full block but only 15/16th in height.
* Added in 15w31 (to be version 1.9), probably will be in stable in January.

**Comment by CounterPillow** [comment]
fixed in 5f9276a24a8d64efe4b91cf29c565b4541a0cdf0
