### ISSUE TITLE
"Detected that overwriting renames do NOT work in "U:\\path\\to\\dir"

### ISSUE THREAD

**Issue by Kyrluckechuck** [overviewer/Minecraft-Overviewer#1264]
Hey there,

Just trying to find if this has any significance whatsoever (i.e. causing it run much slower or if it's just a useless information error).

This is running Overviewer on a Windows10 system using the following config:
http://pastebin.com/kZbYrBkx

Thanks!

**Comment by CounterPillow** [comment]
Is U:\ by any chance a network drive?

**Comment by Kyrluckechuck** [comment]
Hey CounterPillow, in short, no.
Funny enough I had been trying to set up my webserver to be the target destination so I could have the overviewer web files hosted there, but I couldn't find any proper way to map the FTP to a drive letter that Overviewer would accept. It would always give an error about it not being able to properly access the location (on the FTP server).

I gave up and resetup my old WAMP server to only deal with the specific map.mysite.web address and that all works well enough now. It is working on a different drive than the main OS (C: is the main OS, server files are on U:). Both are local HDDs.

**Comment by eminence** [comment]
This message is primarily a diagnostic message for Overviewer developers.  

When Overviewer writes to files, we first write to a temporary file and then move that temporary file over the real destination.  This is a common thing to do, as it helps prevents the contents of the final destination file from being corrupted in case of a crash.

However, this trick only works if you can overwrite a file like this.  On some filesystems, this is not possible, so we try to detect this (and issue the debug message you are seeing)
