### ISSUE TITLE
"Hide" a region from overview map

### ISSUE THREAD

**Issue by JasonBristol** [overviewer/Minecraft-Overviewer#1268]
Is it possible to define a region that Overviewer can skip over during map generation? I currently have a region of my map that is extremely far off from the main body of my world. This is forcing my map to 16 zoom levels.

It may also be helpful to hide this area since I use it mainly as an rpg adventure only zone that I would like players to map on their own in-game without restricting access to the overviewer map of the rest of the world.

**Comment by CounterPillow** [comment]
You can use the "crop" render dictionary key to crop a map. See [the documentation](http://docs.overviewer.org/en/latest/config/#rendering) for more information on how to use it.

**Comment by JasonBristol** [comment]
Ahh, must have missed that! That is exactly what I was looking for, thanks!

**Comment by CounterPillow** [comment]
I'll close this issue then. Let me know if you still have questions and want it re-opened.
