### ISSUE TITLE
Fedora 23 repository?

### ISSUE THREAD

**Issue by MikeyCarter** [overviewer/Minecraft-Overviewer#1269]
Noticed the fedora repositories in http://overviewer.org/rpms/ only go to fedora 21.   Since fedora 21 is now EOL... would be good to get the later repos.

**Comment by enaut** [comment]
I just use git latest... in Fedora 23 which works like a charm. It is probably about the same amount of effort to set up the git version as it would be to set up external repositories.
I'm not really a member of the project but I think the lack of packages is mostly because noone seems too interested in doing the work.

**Comment by CounterPillow** [comment]
If I remember correctly, @aheadley made the RPM repositories, so he's the most likely person to provide new ones.

**Comment by enaut** [comment]
So hey there again... I decided to jump into the copr repository stuff and created a copr repository for F23 and F24.

I forked the git repository of Minecraft-Overviewer:
https://github.com/enaut/Minecraft-Overviewer

And added tito and RPM configuration files to the two branches stable-tito and weekly-tito.
With those two git branches I crated the two copr Repositories located at:
  * https://copr.fedorainfracloud.org/coprs/enaut/minecraft-overviewer/
  * https://copr.fedorainfracloud.org/coprs/enaut/minecraft-overviewer-weekly/

To install either do one of the following:

    # dnf copr enable enaut/minecraft-overviewer
    # dnf copr enable enaut/minecraft-overviewer-weekly

Then you can run like:

    > overviewer <world> <target>

All in all its working and I will try to update the weekly branch whenever there are new commits (which is far from weekly). Bugreports can go to this issue tracker as I'm following this anyway. It might be faster if you mention me directly or if I get a tag or something.

Hope that helps you :)

**Comment by agrif** [comment]
Hey! Sorry this took a while to get to. Ultimately we just needed to add a symlink!
