### ISSUE TITLE
debian installation : 404  Not Found

### ISSUE THREAD

**Issue by MrMaleficus** [overviewer/Minecraft-Overviewer#1277]
Hello,

I use overview since months ago, but when i attempted to install the latest update via "apt-get update" here the problem 

```
Ign http://overviewer.org ./ Translation-fr_FR                                           
Ign http://overviewer.org ./ Translation-fr                                                
Ign http://overviewer.org ./ Translation-en                                                
Err http://overviewer.org ./ Packages                    
  404  Not Found [IP : 2a01:4f8:110:31e8::2 80]
```
`W: Impossible to retrieve http://overviewer.org/debian/./Packages  404  Not Found [IP : 2a01:4f8:110:31e8::2 80]`

Is just the server down ?

**Comment by CounterPillow** [comment]
We had issues with the docker containers after an upgrade on the server last night, resulting in minor data loss. We'll fix it as soon as we can, thanks for the report

**Comment by eminence** [comment]
Ok, I think I fixed this.  Can you please check?   Thanks for your patience!

**Comment by MrMaleficus** [comment]
Fixed ! :) Thank you ;)

**Comment by eminence** [comment]
Thanks for confirming!
