### ISSUE TITLE
missing textures for 1.9 snapshots / prereleases

### ISSUE THREAD

**Issue by NoxNebula** [overviewer/Minecraft-Overviewer#1280]
The overviewer is searching the textures following textures in 1.9 snapshots / prereleases:
- [x] 'assets/minecraft/textures/blocks/redstone_dust_line.png'
- [x] 'assets/minecraft/textures/blocks/redstone_dust_cross.png'
- [x] 'assets/minecraft/textures/blocks/command_block.png'

I have to manually copy these textures from 1.8.* to the snapshot texturepath, in order to make the overviewer work.

`redstone_dust_cross` has been removed,
`redstone_dust_line` has been renamed to *0 respectively *1
`command_block` has now different textures, the best replacements should be command_block_back and command_block_front.

- [x] pathblocks are also not rendered (i use the git version of overviewer).

please fix

**Comment by xd1936** [comment]
Now that 1.9 is officially out, this should be very high priority.

**Comment by eminence** [comment]
Please give the latest commit from the `master` branch a test!

**Comment by seeseekey** [comment]
Hello,

i have tested the new version. The new end blocks renders well, but command blocks are not correctly rendered. There are empty on the map.

**Comment by SteseDav** [comment]
I'm getting the same problem on a Windows XP machine (don't ask), with 1.8.9 and 1.9 versions of Minecraft installed by the launcher. If the above fix works, when would it be normally included in the pre-compiled windows download?

**Comment by Yoplitein** [comment]
Grass path blocks are also not rendered.

**Comment by NoxNebula** [comment]
Tested the current master, rendering works with 1.9 textures, but pathblocks are still missing :(

**Comment by CounterPillow** [comment]
Path blocks are implemented in #1263 but somebody needs to review and merge that.

**Comment by eminence** [comment]
thanks for digging up that PR, i'll take a look tonight

**Comment by eminence** [comment]
Path blocks are now added in 5f9276a24a8d64efe4b91cf29c565b4541a0cdf0

Still todo is check on command blocks

**Comment by jason-green-io** [comment]
Chorus plants too :)

**Comment by eminence** [comment]
those are weiirrddd.  but i think we can do them

**Comment by NoxNebula** [comment]
The command blocks are not rendered correctly (see the arrows) and the cained and the repeating are not rendered at all: http://imgur.com/a/jDs64

**Comment by eminence** [comment]
looks like there are two new variants of command blocks that need to be added

**Comment by tazorax** [comment]
Beetroot crops added on PR #1284

**Comment by Jamdog** [comment]
The new 1.9 'Path' blocks also fail to render, leaving them black.

**Comment by NoxNebula** [comment]
@Jamdog they do render in the GitHub version

**Comment by agrif** [comment]
What's the current status with these blocks? What's left to do?

(Can I close this? 😄 )

**Comment by jason-green-io** [comment]
They render fine for me

**Comment by mvndrstl** [comment]
They work for me too. The only blocks that were not working were the chorus
plants.

Example of the paths working: http://maps.rycieos.com/#/-102/64/-73/-1/0/0

**Comment by agrif** [comment]
Ok! I'll close this then.

**Comment by urda** [comment]
Is there something special I have to do to render the newer textures? Everytime I've tried to move away from a `1.8` texture pack to something newer I get:

```
E Could not find the textures while searching for 'assets/minecraft/textures/blocks/redstone_dust_line.png'. Try specifying the 'texturepath' option in your config file.
```

**Comment by eminence** [comment]
@urda In order to not clutter up this issue, can you please open a new issue?  Please include your version of Overviewer, too.   Thanks!

**Comment by mide** [comment]
@urda I was having a similar issue with my installation. I recently moved my render over to Docker and performed a lot of the installation from scratch. Check out the `Dockerfile` and `entrypoint.sh` in [mide/minecraft-overviewer](https://github.com/mide/minecraft-overviewer) and maybe that will help.

**Comment by CounterPillow** [comment]
>Overviewer Version: Minecraft Overviewer 0.11.164 (da3e6fd) built on Tue Aug 5 21:59:17 2014

It's probably the 2 years out of date Overviewer version.
