### ISSUE TITLE
Chunk 0;0 is corrupted

### ISSUE THREAD

**Issue by iBars** [overviewer/Minecraft-Overviewer#1293]
My harddrive was broken and I restored what I was able to. I deleted all corrupted regions (checked in NBTExplorer) and used RegionFixer on another regions which not corrupted, but I have in all cases the same problem:

![ov](https://cloud.githubusercontent.com/assets/3519015/14407564/b5d854f6-fed6-11e5-83d7-c3bc6863529c.png)

**Comment by CounterPillow** [comment]
Chunk 0,0 is stored in level.dat as far as I remember. For what it's worth, if that one is corrupt, there's not really much Overviewer can do for you. Try loading up the world in Minecraft and visiting the chunk there.

**Comment by CounterPillow** [comment]
Closing this due to inaction from the initial reporter and this being a case overviewer can't really handle well in general.
