### ISSUE TITLE
Using overviewer's Debian repository results in weak digest algorithm warnings 

### ISSUE THREAD

**Issue by soc** [overviewer/Minecraft-Overviewer#1296]
Error message while updating package information:

```
An error occurred

The following details are provided:

W: http://overviewer.org/debian/./Release.gpg: Signature by key
97BDD17642A97E9B43E7FF23AB6EAF871F4C1BCE uses weak digest algorithm (SHA1)
```

My system:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

**Comment by E-PaiN** [comment]
I'm getting the same error on Debian

**Comment by agrif** [comment]
Looks like [Debian is phasing out SHA1 signatures](https://wiki.debian.org/Teams/Apt/Sha1Removal), so I changed our builders to use SHA512, which ought to last a while.

If the problem persists, re-open this and let me know, and I'll dig deeper.
