### ISSUE TITLE
Symbol not found: _estimate_blocklevel

### ISSUE THREAD

**Issue by mojca** [overviewer/Minecraft-Overviewer#1297]
I tried to create a package for overviewer for MacPorts (Mac OS X). After some tricks that were needed to find the imaging library the installation went fine, but when I try to run the program, it fails to find a function and load a library:

```
> overviewer.py "Demo_World" /tmp/demo
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/overviewer_core/__init__.py",
line 20, in check_c_overviewer
    import c_overviewer
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/overviewer_core/c_overviewer.so,
2): Symbol not found: _estimate_blocklevel
  Referenced from:
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/overviewer_core/c_overviewer.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/overviewer_core/c_overviewer.so
```

Maybe the code should be reorganized a bit or the `inline` could be removed.
See also http://stackoverflow.com/questions/4391202/symbol-not-found-linking-a-library

**Comment by eminence** [comment]
I wonder if this is related to #1276.  CC @agrif 

@mojca are you in a position to try to revert 1276 and see how that changes things for you?

**Comment by mojca** [comment]
Oh, sorry. I believe the reason was that I was compiling from the released version (as package manager should probably not use random commits) and the last release was on 2nd Sep 2014. The pull request probably fixes exactly the problem I was complaining about. I'll test.

**Comment by CounterPillow** [comment]
@mojca we don't really do "stable releases", git master branch HEAD is what you should always use.

**Comment by CounterPillow** [comment]
Any news on this? Can I close this as already resolved?

**Comment by mojca** [comment]
I tried the latest commit and the build works as expected. (And sorry for the delay.)

Thank you.

**Comment by mojca** [comment]
The package was committed in https://github.com/macports/macports-ports/commit/d775393371eaf261518c35cd72f1d65d3d52cd4b.
