### ISSUE TITLE
Issue with overviewer for minecraft 1.6.4

### ISSUE THREAD

**Issue by coupaul** [overviewer/Minecraft-Overviewer#1306]
Hey,
I actually work with overview linux for my 1.6.4 server, but when i start the script who render the map, it stop on the "Generating textures..." have you an idea fix that ?

Thanks for ur time !

Sorry for my english, i'm french :)

**Comment by CounterPillow** [comment]
By stop, do you mean it gets stuck, or does it crash?

Can you provide the output of what happens when you run overviewer with the arguments `--check-terrain -v`? Also, which version of Overviewer are you using?

**Comment by coupaul** [comment]
I use the same version in the documentation.
with apt-get install overviewer

**Comment by CounterPillow** [comment]
Since you've apparently managed to resolve the issue yourself, I'll close this. Feel free to let me know if you still have problems and want me to re-open this.
