### ISSUE TITLE
Player "Skin" texture not appearing on map

### ISSUE THREAD

**Issue by DIYglenn** [overviewer/Minecraft-Overviewer#1309]
For some reason the player skins doesn't appear on the map. They **sometimes** do for a random player. We're 6 in total, and typically it's 2 that works, sometimes 1, sometimes none. 
If you click the player, the skin appears in the text bubble. (Name is removed for this screenshot).

Anyone know why this is? 
![skin](https://cloud.githubusercontent.com/assets/10504432/16336061/bde79bc4-3a0a-11e6-8b5b-91457ab4b80f.png)

**Comment by CounterPillow** [comment]
Since this some work on the player skin endpoint of overviewer.org has been done. If this is still an issue, let me know and I'll reopen it.
