### ISSUE TITLE
Request: Google API value via command line or config file?

### ISSUE THREAD

**Issue by Krahazik** [overviewer/Minecraft-Overviewer#1318]
Until the change to a new system is implemented, could we get an option in the config file where the user can place their google api key, and add instructions for where to go to obtain a key to the wiki.

**Comment by djekl** [comment]
Check out this for how you can do it https://github.com/overviewer/Minecraft-Overviewer/issues/1308#issuecomment-235898484

**Comment by Krahazik** [comment]
@djekl - Yes I am aware of that one, and have used it, but that requires the user to manually edit the index.html file from the html source directory. Also requires hunting that particular post entry down for the information. 

The point of the config file is so that you don't have to go to specific files within the system and manually edit them with user specific information and configurations. A user specific API key would qualify as a config file item.

**Comment by djekl** [comment]
@Krahazik I do understand this yes, and thats why I linked that post there. In my opinion there would be no value in writing additional code for Google Maps, when they are working on the rewrite to the new map api.

**Comment by LeadMagnet** [comment]
Agree with @djekl no sense beating a dead horse. While I test the Leaflet version, putting the GAPI dev key in the index.html file of web_assets works a treat when re-rendering maps. Gets copied into the new render folder automatically. There was a post about this method but I can't find it.

**Comment by CounterPillow** [comment]
Overviewer now uses leaflet.
