### ISSUE TITLE
Help with Mobs

### ISSUE THREAD

**Issue by designermonkey** [overviewer/Minecraft-Overviewer#1320]
Is there any way to use this to locate where certain mobs will spawn? I want to look for slimes and would love to use this, as I already use it to map where I've been.

**Comment by CounterPillow** [comment]
To show slime spawns, you can use the SlimeOverlay [which has more details about it in the documentation](http://docs.overviewer.org/en/latest/config/#the-rendermode-primitives).

**Comment by designermonkey** [comment]
Awesome, I didn't think of overlays. Thanks.
