### ISSUE TITLE
Minecraft 2.0 causes Overviewer to fail.

### ISSUE THREAD

**Issue by 44trent3** [overviewer/Minecraft-Overviewer#1328]
So today I tried to render my map in Overviewer. However, since I have version 2.0 (it was a joke version of MC Mojang released in 2013) in my versions folder, it tried to load the textures from that file instead of 1.10.2, and failed as such. I presume this was caused because it just loads the textures from whatever the highest number in the versions file is.

**Comment by eminence** [comment]
Relevant part from @44trent3 's log that we saw in IRC:

```
textures.pyc:246   5756 2016-08-30 18:30:31 INFO     Found these versions: ['1.10', '1.10.2', '1.10.2-forge1.10.2-12.18.1.2065', '1.5.2', '1.5.2-Forge7.8.1.738', '1.6.2', '1.6.2ML', '1.6.4', '1.6.4-Forge9.11.1.1345', '1.7.10', '1.7.10-Forge10.13.4.1614-1.7.10', '1.7.7', '1.8.9', '1.9.4', '2.0', 'a1.0.14', 'a1.0.15', 'a1.1.2', 'a1.1.2_01', 'a1.2.0', 'a1.2.6', 'b1.2_02', 'b1.2_03', 'b1.4', 'b1.5_01', 'b1.7.3', 'c0.0.13a', 'c0.30_01c', 'Indev', 'inf-20100227', 'inf-20100627']
textures.pyc:275   5756 2016-08-30 18:30:31 INFO     Most recent version >=1.8.0: [2, 0]. Searching it for the file...
```


We probably should be trying other versions, if the first version we try didn't work.

**Comment by 44trent3** [comment]
Has this issue been resolved?

**Comment by CounterPillow** [comment]
I don't think so, but I think @eminence's suggestion is the right one to go ahead with. I'll assign this to myself and hope to get some work done on this.

**Comment by CounterPillow** [comment]
There, I fixed it. Not sure why the original code didn't do this, it's the obvious solution. I blame every dev but me.
