### ISSUE TITLE
Bad icon URLs

### ISSUE THREAD

**Issue by astronouth7303** [overviewer/Minecraft-Overviewer#1334]
`https://google-maps-icons.googlecode.com/files/home.png` is no longer available because of the shut down of google code.

The JS file is overwritten every time, so the work-around involves more sed.

**Comment by CounterPillow** [comment]
will be fixed with leaflet, since there we no longer use that icon.

**Comment by CounterPillow** [comment]
Overviewer now uses leaflet.
