### ISSUE TITLE
Request for older overviewer version.

### ISSUE THREAD

**Issue by sigurdtheone** [overviewer/Minecraft-Overviewer#1335]
I am running a private server for my friends with a custom texture pack. It would seem that after an upgrade from version 0.12.109-0~overviewer1 to 0.12.137-0~overviewer1 on ubuntu, Overviewer won't accept my texture pack anymore.

I figure the easiest solution for me would be to request the older version. I was hoping one of you may have the pre-compiled .deb package lying around somewhere?. Because it does not seem to be in the repo anymore. I will also settle for the source code, so i can compile it, but i can't seem to find anything but the newest versions anywhere.

I think the root cause concerns Overviewers inability to handle dynamic textures. Eg, multiple versions of the same textures or animated ones.

**Comment by CounterPillow** [comment]
Use git to check out an older version of the source code with `git checkout` specifying an older commit id.

>I think the root cause concerns Overviewers inability to handle dynamic textures. Eg, multiple versions of the same textures or animated ones.

Animated textures has nothing to do with multiple versions, as far as I see. We just don't support multiple versions of Minecraft for simplicity.

**Comment by sigurdtheone** [comment]
Roger that, ill checkout an older commit and compile from source. Thanks
Nicolas!
