### ISSUE TITLE
How to render with textures from mod packs?

### ISSUE THREAD

**Issue by Capri205** [overviewer/Minecraft-Overviewer#1337]
Hi. For the life of me I cannot get this to work for Orespawn (orespawn.com). I've tried all manner of combinations of setup and extracting png's, merging with default assets, and stand-alone, but the map will not render with them. Has anyone tried and successfully done this?

Thanks.

**Comment by CounterPillow** [comment]
Block rendering is hardcoded right now and Minecraft has no modding API, so there's not much we can do to support it. Sorry, it simply is not possible, unless you make your own modifications to textures.py for every block in every mod.

**Comment by Capri205** [comment]
Ah. I guess that explains that. Thanks as always for the prompt response.

**Comment by posicat** [comment]
It seems to me like a mod might be the solution for making this work.  It could piece together a directory of all needed texture packs, and then loop through all of the block IDs that the server knows about and write out the matching folder.  I'm a software engineer in real life, so I'd be up for the coding, but I know almost nothing about how Minecraft or Overviewer's internal structures that would need to be queried to extract the data, and format it appropriately.
