### ISSUE TITLE
Getting kicked out of server often

### ISSUE THREAD

**Issue by UberNoel** [overviewer/Minecraft-Overviewer#1341]
Hi ,
Internal Exception : io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: readerIndex(1068) + length(1) exceeds writerIndex(1068): UnpooledHeapByTeBuf(ridx: 1068,widx: 1068, cap:1068/1068)

Everyone in the server gets kicked like once or twice every few minutes and give this error. Fyi , the server isnt off , everyone has to just rejoin the server again. Is there a solution to fix this problem?

**Comment by CounterPillow** [comment]
How is this a Minecraft-Overviewer issue?

**Comment by UberNoel** [comment]
then where should i put this?

**Comment by CounterPillow** [comment]
I don't know. What software do you have an issue with?
Because this is not an error caused by Minecraft-Overviewer, since overviewer does not integrate with the Minecraft server at all.
