### ISSUE TITLE
Changing a Link?

### ISSUE THREAD

**Issue by BarynnD** [overviewer/Minecraft-Overviewer#1342]
Hello,

I just got done rendering my map on minecraft overviewer and I couldnt help but notice I got a strange link, file:///C:/Users/HP-PC/Desktop/Overviewer%20world/index.html#/219/64/-292/-9/0/0

I was wondering if I could change it to a link like: https://overviewer.org/warcraft/#/-2618/64/3464/-8/0/0
But I dont know how, if you lovely people could help me out that would be amazing!

I don't know if I have to edit the settings on the index.html but when I go in there to edit I saw an error that said If you can see this message, there is likely a problem loading the Overviewer javascript components.
         Check the javascript console for error messages.
I don't know if that has anything to do with it but, whatever

Thanks in advance :D

**Comment by chungy** [comment]
You'll need to host it on a web server. The file:// URI you see is merely because you are opening a local file in your web browser, no server involved.

**Comment by BarynnD** [comment]
Could you refer me to a web host, or server that I can host this map on?
Thanks.

**Comment by CounterPillow** [comment]
Most of us cannot give any specific recommendations for managed webhosting, since we usually take the more advanced route of administrating our own servers for this purpose, which usually requires some Unix skills.

If you are willing to pay for it, then webhosting can be found fairly easily for a low price.

**Comment by CounterPillow** [comment]
I'll close this for now, let me know if you have additional questions.
