### ISSUE TITLE
Only showing recent player markers

### ISSUE THREAD

**Issue by steveabraham** [overviewer/Minecraft-Overviewer#1344]
I think I know the answer to this, but is there any way at all that only recently logged in players can be shown as markers on the map?

I suspect this information isn't available to Overviewer, but wondered if anyone has any creative solutions?

We have a lot of players that haven't logged in for months, so would be keen for them not to be shown to help declutter the map.

**Comment by MasterofJOKers** [comment]
You can write a filter function using `poi['time']` as it seems: https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/aux_files/genPOI.py#L317

**Comment by steveabraham** [comment]
Aha, very nice, thank you, I'll have a play with that, see how I get on.

Thanks!

**Comment by CounterPillow** [comment]
Going to close this since `poi['time']` exists, let me know if you have further questions.

**Comment by a2597** [comment]
For anyone else searching for this, here is my POI filter for this:
note that tm_year could be substituted with month, or possibly something more complex to update automatically, but this works for my purposes.

`def playerIcon(poi):
	if poi['id']=='Player':
		if poi['time'].tm_year==2016:
			poi['icon']="http://overviewer.org/avatar/%s" % poi['EntityId']
			return "Last known location for %s" % poi['EntityId']`

**Comment by LeadMagnet** [comment]
Thanks a2597, I have the same problem. Server has been running for 6 years and there are hundreds of player files! :P This will be a blessing to our regular players. Thanks for sharing.

**Comment by steveabraham** [comment]
My Python-foo is weak, but for reference here's what I ended up with to just show players that have been active in the last 15 mins:

https://gist.github.com/steveabraham/c4781e51f6d0c0b5c74f99ea9132d202

**Comment by LeadMagnet** [comment]
Wow! I was a bit more generous, I gave them a year! :P Took me an hour to figure out! My phyton-foo is so far below weak ya can't see the bottom! :P
