### ISSUE TITLE
Corrupt NBT error message with working MP server files

### ISSUE THREAD

**Issue by jlsturgeon** [overviewer/Minecraft-Overviewer#1347]
For a couple weeks, I've been running a small multiplayer server for me and a friend, first on my NAS and then, due to poor performance, on my Win10 PC. After a power outage yesterday took down my PC while the server was running, Overviewer is giving me an error message when I try to update that world's maps. When I first restarted the server following the power outage, it did appear that some character data had been corrupted (no inventory, levels or achieves on the one character logged in at the time) but everything else was fine.  However, when I tried to run Overviewer on the world files the following morning, I received the following error:

2016-11-30 00:19:50  Welcome to Minecraft Overviewer!
2016-11-30 00:19:54 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 608, in <module>
  File "overviewer.py", line 469, in main
  File "overviewer_core\world.pyc", line 97, in __init__
  File "overviewer_core\nbt.pyc", line 29, in wrapper
  File "overviewer_core\nbt.pyc", line 37, in load
  File "overviewer_core\nbt.pyc", line 193, in read_all
CorruptNBTError: could not parse nbt: 'utf8' codec can't decode byte 0xc0 in position 10: invalid start byte

Press [Enter] to close this window.

I ran an NBT checker tool on the world files, and it identified no problems. The character with the corrupted data is also showing no further problems. Nothing seems to be wrong with the world, and at least one other mapping program works fine with it. I repeatedly tried re-running Overview after several hours of problem-free server uptime, always receiving the same error. I ran Overviewer for a different single player world and it was fine, so it's definitely these specific world files. I'm at a loss as to what else to try. Any suggestions? My friend and I have really been enjoying the beautiful maps as we explore and build!

**Comment by Rycieos** [comment]
Your level.dat file is probably corrupted. However, since Minecraft and another program disagree, it could be a simple problem to fix. Without being able to see the file, we can't do much. Can you upload your level.dat file to Dropbox or equivalent and link it here?

**Comment by CounterPillow** [comment]
One of these filehosts would be even more convenient than dropbox:

https://overviewer.org/upload/
http://pomf.cat/
https://catbox.moe/

**Comment by jlsturgeon** [comment]
I'm not familiar with those services, so hopefully it worked right. I uploaded the level.dat to https://a.pomf.cat/wfauib.dat, thanks!

**Comment by CounterPillow** [comment]
```
TAG_String("keepInvfal������"):
```

That seems weird.

**Comment by jlsturgeon** [comment]
I see that there are editors that can be used on level.dat files but I have not tried anything like that, partly since I had no idea what I'd be looking for or how to fix it if I did. Would you suggest using one to alter those characters?

**Comment by CounterPillow** [comment]
Yeah, or delete that tag entirely, since it appears to be a mashup of "keepInventory" and something else, even though "keepInventory" is already specified.

**Comment by Rycieos** [comment]
Make a backup first of course.

If you use [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases), you could delete that invalid tag and see if it works. It is under Data > GameRules.

**Comment by eminence** [comment]
if you just want a read-only NBT viewer, you can use http://overviewer.org/~achin/librs/dump.html

it won't be able to edit the file, though (but that would be a nice feature!)

**Comment by jlsturgeon** [comment]
I followed CounterPillow's and Rycieos's suggestions and it seems to have worked. Overviewer started rendering without throwing that error message again. Thanks for your help! Guess I will be adding a UPS to my Christmas list...

**Comment by Rycieos** [comment]
Off topic, but a backup would have solved this problem. Keeping daily world backups has saved my worlds from power outages more times than I can count.

**Comment by jlsturgeon** [comment]
Having not worked with Minecraft that long, I assumed that restoring a backup would wipe out everything built/explored since the previous backup. I didn't really want to do that since it seemed to be working other than Overviewer not rendering the maps. I actually hadn't yet decided what would be the best practice for backing up the MP server worlds; I set up my single player worlds to sync their world folders automatically to Google Drive and my NAS. Google Drive gives me version control ability without making separate backups. I generally don't keep anything vital on one local machine, but unfortunately I was still figuring out how to best set things up on the PC when this happened.
