### ISSUE TITLE
Could not find the textures while searching for 'assets/minecraft/textures/blocks/rail_normal_turned.png'.

### ISSUE THREAD

**Issue by bystones** [overviewer/Minecraft-Overviewer#1349]
Running the overviewer.py result in the following error:

    $ overviewer.py -c /home/minecraft/overviewer.conf
    2016-12-05 22:13:34 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/rail_normal_turned.png'. Try specifying the 'texturepath' option in your config file.
    Set it to the path to a Minecraft Resource pack.
    Alternately, install the Minecraft client (which includes textures)
    Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
    (Remember, this version of Overviewer requires a 1.10-compatible resource pack)
    (Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

The version is:

    $ overviewer.py -V
    Minecraft Overviewer 0.12.137 (7a0930a)
    built on Tue Sep 27 06:53:33 2016

The texture file:

    $ ls -la /home/minecraft/web/assets/
    total 15676
    drwxr-sr-x 2 minecraft www-data     4096 Dez  5 22:08 .
    drwxr-sr-x 5 minecraft www-data     4096 Jan  1  2016 ..
    -rw-r--r-- 1 minecraft www-data 16039975 Dez  5 21:52 JohnSmithLegacy.zip

Config file:

    $ cat overviewer.conf 
    worlds["bums"] = "/home/minecraft/server/default/bums"
    
    renders["normalrender"] = {
	    "world": "bums",
	    "title": "daylight on bums",
	    "rendermode": smooth_lighting,
	    "imgformat": "jpg",
	    "defaultzoom": 6,
	    "rendermode": [Base(biomes=False), EdgeLines(), SmoothLighting()],
    }
    
    outputdir = "/home/minecraft/web/map"
    texturepath = "/home/minecraft/web/assets/JohnSmithLegacy.zip"

Checksum for the texture file:

    $ sha1sum web/assets/JohnSmithLegacy.zip 
    2f1b9dc079aeaa0702be8722dded394d763c7e9d  web/assets/JohnSmithLegacy.zip

The texture pack is a fresh version from here: https://www.johnsmithlegacy.co.uk/.

**Comment by Rycieos** [comment]
This is a bug in the texture pack, not overviewer. It is missing the file 'assets/minecraft/textures/blocks/rail_normal_turned.png'. While a missing texture will work just fine in Minecraft (it will just use the default one), overviewer needs a complete texture pack because it does not have access to the default texture files.

**Comment by CounterPillow** [comment]
I think letting the user specify multiple texture packs to use as fallbacks would be a nice feature addition though.

**Comment by Rycieos** [comment]
I agree. Having a fallback on the vanilla jar would be the best last case fallback, because it is guaranteed to have all the textures.

**Comment by Rycieos** [comment]
It is used for rail corners. You can see that in the example [here](https://overviewer.org/example/#/-307/64/106/max/0/0).

**Comment by bystones** [comment]
I am not sure if I understand correctly how the overviewer and the ingame textures work but from my understanding is that the game will fall back to its default texture back if a texture is missing in a texture pack.

Assuming that that is the case I should see a default textured rail when I try to build a corner with the texture pack from above. But this does not happen? I only see textures from the texture pack:

![2016-12-06_18 56 15](https://cloud.githubusercontent.com/assets/2666688/20937133/e740d582-bbe5-11e6-93e9-ac7be76aec49.png)
![2016-12-06_18 59 08](https://cloud.githubusercontent.com/assets/2666688/20937160/fc0149b6-bbe5-11e6-8080-9c2d7391277f.png)

**Comment by Rycieos** [comment]
That file is missing, however, a few files are in its place: 'rail_rails.png' and 'rail_sleepers.png'. Do I also see that the rails in your screenshot are somewhat 3D? If they use a custom model, that could explain it.

**Comment by CounterPillow** [comment]
Overviewer now falls back to vanilla Minecraft textures for missing textures, allowing you to use resource packs that don't include all Minecraft textures.
