### ISSUE TITLE
Rendering two zooms at the same time

### ISSUE THREAD

**Issue by dogmatic69** [overviewer/Minecraft-Overviewer#1351]
See image for better explanation. This happens in chrome (+ incognito) and Midori, probably others

 ![](http://i.imgur.com/6dDKPmzg.jpg)

**Comment by CounterPillow** [comment]
Did you interrupt an ongoing overviewer render by any chance?

**Comment by dogmatic69** [comment]
Ye, I am pretty sure I have...

**Comment by CounterPillow** [comment]
Start overviewer again and let it finish rendering then (don't worry, the ETA will be a bogus number)

That should fix the issue.

**Comment by dogmatic69** [comment]
Oh, its on a cron and runs periodically. 

Do I need to delete all the files? You can see it for your self here map.shadowcraft.rocks

**Comment by CounterPillow** [comment]
No, overviewer will detect a half-finished render and resort to checktiles mode, which should fix the issue by itself.

**Comment by dogmatic69** [comment]
Ok, well it has done full renders since (every 15 minutes it runs) so does not seem like it. 

Later I will try delete everything and start over.

**Comment by dogmatic69** [comment]
I deleted everything from the server and started over, seems ok so far.

Must have been some glitch
