### ISSUE TITLE
Only render certain region

### ISSUE THREAD

**Issue by NgYShung** [overviewer/Minecraft-Overviewer#1357]
After building Overviewer and render a Minecraft world, I found out that my output file size is more than 800MB. I found out there are a lot of regions that don't need to be rendered (because it is a chunk with no buildings etc.) It would be very helpful if we can specify certain regions to only be rendered.

```
renders["world"] = {`
        # Only render region r.0.0, r.0.-1, r.-1.-1, r.-1.0 (.mca)
        "region": ["0,0", "0,-1", "-1,-1", "-1,0"]
}
```

**Comment by MasterofJOKers** [comment]
This feature is already available using the "crop" option of a render. Please have a look at the documentation: http://docs.overviewer.org/en/latest/config/#crop

**Comment by NgYShung** [comment]
Thanks for the quick answer. Although it only allow cropping block range but not chunks, but I'm taking that since I can just calculate the world coords myself. :+1:
