### ISSUE TITLE
set "defaultZoom" to "maxZoom" value [Support]

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1358]
Thanks to over zealous players, some of my maps render with insane zoom levels.

After each render, I have to manually change the overviewerConfig.js file for each world and set the "defaultZoom" value to the same value that's in "maxZoom". 

For example: After a render, "defaultZoom" will be 0, "maxZoom" will be 16. I edit "defaultZoom" to 16, save and close the file.

This results in the map displaying fully zoomed IN (at zero, zero (or spawn)) when first loaded. If I don't do this, sometimes the map is so zoomed out you can't even see it.

How do I automate this? How do I tell OV to insert this value for me?

**Comment by CounterPillow** [comment]
You can set `defaultzoom` in the render dictionary of your config file.

**Comment by LeadMagnet** [comment]
Yes I know this can be set. Problem is, it would have to set it to the "lowest common denominator".

Of the 10 maps I render, the maxZoom value ranges from a HI of 16 to a LO of 9. So in order to have a valid number, I would have to set them all to 9. For the maps with 16, this isn't enough.

Looks like a job for Newtonsoft and the fileWatcher object! :P

**Comment by CounterPillow** [comment]
Huh? `defaultzoom` is per render dict entry, not global for the entire map.

**Comment by LeadMagnet** [comment]
Yeah that wasn't really clear! :P My point was, if I set the default level to 9, and the map grows and the new number "could  be" 10, there is no way of knowing this. Either way, looks like this is going to be a manual process. Thanks for the info.
