### ISSUE TITLE
SSL cert for overviewer.org

### ISSUE THREAD

**Issue by varspoolr** [overviewer/Minecraft-Overviewer#1362]
Hello, not sure if this is the best place to report this but the ssl certificate for overviewer.org expired on 1/26/2017.  I only noticed because it caused my player icons to break, chrome fails while connecting to the website.

![image](https://cloud.githubusercontent.com/assets/25387005/22373343/59bd7d8e-e46f-11e6-8be5-e7b0704aaa4a.png)

![image](https://cloud.githubusercontent.com/assets/25387005/22373426/c8d4ebda-e46f-11e6-98ac-f018e517e5d4.png)

**Comment by eminence** [comment]
Very sorry!  The letsencrypt cert expired, but has just been renewed.  Thanks.

**Comment by varspoolr** [comment]
Thank you, this is the #1 minecraft map renderer and we appreciate your support!!!

**Comment by eminence** [comment]
Thank *you* !
