### ISSUE TITLE
API KEY Problem

### ISSUE THREAD

**Issue by Raphy123** [overviewer/Minecraft-Overviewer#1365]
Hi,

My map is rendered and I have this error when I want to go on the .html

Screenshot 
http://prntscr.com/e97ell

I have put my API KEY but I have an JS error...

Regards

**Comment by CounterPillow** [comment]
Your API key seems to be invalid.

**Comment by Raphy123** [comment]
Yes.. but I have created this on google api.. ?

Strange.. ?

**Comment by Raphy123** [comment]
What api key we must to choose ?

**Comment by LeadMagnet** [comment]
To confirm you have a valid key or to get a new one, go here

https://developers.google.com/places/web-service/get-api-key

**Comment by Raphy123** [comment]
That's ok for me :) 

I have found. But... Big problem 👍 http://mineskill.fr/rendu/#/-175/64/661/-27/0/0
My map is not here xD

**Comment by LeadMagnet** [comment]
Try rendering it again. To be safe, I'd delete the contents of the target directory, to be sure you get good results.

**Comment by Raphy123** [comment]
Ok man :)

Can you send me the link of the texture pack you use ?

**Comment by LeadMagnet** [comment]
Overviewer uses the default texture pack. The easiest way to install the default textures is to install Minecraft, or at least run the launcher. If you want to use a custom texture pack, read the documentation here:

http://docs.overviewer.org/en/latest/running/#installing-the-textures
