### ISSUE TITLE
snapshot 17w0x

### ISSUE THREAD

**Issue by lipki** [overviewer/Minecraft-Overviewer#1367]
Hello, the new blocks of the 17w0x snapshot are not visible (but they do shade), despite the presence of a correct resource pack.
Is it normal ?
And if so, is it possible to solve the problem?

tested on master

**Comment by CounterPillow** [comment]
Someone needs to add them to textures.py in order to have them rendered. I'll look into it.

**Comment by lipki** [comment]
I tried, but, I had to make a mistake, it does not work anymore, even removing modifications :)
I do not have time today, but I would retest in the week if nobody does it.

```
White Glazed Terracotta.png 	235 	EB 	minecraft:white_glazed_terracotta 	White Glazed Terracotta
Orange Glazed Terracotta.png 	236 	EC 	minecraft:orange_glazed_terracotta 	Orange Glazed Terracotta
Magenta Glazed Terracotta.png 	237 	ED 	minecraft:magenta_glazed_terracotta 	Magenta Glazed Terracotta
Light Blue Glazed Terracotta.png 	238 	EE 	minecraft:light_blue_glazed_terracotta 	Light Blue Glazed Terracotta
Yellow Glazed Terracotta.png 	239 	EF 	minecraft:yellow_glazed_terracotta 	Yellow Glazed Terracotta
Icon 	Dec 	Hex 	Name 	Block
Lime Glazed Terracotta.png 	240 	F0 	minecraft:lime_glazed_terracotta 	Lime Glazed Terracotta
Pink Glazed Terracotta.png 	241 	F1 	minecraft:pink_glazed_terracotta 	Pink Glazed Terracotta
Gray Glazed Terracotta.png 	242 	F2 	minecraft:gray_glazed_terracotta 	Gray Glazed Terracotta
Light Gray Glazed Terracotta.png 	243 	F3 	minecraft:light_gray_glazed_terracotta 	Light Gray Glazed Terracotta
Cyan Glazed Terracotta.png 	244 	F4 	minecraft:cyan_glazed_terracotta 	Cyan Glazed Terracotta
Purple Glazed Terracotta.png 	245 	F5 	minecraft:purple_glazed_terracotta 	Purple Glazed Terracotta
Blue Glazed Terracotta.png 	246 	F6 	minecraft:blue_glazed_terracotta 	Blue Glazed Terracotta
Brown Glazed Terracotta.png 	247 	F7 	minecraft:brown_glazed_terracotta 	Brown Glazed Terracotta
Green Glazed Terracotta.png 	248 	F8 	minecraft:green_glazed_terracotta 	Green Glazed Terracotta
Red Glazed Terracotta.png 	249 	F9 	minecraft:red_glazed_terracotta 	Red Glazed Terracotta
Black Glazed Terracotta.png 	250 	FA 	minecraft:black_glazed_terracotta 	Black Glazed Terracotta
White Concrete.png 	251 	FB 	minecraft:concrete 	Concrete S
```

**Comment by JRSofty** [comment]
When will this commit be released? Just asking because the 0.12.184 (dd96d95) built on 24 March 2017 doesn't seem to have this change. Things like light gray concrete and light gray concrete powder are not showing up on the map.

**Comment by CounterPillow** [comment]
The snapshot branch will be merged into the master branch once the minecraft release happens. If you need the functionality right now, clone the git repository and check out the "snapshot" branch and build it yourself:

```
git clone https://github.com/overviewer/Minecraft-Overviewer.git
cd Minecraft-Overviewer
git checkout snapshot
./setup.py build
```
You can then run it with `./overviewer.py` in the `Minecraft-Overviewer` directory.

**Comment by fredkilbourn** [comment]
Will be merged soon now with the release?

**Comment by CounterPillow** [comment]
Has been merged.

**Comment by fredkilbourn** [comment]
Fedora RPM on the downloads page still isn't up to date, should it show up automatically or is there an issue? https://overviewer.org/downloads

**Comment by CounterPillow** [comment]
@fredkilbourn it's broken, and has been for a while.
