### ISSUE TITLE
Google maps did not load correctly

### ISSUE THREAD

**Issue by ICEconchy** [overviewer/Minecraft-Overviewer#1371]
Page didn't load google maps.

http://pasteboard.co/I8gMqeUW4.png

**Comment by Wruczek** [comment]
Duplicate of #1308 
Current solution: https://github.com/overviewer/Minecraft-Overviewer/issues/1308#issuecomment-228310624
Or you can just wait for the leaflet version of Overviewer to come out.

**Comment by CounterPillow** [comment]
Closed as duplicate.

We're working on it.
