### ISSUE TITLE
Question: Documentation Images

### ISSUE THREAD

**Issue by JeromSar** [overviewer/Minecraft-Overviewer#1374]
Hi, 
I'm wondering how the informational images on the read the docs page were created. Specifically the ones depicting chunks, blocks and axes, like the ones below

![chunk width](http://docs.overviewer.org/en/latest/_images/chunk_width.png)
![cube stack](http://docs.overviewer.org/en/latest/_images/cube_stack16.png)

Any information would be of great help, thanks!

**Comment by CounterPillow** [comment]
pinging @brownan, since I believe he's the one who made these.

My guess is Inkscape.

**Comment by CounterPillow** [comment]
Actually, I just checked the design subfolder in the docs folder and the original SVGs are in there, and the SVG files contain references to Inkscape, so yes, these were created with [Inkscape](https://inkscape.org/).

**Comment by JeromSar** [comment]
@CounterPillow. Thanks much! :)
