### ISSUE TITLE
Texture pack use help

### ISSUE THREAD

**Issue by cyris69** [overviewer/Minecraft-Overviewer#1376]
Is it possible to use textures beyond the vanilla ones? So for instance I'd like to be able to map my server offline and when I choose so this software is perfect. However, I run a Tekkit Legends (1.7.10) server so no matter how I set texture path aka the zip file I use ingame or it unzipped (doesn't work it seems) it won't render any non-vanilla blocks. I get no errors of missing textures so not sure what to do and really loath having to go back to dynmap.

Any and all help would be appreciated.

**Comment by CounterPillow** [comment]
Mod blocks are not supported, sorry. This is because blocks are hardcoded in overviewer, and even if we implemented block models for rendering, we still wouldn't be able to render mods since they (as far as I'm aware) do their own thing altogether.
