### ISSUE TITLE
Getting an error with this config.

### ISSUE THREAD

**Issue by andrewkm** [overviewer/Minecraft-Overviewer#1378]
Error:
https://pastebin.com/raw/Bdefg1Qn
http://i.imgur.com/Gee4ZGL.png

Config:
https://pastebin.com/raw/ZhPD6bh9

**Comment by andrewkm** [comment]
Something to do with this setting I believe:
"crop": (-15000, -15000, 15000, 15000),

This works fine:
"crop": (-100, -100, 100, 100),

While this (the size of my actual map) does not:
"crop": (-15000, -15000, 15000, 15000),

**Comment by CounterPillow** [comment]
looks like a bug, thanks for reporting.

**Comment by andrewkm** [comment]
Seems it had something to do with files remaining in the final folder from the previous render. Once files were deleted the error went away. Hoping this assists you in finding the cause.

**Comment by andrewkm** [comment]
Any updates on this?
