### ISSUE TITLE
Refuses to run as it won't pickup textures.

### ISSUE THREAD

**Issue by FrozenBeard** [overviewer/Minecraft-Overviewer#1381]
I installed via Debian sources. Added the repository, activated the key, updated, installed.
Pre-generated my world.
Run the script, and oh look no textures included! ok, time to trawl through all the docs for ages to figure out why.
Now I have to create a config, I do this, heres my config.

```

worlds["PirateCraft_2"] = "/home/tom/piratecraft/games/PirateCraft_2/"

renders["normalrender"] = {
    "world": "PirateCraft_2",
    "title": "PirateCraft Games World.",
}

outputdir = "/home/tom/gamesmap/"
texturepath = "/home/tom/gamesmap/texture/1.11-Dokucraft-TSC-Light.zip"
```

I run my config with:
`overviewer.py --config=/home/tom/gamesmap/texture/config_file`

I have tried, 2 resource/texture packs, I have tried them zipped, I have tried them unzipped ALL the times its giving me:

```
:~/gamesmap/texture$ overviewer.py --config=/home/tom/gamesmap/texture/config_file
2017-06-03 19:03:31  Welcome to Minecraft Overviewer!
2017-06-03 19:03:31  Generating textures...
2017-06-03 19:03:34 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/brewing_stand_base.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.11-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

```

It is not listening to texturepath in the config, same issue if I run without the config, it refuses to work.

**Comment by CounterPillow** [comment]
>Run the script, and oh look no textures included!

because it wouldn't be legal to include Minecraft's textures.

>I have tried, 2 resource/texture packs

They're probably not 1.11 compatible resource packs.

Use the client textures as described in [this section of the documentation](http://docs.overviewer.org/en/latest/running/#installing-the-textures) which you apparently did not find as you "trawled through the docs for ages" before deciding to be a passive-aggressive dick on a github issue tracker.

**Comment by FrozenBeard** [comment]
They are both 1.11 compatible texture packs, dokucraft is a massively known pack, it's definitely 100% 1.11.

**Comment by CounterPillow** [comment]
Overviewer doesn't fallback from texture packs to default textures, so if a texture pack doesn't include `assets/minecraft/textures/blocks/brewing_stand_base.png`, then it can't find it.
