### ISSUE TITLE
Bed block texture errors with 1.12

### ISSUE THREAD

**Issue by fredkilbourn** [overviewer/Minecraft-Overviewer#1383]
Running Overviewer on 1.12 release with 1.12 jar for textures, bed isn't a block any more it's an entity, textures/blocks/bed* no longer appears to exist.

```
overviewer.py:612  16559 2017-06-07 18:36:01 ERROR    Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

**Comment by JiFish** [comment]
I worked around this using `texturepath` and a custom resource pack with the 1.12 assets plus the bed textures mcdungeon wants. It works, but obviously rendering beds is broken.

**Comment by fredkilbourn** [comment]
I went the same route, but yes, needs updating!  (along with glazed terracotta and other things)

**Comment by gaboreszaki** [comment]
Same route, same result :)

**Comment by CounterPillow** [comment]
Looks like Minecraft changed the bed textures. They can now be multicoloured and all parts of the bed are in a single image file, in `assets/minecraft/textures/entity/bed`. This will need some textures.py hacking to get it back to working.

**Comment by CounterPillow** [comment]
Fixed in master. Note that the automatic Windows builders aren't running, so if you're on Windows, you'll have to compile yourself.

**Comment by JiFish** [comment]
@CounterPillow are the windows builds gone forever? or is it a temporary thing?

**Comment by CounterPillow** [comment]
@JiFish hopefully a temporary thing

**Comment by valeriez** [comment]
@CounterPillow I'm using windows for overviewer. How do I compile this?

**Comment by CounterPillow** [comment]
@valeriez there are different ways to build Overviewer on Windows, they're explained in [the documentation, section Building Overviewer from Source](http://docs.overviewer.org/en/latest/building/#windows-build-instructions). However, you don't need to do this, we have some preliminary updated builds available here: http://static.overviewer.org/builds/master/861/

**Comment by AugustT** [comment]
@CounterPillow This solved my problem but it took 2 days to find this issue on Github. Could you add a note to the great documentation you have put together so that others don't get stuck for so long?

**Comment by CounterPillow** [comment]
Well, if I wanted to take my time to work on Overviewer, I'd just put the fixed builds on the download page

**Comment by morantis** [comment]
then why did you start a software project?  Another case of irresponsible coding.  You start a project and make it public and that is your to tend to FOR LIFE.  You are there to accept the "good job"s, but never there to tow the line when it comes to it.  Another coder that is nothing but a joke.

**Comment by CounterPillow** [comment]
@morantis go troll somewhere else

**Comment by morantis** [comment]
And I rest my case!  Thank you for showing your true colors.

**Comment by CounterPillow** [comment]
ok bye

**Comment by fredkilbourn** [comment]
wow @morantis get over yourself, I hope you're just trolling and don't actually believe anyone owes you the hours and hours it takes to make _free_  software

**Comment by CounterPillow** [comment]
I don't think they get that contributing to software does not mean becoming a slave working for free for the rest of one's life, probably because they don't write any software themselves. Go figure.

Either a troll or some middle-management knob who likes to play a bit of Minecraft inbetween sexually harassing their underlings.

Whatever reason they have for making dumb comments on the internet, it's best to not dwell on those, and it would be a shame if I had to ask someone with the necessary permissions to lock an issue for the first time in Overviewer history.

**Comment by AugustT** [comment]
Well, that got out of hand pretty quick! Needless to say I don't share the views of @morantis. I usually take the view that the more issues I get from users the better my software is. The curse of success.
