### ISSUE TITLE
Minecraft 1.12 not rendering.  Error with missing PNG

### ISSUE THREAD

**Issue by Kenduskeag** [overviewer/Minecraft-Overviewer#1385]
Figured I'd pass this along.  There is a major difference in the number of PNG files in the 1.12 client JAR (less) than in 1.11.2 (much more).  This is causing errors when attempting to render.

c:\Overview>c:\overview\overviewer.exe --config=file.conf
2017-06-10 11:16:51  Welcome to Minecraft Overviewer!
2017-06-10 11:16:51  Generating textures...
2017-06-10 11:17:10 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

As a workaround, I snagged the 1.11.2 JAR from my daughter's computer and put it into my minecraft directory.  Once there, I updated the variable in my file.conf.

texturepath = r"C:\Minecraft\1.11.2.jar"

It is working as intended now and the render is churning away.  Not sure if this is a feature or a bug issue since 1.12 released on June 7, 2017.  Regardless, figured I'd ask.

Anyways, thanks for your time.
--Kenduskeag

**Comment by mhvis** [comment]
I think this is the same bug as reported here: #1383 . It should already have been fixed in the master branch.

**Comment by CounterPillow** [comment]
Already fixed, there currently aren't any new builds for windows right now because of @eminence
