### ISSUE TITLE
1.12 Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'.

### ISSUE THREAD

**Issue by marksnell** [overviewer/Minecraft-Overviewer#1387]
In 1.12, there is no assets/minecraft/textures/blocks/bed_feet_top.png in the .jar on Windows, 
I'm guessing this is due to the new coloured bed options.
I'm currently working around it by specifying the 1.11.2 jar as the texturepack

**Comment by CounterPillow** [comment]
this is because the windows builds are out of date. Already fixed in git master.

**Comment by AndrewSav** [comment]
May I venture a suggestion to close this issue *after* the windows builds are available, not before. Closing it like that does not let people interested in a fix to track progress on this been done.

**Comment by CounterPillow** [comment]
@AndrewSav no, there already is #1390
