### ISSUE TITLE
Minecraft 1.12 not rendering concrete_silver.png

### ISSUE THREAD

**Issue by maxolasersquad** [overviewer/Minecraft-Overviewer#1388]
After updating to Minecraft 1.12 I cannot generate maps anymore.

```
Could not find the textures while searching for 'assets/minecraft/textures/blocks/concrete_silver.png'. Try specifying the 'texturepath' option in your config file.
```

I'm running Ubuntu 16.04 and the latest version over overviewer.py from the repo.

**Comment by eminence** [comment]
This might be a little annoying for you, but can you try one of the builds from here:

http://static.overviewer.org/builds/master/801/

I'll try to make updating our .deb and .rpm repos a priority

**Comment by CounterPillow** [comment]
The debs are up to date, including the repositories. I'm assuming the issue here is that you did not update your texture files to 1.12.

**Comment by maxolasersquad** [comment]
You are correct. Following the instructions at http://docs.overviewer.org/en/latest/running/#installing-the-textures got me going again.
