### ISSUE TITLE
Unable to render new maps

### ISSUE THREAD

**Issue by lunardust** [overviewer/Minecraft-Overviewer#1391]
Hello. 

For the past 2 days, I have been attempting to render worlds, and no matter what I do, I get the same error. "ERROR    Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'."

The thing that is confusing me is that I opened up the zip folder I'm pointing to and the file is in there. I even opened it to make sure it was correct and it was. I've tried all manners of bug fixing from reinstalling overviewer, restarting computer, generating worlds in 1.9, 1.10, 1.11 and 1.12, and even deleting my entire .minecraft folder and starting from scratch. Nothing so far has corrected this error.

**Comment by CounterPillow** [comment]
If you're using a config file, could I see that?

**Comment by lunardust** [comment]
[test.txt](https://github.com/overviewer/Minecraft-Overviewer/files/1082503/test.txt)

**Comment by CounterPillow** [comment]
According to the docs:

>If specifying a folder, this option should point to a directory that contains the assets/ directory (it should not point to the assets directory directly or any one particular texture image).

Can you show me `1.10_Default_Resource_Pack.zip` so I can make sure this is the case?

**Comment by lunardust** [comment]
[1.10_Default_Resource_Pack.zip](https://github.com/overviewer/Minecraft-Overviewer/files/1082507/1.10_Default_Resource_Pack.zip)

**Comment by CounterPillow** [comment]
This is packed wrong. It has the `assets` directory in a subdirectory called `1.10 Default Resource Pack`.

That being said, if you just want the default textures for 1.10, just specify `whatever/your/appdata/folder/is/.minecraft/versions/1.10/1.10.jar` as your `texturepath`.

**Comment by lunardust** [comment]
I changed it to the .jar and it still failed with the same error.

**Comment by lunardust** [comment]
It fixed. Thank you.
