### ISSUE TITLE
Couldn't find requested dimension

### ISSUE THREAD

**Issue by jamesmweir3** [overviewer/Minecraft-Overviewer#1394]
I've had Overviewer working fine for years with the overworld, but for some reason I cannot get the End or Nether to work.  I'm guessing it has something to do with the way the directories are split up.

/opt/msm/servers/Myserver/worldstorage/myserver/level.dat = overworld
/opt/msm/servers/Myserver/myserver_the_end/level.dat = end
/opt/msm/servers/Myserver/myserver_nether/level.dat = nether

My overworld config works fine:
renders["survivalday"] = {
    "world"      : world,
    "title"         : "Day",
    "rendermode" : smooth_lighting,
    "imgformat"  : "jpg",
    "imgquality" : 90,
    "dimension"  : "overworld",
    "manualpois" : poilocations,
    "markers"    : [dict(name="Locations", filterFunction=locationFilter)]
}

But the Nether does not:
renders["survivalnether"] = {
    "world"      : world,
    "title"      : "The Nether",
    "rendermode" : "nether_smooth_lighting",
    "imgformat"  : "jpg",
    "imgquality" : 90,
    "dimension"  : "../../myserver_nether/DIM-1/",
    "markers"    : []
}

I've tried "nether", the relative path, the absolute path, creating a symlink to the directory, with and without trailing slashes, with and without the DIM1/DIM-1 directories.

**Comment by CounterPillow** [comment]
the dimension key as far as I remember does not accept directories. Normally, dimensions are within the `DIM1` and `DIM-1` subdirectories of a world, but your dimensions are actually structured like separate worlds altogether. Instead of trying the dimension key, treat them as separate worlds.

**Comment by jamesmweir3** [comment]
Ok, I'll try setting them up that way.  The docs did mention that Bukkit servers were a bit more complicated but didn't mention how so.  Also it does say they can take directories, but perhaps only the DIM1/DIM-1 ones?

> The value should be a string. It should either be one of “overworld”, “nether”, “end”, or the directory name of the dimension within the world. e.g. “DIM-1”

**Comment by CounterPillow** [comment]
Only of directories within the world, but your dimensions are different worlds entirely, i.e. not sub-directories of the world directory.

**Comment by jamesmweir3** [comment]
Separate worlds worked great.  Thanks for the help!
