### ISSUE TITLE
Windows compiling, last instruction

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1395]
So I'm going through and building a VM for the sole purpose of compiling Overviewer.

The instructions () are very clear, easy to follow. Ran through it all without issue.

That is until the very last line...

`After it finishes, you should now be able to execute overviewer.py from the MINGW64 shell.`

Since step 5 has you running commands inside MINGW64 shell, I tried just typing "overviewer.py". 

user1@testpc MINGW64 ~/Minecraft-Overviewer
$ overviewer.py
bash: overviewer.py: command not found

That give me a command not found error. I'm fairly certain this is a pathing issue to the Python libraries, just not sure where.

Thoughts?

**Comment by CounterPillow** [comment]
Try `./overviewer.py`

The `./` means "execute this file in the local directory"; using `overviewer.py` won't work unless you add it to your `PATH`.

**Comment by LeadMagnet** [comment]
That worked like a charm! Thanks!

It didn't occur to me i was building an EXE-less version. That I'd need Phyton on the production machine. But not a problem. The compile process worked great and (with the ./) runs just fine! :D
