### ISSUE TITLE
Windows Automation

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1396]
I'm running OV on a Windows 2012R2 server. For years I have been executing a batch file to render all of the worlds for my MC server. It looks something like this...

```
cd C:\overviewer_GAPI
overviewer.exe -c configs\C_config.py > c:\overviewer_GAPI\logs\C\log.txt
overviewer.exe -c configs\W1_config.py > c:\overviewer_GAPI\logs\W1\log.txt
overviewer.exe -c configs\W1_config.py --genpoi --skip-scan > c:\overviewer_GAPI\logs\W1\log_poi.txt
```

The actual file is much larger, many more lines for alot of worlds but you get the point.

Following the instructions from "Building with mingw-w64 and msys2" and I've got the latest OV source compiled (or at least I think I do).

Running the command...
`./overviewer.py -c configs/W1_config.py`
...outside of the MinGW64 shell does not work. Inside the shell I get the following error:

```
Traceback (most recent call last):
  File "./overviewer.py", line 624, in <module>
    ret = main()
  File "./overviewer.py", line 427, in main
    assetMrg = assetmanager.AssetManager(destdir, config.get('customwebassets', None))
  File "./overviewer_core/assetmanager.py", line 47, in __init__
    self.fs_caps = get_fs_caps(self.outputdir)
  File "./overviewer_core/files.py", line 27, in get_fs_caps
    return {"chmod_works": does_chmod_work(dir_to_test),
  File "./overviewer_core/files.py", line 38, in does_chmod_work
    f1 = tempfile.NamedTemporaryFile(dir=dir_to_test)
  File "C:/msys64/mingw64/lib/python2.7/tempfile.py", line 475, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "C:/msys64/mingw64/lib/python2.7/tempfile.py", line 257, in _mkstemp_inner
    raise IOError, (_errno.EEXIST, "No usable temporary file name found")
IOError: [Errno 17] No usable temporary file name found
```

I've installed Python 2.7.13(64bit) onto the machine so I can try something like..

`python.exe overviewer.py -c configs/W1_config.py`

But this isn't working either. All paths have been added to the locals machine config so its not a referencing error.

**So how do I automated the render process using the recommended Windows build method?**

What's even more confusing is the build folders created by MinGW64 don't match the folder structure for the Windows ZIP downloaded version. Not even close. So I'm not even sure what files are need and where they are.

Trying to get away from the need for the Windows EXE, but this final step isn't documented very clearly.

Assuming the Overviewer.exe was just a Python wrapper, I coppied it into the MinGW64 build folder and tried it that way. Yeah that didn't work either! :P

**Comment by CounterPillow** [comment]
not sure what the named temporary file failure is about, probably some Windows weirdness. I'd have to try it myself again some time to debug it.

However, `python.exe overviewer.py -c configs/W1_config.py` obviously won't work if you're not in the very directory that overviewer.py resides in, since python.exe doesn't load files from `PATH` but just loads the filename.

>Assuming the Overviewer.exe was just a Python wrapper, I coppied it into the MinGW64 build folder and tried it that way. Yeah that didn't work either! :P

No, it's a whole python interpreter with overviewer's code in it.
