### ISSUE TITLE
Something has gone wrong importing the c_overviewer extension

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1397]
Using the latest overviewer-win64-0.12.196.zip  and running on the same machine that has been running 0.12.135 I get the following error

Something has gone wrong importing the c_overviewer extension.  Please
make sure the 2008 and 2010 redistributable packages from Microsoft
are installed.

Since version 0.12.135 runs fine (2008 and 2010 redistributable both 32 and 64 bit installed) I'm not sure what to make of this.

**Comment by CounterPillow** [comment]
that error message is not yet updated for the new builds, which will require a newer redistributable, downloadable here: https://go.microsoft.com/fwlink/?LinkId=746572

**Comment by LeadMagnet** [comment]
downloaded and installed.

ran overviewer.exe -c configs\W4_config.py --forcerender -v 

It's running, but all world renders now have the same error. Turned on verbose logging and dumped it into Gist

https://gist.github.com/LeadMagnet/dad16181105a31f6443a9415199d1717

So if this is a corrupt region, why did it stop? 

0.12.135 rendered this chunk without issue.

**Comment by CounterPillow** [comment]
that is something I probably goofed up, thanks for reporting, will look into it

**Comment by wevertonslima** [comment]
same error here any solution?

**Comment by LeadMagnet** [comment]
rendered using version 0.12.267 and it's working
