### ISSUE TITLE
render automatic for windows

### ISSUE THREAD

**Issue by Svenman2** [overviewer/Minecraft-Overviewer#1398]
Hello all,

I have a question is there a way to make the Mc Overviewer automatic on a particular day and time?
What do I have to do for that? Because I can not find anywhere on the internet for windows!

We run on windows 10.

Thank you for your response.

**Comment by enaut** [comment]
There are various ways...
You will probably want to write some script or make the configuration elaborate enough so you have just one command to run overviewer. You can run that command with one of the tools described in the answers of: https://stackoverflow.com/questions/132971/what-is-the-windows-version-of-cron

**Comment by Svenman2** [comment]
Hello enaut

Thank you for your link, along with a friend that she was the same that I could use schtask's best.
Hereafter I did the following to get it all working

First create a bat file with the following text.
`@echo off

cd /d D:\de-club-fan-server\plugins\overviewer-0.12.137/
overviewer.exe "D:\de-club-fan-server\world" D:\xampp\htdocs
pause`

then
_Schtasks / create / tn "Map Overviewer" / tr D: \ de-club-fan-server \ plugins \ overviewer-0.12.137 \ RunOverviewer.bat / sc weekly / d THU / st 2:00_

And then you need to edit another file because google maps key otherwise eleke times will be appropriate because the overviewer.exe returns everything to default values every time.

Go to the Web_assets folder and then edit index.

<Script type = "text / javascript" src = "https://maps.google.com/maps/api/js?sensor=false"> </ script>
to
<Script type = "text / javascript" src = "https://maps.google.com/maps/api/js?key=<own api key> & sensor = false"> </ script>
