### ISSUE TITLE
Generated map does not work on some webservers

### ISSUE THREAD

**Issue by uszasty** [overviewer/Minecraft-Overviewer#1401]
Those two locations has the same minecraft map loaded. One works, one does not
http://krysztal.ct8.pl/out/#/-287/64/119/-5/0/0 <-works
https://smiesznadomena.ml/krysztal/out/#/-287/64/119/-5/0/0 <- does not work
For the record, I've found one host without https that does not work either, but I'm not allowed to share it.
It works localy too, I can upload it as a .zip if it's needed.

I believe those two errors are exclusive for "not working" hosts:
```js?sensor=false:35 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error```

```overviewer.js:1230 Uncaught TypeError: Cannot read property 'lat' of undefined
    at Object.updateHash (overviewer.js:1230)
    at ug.<anonymous> (overviewer.js:817)
    at _.A.trigger (js?sensor=false:100)
    at common.js:27
    at Ax.G (map.js:32)```

**Comment by CounterPillow** [comment]
https://github.com/overviewer/Minecraft-Overviewer/issues/1308
