### ISSUE TITLE
Running Overviewer on Win10 and MC vanilla 1.12 and get an error

### ISSUE THREAD

**Issue by drysz** [overviewer/Minecraft-Overviewer#1403]
I had run overviewer on this Win10 machine back in February but I upgraded to MC 1.12. It didn't work so I went and downloaded overviewer-win64-0.12.196.zip. I deleted my c:\mcmap contents and tried running it again with the same error. any ideas on how to fix this? Thanks! This is Minecraft server running on Win10.

~Dave / H0logram

C:\Minecraft\OverViewer>c:\minecraft\overviewer\overviewer.exe --verbose C:\Minecraft\RyszCraft2\RyszCraft c:\mcmap
overviewer.py:275  5264 2017-08-02 18:52:59 DEBUG    Using 'C:\\Minecraft\\RyszCraft2\\RyszCraft' as the world directory
overviewer.py:276  5264 2017-08-02 18:52:59 DEBUG    Using 'c:\\mcmap' as the output directory
overviewer.py:342  5264 2017-08-02 18:52:59 INFO     Welcome to Minecraft Overviewer!
overviewer.py:343  5264 2017-08-02 18:52:59 DEBUG    Current log level: 10
files.py:43        5264 2017-08-02 18:52:59 DEBUG    Detected that chmods work in 'c:\\mcmap'
files.py:56        5264 2017-08-02 18:52:59 DEBUG    Detected that overwriting renames do NOT work in 'c:\\mcmap'
assetmanager.py:57 5264 2017-08-02 18:52:59 DEBUG    Traceback (most recent call last):
  File "overviewer_core\assetmanager.py", line 51, in __init__
IOError: [Errno 2] No such file or directory: 'c:\\mcmap\\overviewerConfig.js'

assetmanager.py:68 5264 2017-08-02 18:52:59 DEBUG    Preferred enoding set to: cp1252
overviewer.py:462  5264 2017-08-02 18:52:59 DEBUG    Found the following render thing: OrderedDict([('manualpois', []), ('minzoom', 0), ('rerenderprob', 0.0), ('showlocationmarker', True), ('imgquality', 95), ('title', 'Overviewer Render (lighting)'), ('markers', []), ('bgcolor', (26, 26, 26, 0)), ('showspawn', True), ('northdirection', 0), ('defaultzoom', 1), ('imgformat', 'png'), ('base', ''), ('world', 'C:\\Minecraft\\RyszCraft2\\RyszCraft'), ('optimizeimg', []), ('poititle', 'Markers'), ('overlay', []), ('rendermode', [<overviewer_core.rendermodes.Base object at 0x0000000004503748>, <overviewer_core.rendermodes.EdgeLines object at 0x0000000004503780>, <overviewer_core.rendermodes.Lighting object at 0x00000000045037B8>]), ('dimension', ('default', 0)), ('worldname_orig', 'world')])
overviewer.py:471  5264 2017-08-02 18:52:59 ERROR    Failed to open world 'C:\\Minecraft\\RyszCraft2\\RyszCraft'
overviewer.py:634  5264 2017-08-02 18:52:59 ERROR    An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 624, in <module>
  File "overviewer.py", line 472, in main
CorruptNBTError: could not parse nbt: 'utf8' codec can't decode byte 0xc0 in position 7: invalid start byte

**Comment by CounterPillow** [comment]
Can you upload your level.dat for me so that I can take a look at it?

**Comment by eminence** [comment]
Closed by #1477
