### ISSUE TITLE
Missing texture for bed

### ISSUE THREAD

**Issue by meiisthicc** [overviewer/Minecraft-Overviewer#1416]
"Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file."

Wondering how to fix this as I am terrible at coding. I have looked it up and apparently you can use 1.11 as the texture path but I have no idea how to do this. Help would be greatly appreciated.

**Comment by tristandaniel** [comment]
Probably introduced after 4b71f15 (at least it did not happen to me with it on Linux). I could try to fix this myself but a quick search with `bed_feet_top` did not return any occurence .. Will investigate further ..

**Comment by meiisthicc** [comment]
what

**Comment by tristandaniel** [comment]
Basically it has been fixed already. Apparently the Windows builds are out of date (although I downloaded the build at https://overviewer.org/builds/win64/6/overviewer-0.12.204.zip, which theorically should be the build corresponding to the latest commit right?).

If you're on Windows and downloaded the provided build, I guess you can close the issue.

**Comment by meiisthicc** [comment]
alrighty let me try

**Comment by meiisthicc** [comment]
Nope, C:\Users\Cats\Documents\Overviewer>overviewer.exe "C:\Users\Cats\Desktop\Minecraft Server 1.12\world" "C:\Users\Cats\Desktop\World Map"
2017-09-23 14:28:13  Welcome to Minecraft Overviewer!
2017-09-23 14:28:13  Generating textures...
2017-09-23 14:28:15 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

**Comment by tristandaniel** [comment]
Okay nevermind, the link given for Windows on the download page was for an outdated build (0.12.137). So I tried replacing the build number in the URL to the latest available Linux build (0.12.204) just in case the download page had not been updated. And it actually worked, the link returned a file ... so I thought there was actually a Windows build 0.12.204. But in fact you can basically type in any build number and you will get a file.

Soooo the Windows build is probably really outdated and the download page does weird stuff with filenames. I'll see if I can build one myself ..

**Comment by tristandaniel** [comment]
Ok I found the latest Windows builds .. http://static.overviewer.org/builds/master/861/

**Comment by meiisthicc** [comment]
awesome thanks it worked
