### ISSUE TITLE
Unable to get player name for UUID

### ISSUE THREAD

**Issue by mgjuhler** [overviewer/Minecraft-Overviewer#1417]
I'm having trouble generating players and other poi's on my survival map. game server is downloaded from the game host and where it is packed with tar and there after packed out on the overview server and handled.

Minecraft Overviewer 0.12.204 (22b9ab3)
built on Thu Aug 24 22:26:03 2017

log: https://pastebin.com/VWEYFAzf
config: https://pastebin.com/D1CH3uKf

**Comment by CounterPillow** [comment]
To me it looks like the problem is with the filesystem on  `/home/minecraft/overviewer/outgoing/web/survival/`. The crash isn't in our code, but within python's standard library itself.

**Comment by mgjuhler** [comment]
okay thanks for your reply. I just updated my server and there was an update to perl. I am currently building a new overview map.

**Comment by mgjuhler** [comment]
forgot all about this, i have no idea if i got it working or not. sorry

**Comment by linomass36** [comment]
3 years later and now I'm having this problem: the crash log is basically the same. I saw your reply about this not being a crash but it rather being sth to do with python itself?

Could you explain how I can render the player names then?

**Comment by CounterPillow** [comment]
@linomass36 open a new issue with your log
