### ISSUE TITLE
Can't use overviewer for Windows.

### ISSUE THREAD

**Issue by Modddder** [overviewer/Minecraft-Overviewer#1419]
I keep getting this error and i saw others did a while back.

2017-10-22 20:32:13  Welcome to Minecraft Overviewer!
2017-10-22 20:32:13  Generating textures...
2017-10-22 20:32:17 E Could not find the textures while searching for 'assets/mi
necraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' opti
on in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>

(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the text
urepath option to use a snapshot jar)

I saw that there is a fix for it, but i can't find it anywhere. Also i used this video https://www.youtube.com/watch?v=j-aD6QLXQ5E (don't know if there is a better way to install overviewer) because the guide that you guys have is too complex for me lol

**Comment by CounterPillow** [comment]
the Windows version you're using is too out of date because our automatic builders are down. You can grab a newer one, 0.12.204, here: http://static.overviewer.org/builds/master/861/overviewer-win64-0.12.204.zip

**Comment by Modddder** [comment]
Thank you so much! This has been bothering me for the past 2 days

**Comment by Modddder** [comment]
Hey, i was wondering (not sure if i should ask this here), but is there a way to switch from which angle im looking at the map?

**Comment by CounterPillow** [comment]
See "northdirection" here http://docs.overviewer.org/en/latest/config/#rendering

**Comment by Modddder** [comment]
Thank you!!
