### ISSUE TITLE
missing API key on chrome

### ISSUE THREAD

**Issue by DaniNyheim** [overviewer/Minecraft-Overviewer#1420]
when I checked in on my maps today, all of them gave me this error:
![image](https://user-images.githubusercontent.com/23560850/32486560-477d033e-c3a7-11e7-871c-73108c4a5570.png)
this only happens on chrome and other browsers built on chromium

**Comment by Electromaster232** [comment]
Duplicate (kinda) of #1308 
Follow the directions mentioned later in the thread for the fix.
