### ISSUE TITLE
Download Link on Webpage is very old...

### ISSUE THREAD

**Issue by Phreag** [overviewer/Minecraft-Overviewer#1424]
https://overviewer.org/downloads

The Windows Downoad Link is very old, maybe it could be updated...

**Comment by AuGolden** [comment]
I've spent hours trying to get the version posted on the download page to work with 1.12.  Texturepaths, config files (Which don't even seem to exist?) and downloading other windows builds.  Nothing.  All because of texture changes to beds :(  Definitely needs an update soon

**Comment by CounterPillow** [comment]
project's dead rip in peace

**Comment by eminence** [comment]
should be fixed now!  🎉

**Comment by Reg-Ed** [comment]
> project's dead rip in peace

So I kinda looked into alternatives and am in the process of migrating away from The Overviewer because of this comment.  Is the project actually dead or not?

**Comment by CounterPillow** [comment]
@Reg-Ed depends entirely on your definition of "dead". Overviewer got most of its contributors early on, and their interests have naturally moved on. Nobody who still uses the overviewer has ever thought of becoming a regular contributor, so now we're in this awkward situation of having a codebase that desperately needs a rewrite with nobody around that actually wants to do it.

We're obviously going to keep the website going and I'll probably still merge pull requests if they're good enough, but if Minecraft changes things around fundamentally prompting the need for a fundamental rework of Overviewer, I don't think it'd happen. Obviously, Overviewer still works right now, so it's not like it'll be gone suddenly.
