### ISSUE TITLE
Google maps directions API showing bus routes even when selecting driving as an option

### ISSUE THREAD

**Issue by trishala1234** [overviewer/Minecraft-Overviewer#1429]
![mapserror](https://user-images.githubusercontent.com/22783725/36062408-21694276-0e92-11e8-88a0-cbd68c27366c.png)

I am making use of google maps directions api to display Bus, Train and Car routes available for a particular destination, by asking the user to enter the origin and destination places in two input boxes.
I have provided three radio buttons with labels as Bus, Train, Driving for the user to choose. 
So when the user chooses Bus , the bus routes for that destination are displayed. 
However when the user next chooses Train or Driving, **the initial bus numbers are still displayed on the google map, although am clearing the initial displayed directions  as below.**

for(var i=0; i<directionsCollection.length; i++){
        	directionsCollection[i].setMap(null);
        }

**Am attaching screenshot of the same.**
The same issue persists even if I choose Train first and then choose Bus next, then the **initially displayed train icons are still visible on the google map.**

I googled a lot to find any solution, but i could not get any.
 request you to help me fix this issue asap.

**Comment by CounterPillow** [comment]
you're at the wrong place, this is a minecraft map rendering software, not the google maps api repository.

**Comment by trishala1234** [comment]
okay sorry.
