### ISSUE TITLE
'overviewer.exe' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by moneyhurricane** [overviewer/Minecraft-Overviewer#1439]
I know you probably get this question a lot, but I've tried multiple times to get a MC Map of one of my world saves, and this keeps coming up. How do I fix this? I am running this on a Windows 10 64-bit computer, MC version is 1.12.2.

Thank you.

**Comment by CounterPillow** [comment]
You haven't used `cd` to change into the right directory where overviewer.exe is.
