### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by TechieAndroid** [overviewer/Minecraft-Overviewer#1442]
This happens in both day and night modes, night is obviously worse looking.

I'm using overviewer-win64-0.12.204.

![Night](https://imgur.com/XUGP8ag.png)

**Comment by CounterPillow** [comment]
duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/1370

**Comment by magneticflux-** [comment]
#1445 fixes this issue, could that get looked at and merged soon? It's annoying to have to load my scheduled Overviewer Docker image with my branch's build rather than the official download.
