### ISSUE TITLE
Crashes on starting overviewer-win64-0.12.210

### ISSUE THREAD

**Issue by TechieAndroid** [overviewer/Minecraft-Overviewer#1443]
I just updated to overviewer-win64-0.12.210. I used my same config files to render, when I went to start it and it immediately crashed. The previous version  (overviewer-win64-0.12.204 I think) works fine, the only thing that has changed is I'm using overviewer-win64-0.12.210. Is there a log somewhere for it I could check and upload?

**Comment by eminence** [comment]
Can you try the latest version on http://overviewer.org/downloads please?

**Comment by TechieAndroid** [comment]
@eminence 
It is working fine now.
