### ISSUE TITLE
CentOS 7 Support? (solved my build issue)

### ISSUE THREAD

**Issue by hinchy34** [overviewer/Minecraft-Overviewer#1444]
Hi, I have been wanting to use this on my server for a while, I gave up last year but I am trying again.

I apologize that I am not a linux person, I just try and follow instructions.

I have done these 2 steps from the repo instructions
wget -O /etc/yum.repos.d/overviewer.repo https://overviewer.org/rpms/overviewer.repo
yum install Minecraft-Overviewer

I guess there is no repo for 7 still? So I have tried to build it myself and I am very lost.

I have the following installed, 
python-imaging or python-pillow
python-imaging-dev or python-pillow-dev
python-dev
python-numpy (that doesn't work, so I justed used numpy)

However when I try to run python2 setup.py build, it says; 

In file included from overviewer_core/src/main.c:18:0:
overviewer_core/src/overviewer.h:39:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
CompileError: command 'gcc' failed with exit status 1

As far as I know python is installed, when I use python, the console pops up with version 2.7.5.
Any suggestions would be very appreciated.

EDIT:
I read that for centos I should install python-devel, not just python-dev. Now I am getting:

Imaging.h: No such file or directory
 #include <Imaging.h>

There seems to be a lot of guess work.

Edit 2:

I got the build to complete! I found a comment suggesting I do:
yum install python-imaging-devel

**Comment by blackknight36** [comment]
I'm having the same issue on CentOS 8.2 and there doesn't appear to be a python-imaging-devel package available in the default repos or EPEL.  Does anybody know how to resolve this?

**Comment by blackknight36** [comment]
I figured it out.  Here's a solution for those of you landing here from Google.  :)  This is similar to the steps required to build on OS X.

Install development packages required:
`dnf install git python3 python3-devel python3-pillow python3-numpy gcc
`
Download Pillow source code and extract it.

`wget -O - https://github.com/python-pillow/Pillow/archive/8.0.1.tar.gz | tar xzvf - 
`
Copy header files into the overviewer directory.
` cp Imaging.h ImagingUtils.h ImPlatform.h /var/repos/Minecraft-Overviewer
`
Once this is done you should be able to build and install the package.

**Comment by CounterPillow** [comment]
No, don't do this.

Instead, just install the right package: `yum install python-pillow-devel`

**Comment by blackknight36** [comment]
> yum install python-pillow-devel

This package doesn't appear to exist on CentOS 8.2.

`[root@mc var]# dnf search python-pillow-devel
Last metadata expiration check: 0:01:55 ago on Sat 21 Nov 2020 06:13:33 PM UTC.
No matches found.`

**Comment by CounterPillow** [comment]
Indeed, looks like CentOS 8 unceremoniously got rid of the pillow headers.

So for anyone looking at this issue for reference, make sure you download the Pillow headers of the Pillow version you have installed on your system.

**Comment by dxg** [comment]
The headers are still there in Centos 8 stream but moved to powertools - you need to enable that first:
https://serverfault.com/questions/997896/how-to-enable-powertools-repository-in-centos-8
and then `dnf install python3-pillow-devel`.
