### ISSUE TITLE
Generating POI markers of signs without rendering map

### ISSUE THREAD

**Issue by shooc** [overviewer/Minecraft-Overviewer#1447]
Hey everyone,

I have a huge Minecraft world in which I am trying to find the location of a specific sign. So far I have rendered none of the world, created a config file, ran genPoi and received this output:

```
2018-05-02 15:42:17  Loaded UUID cache from 'C:\\Users\\User\\Documents\\World\\uuidcache.dat' with 0 entries
2018-05-02 15:42:17  Done handling POIs
2018-05-02 15:42:17  Writing out javascript files
2018-05-02 15:42:17  Wrote UUID cache with 0 entries
2018-05-02 15:42:17  Done
```

I am not sure if it finding zero signs is due to my mistake or the fact that it hasn't rendered any of the world yet. If it is due to the lack of world rendering then is it possible to find the POI signs without rendering any of the images?

**Comment by CounterPillow** [comment]
that's just the uuid cache, which is for player markers. genpoi works independently of the map rendering, so there's no issue.

**Comment by shooc** [comment]
I apologise for not being more specific in my original post but I’m looking for support on the topic rather than leaving an issue. I’m trying to create sign POIs without creating a huge image of the map.

**Comment by CounterPillow** [comment]
Running with `--genpoi` will do that. As I said, the genpoi command is completely separate of the map rendering.

Obviously, you won't have anywhere to display those sign POIs if you haven't rendered a map, but the coordinates are written into the corresponding js file in the output directory.
