### ISSUE TITLE
JSObserver doesn't work with Leaflet

### ISSUE THREAD

**Issue by DutchFlander** [overviewer/Minecraft-Overviewer#1451]
Hi,

With google maps API the JSObserver could write the progress with ETA to the screen during generation on the lower right corner, but with Leaflet, the info is totally missing.

Settings to achieve this, which was working before Leaflet:

```
# Import the Observers
from observer import MultiplexingObserver, ProgressBarObserver, JSObserver

# Construct the ProgressBarObserver
ProgressBarObserver = ProgressBarObserver()

# Construct a basic JSObserver
jsObserver = JSObserver(outputdir, 30)

# Set the observer to a MultiplexingObserver
observer = MultiplexingObserver(ProgressBarObserver, jsObserver)
```
Minecraft Overviewer 0.12.259 (a129274)
built on Wed May  9 14:23:42 2018

Kind regards,
Dutch

**Comment by agrif** [comment]
I've merged the fix from @14mRh4X0r. Give it a shot, and feel free to reopen this issue if you continue to have problems.

**Comment by mtoensing** [comment]
Can we merge this in the 113branch please?

**Comment by agrif** [comment]
I've merged master in to the 113 branch, including this fix. Give it a whirl!

**Comment by mtoensing** [comment]
Hi, thank you. But: 


```
.ov-marker {
    position:relative;
    margin-left:-50%;
    margin-top:-50%;
}
```

This messes up the display of players, player spawn etc on the map. Pls remove this.

**Comment by agrif** [comment]
We haven't experienced that issue before. Do the markers work fine for you on this example?

https://github.com/overviewer/Minecraft-Overviewer/issues/1481#issuecomment-457221496

And can you provide a description or image of how the markers are messed up?

**Comment by mtoensing** [comment]
[broken-markers.mov.zip](https://github.com/overviewer/Minecraft-Overviewer/files/2886357/broken-markers.mov.zip)

in overviewer.css I would ONLY add this and leave the ov-marker thing out:

```
.leaflet-control-container .progress.leaflet-control {
    background: rgba(255, 255, 255, 0.7);
    margin: 0;
    padding: 0 5px;
    color: #333;
}
```

**Comment by mtoensing** [comment]
Ok, I see that this was part of the css all along. But the problem can be reproduced with the new 113branch. Did you try it out after the merge? If I accept all changes and just leave out the overviewer.css it is back to normal...

**Comment by mtoensing** [comment]
This commit is the problem: https://github.com/overviewer/Minecraft-Overviewer/commit/6fbced79bf2c1c895d9932021661e0105ecb333e#diff-77feb9b8e2013927a5f757b1f845dc8d It was added along with your code change. Can you pls test it on your site? Because if I add players and spawnpoints it looks like in the video. And this was added with your commit.

**Comment by agrif** [comment]
ah, it looks like this is a problem for custom markers, not the default markers? Is that correct?

Still a bug, and that helps narrow it down a bit. Do the custom markers ever get the `ov-marker` class applied?

**Comment by mtoensing** [comment]
Sorry, i meant that commit: https://github.com/overviewer/Minecraft-Overviewer/commit/2918637539458fd855e433cbcef88897a626d87f#diff-77feb9b8e2013927a5f757b1f845dc8d

**Comment by 14mRh4X0r** [comment]
You might want to apply the patch from #1510, that fixes the marker positions

**Comment by agrif** [comment]
I was just about to ask: @mtoensing, do you have a way to apply and test #1510? I don't have a set up to test markers right now, but if you have a way to test it and it fixes your issue, then I'll merge right away.

**Comment by mtoensing** [comment]
Yes and no. The problem with the weird movement in my video is gone. But there is a white square behind each icon: 

![image](https://user-images.githubusercontent.com/136737/53186836-187a1800-3602-11e9-835c-0af671ee55d0.png)

And the bubble is not centered which is the initial fix I guess. Since the css does not work anyway why not remove it?  I mean this: 
```
.ov-marker {
    position:relative;
    margin-left:-50%;
    margin-top:-50%;
}
```

And could you please open this issue again since it is not closed yet and does not appear?

**Comment by CounterPillow** [comment]
This is the JS Observer issue. Is this related to the JS observer?

**Comment by mtoensing** [comment]
No. I will add a new issue then.

**Comment by mtoensing** [comment]
I copied a fresh pull from the master branch and the problem is gone.
