### ISSUE TITLE
showspawn False breaks overview completely

### ISSUE THREAD

**Issue by bakkerthehacker** [overviewer/Minecraft-Overviewer#1453]
I was wondering why newer leaflet maps were completely broken and it turns out that my config uses `showspawn` to hide the spawn icon.  

Setting `showspawn` to `False` breaks leaflet, instead of hiding the spawn icon.

**Comment by Chi-Yu** [comment]
I just ran into the same issue. Having it set to `False` causes a JavaScript error in the console `Invalid LatLng object` which causes no map to be shown.

**Comment by DevScyu** [comment]
This is also fixed in #1456

**Comment by Chi-Yu** [comment]
I can't find that in the online documentation. Where am I supposed to add that?

**Comment by DevScyu** [comment]
@Chi-Yu Do you have discord where i can help you? `Scyu_#0854`

**Comment by 14mRh4X0r** [comment]
Just ran into this myself, the cause seems to be a combination of [tilesets.py](/overviewer_core/tilesets.py#L592) and [util.js](/overviewer_core/data/js_src/util.js#L342)

**Comment by agrif** [comment]
I've merged in @14mRh4X0r's fix. If you continue to have problems, please reopen the issue!
