### ISSUE TITLE
issue with overviewer

### ISSUE THREAD

**Issue by MariusDarkblade** [overviewer/Minecraft-Overviewer#1462]
ok so overviewer 0.12.137 is no longer working for me and the newest version every time i try to download it is seems im missing files. the first one was working for a while and then it stopped saying i was missing grass textures. now its not doing anything. i type in CD D:\overviewer-0.12.137 and all i get C://Users/_____/. it does nothing anymore. i dont understand any of this .py stuff all i knew how to do was open up command prompt type in that, then use overviewer.exe "world source" "output source" and then let it run. it was working for a few months and then it stopped. how can i get this working again. i really need this to be working so i can work on my world better. i really need this dumbed down as best i can so i can get this working again.

**Comment by CounterPillow** [comment]
The actual error output, and the Minecraft version you're using, would be helpful.

**Comment by MariusDarkblade** [comment]
i'm not getting any error thats the thing. nothing happens. in command prompt it does absolutely nothing. i type in CD D://overviewer-0.12.137 and when i hit enter it goes right back to C://Users/____/. same thing with the new version of overviewer, i type in CD and then the overviewer source path and again it just goes right back to C://Users/___/. as far as my minecraft version its 1.12.2.

**Comment by MariusDarkblade** [comment]
ok i got that part out but still doesnt seem to be working. after switching directories all i'm getting is the command isnt recognized.
![issue](https://user-images.githubusercontent.com/19295323/41490829-d44b4cca-70c3-11e8-9096-737c6b8f75ec.png)

**Comment by MariusDarkblade** [comment]
also thats the older version of overviewer, the one that i was able to get working at all before it went screwy telling me i was missing textures, which i still dont understand. the new version after downloading doesnt have a .exe file it has a .py file and i dont have the slightest clue how to use that.

**Comment by MariusDarkblade** [comment]
and i just realized i forgot to enter CD before overviewer

**Comment by MariusDarkblade** [comment]
and this is what i got before i learned today that i had to change directories first.
 ![issue2](https://user-images.githubusercontent.com/19295323/41491528-9cd7cfbc-70c7-11e8-99cb-914f748b1996.png)

**Comment by MariusDarkblade** [comment]
thought if i typed in overviewer.py i could get the newer version to work, thought maybe that was the issue, but instead it cant even open it. all i got was this.
![issue3](https://user-images.githubusercontent.com/19295323/41491617-32f7491e-70c8-11e8-9077-212d4992723b.png)

**Comment by MariusDarkblade** [comment]
ok so the very latest release(0.12.267) of overviewer plus what i learned here fixed my issues. everythings back to working again.
