### ISSUE TITLE
The certificate of ‘overviewer.org’ has expired.

### ISSUE THREAD

**Issue by Kattus** [overviewer/Minecraft-Overviewer#1465]
Received this error when I was updating my system today

> Err:10 https://overviewer.org/debian ./ Release
>   server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
> Reading package lists... Done
> E: The repository 'https://overviewer.org/debian ./ Release' does no longer have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

I then tried reinstlaling the cert (following steps on docs) and was informed the cert has expired.

> ~ » wget -O - https://overviewer.org/debian/overviewer.gpg.asc | sudo apt-key add -
> --2018-06-25 12:47:37--  https://overviewer.org/debian/overviewer.gpg.asc
> Resolving overviewer.org (overviewer.org)... 78.46.38.47, 2a01:4f8:110:31e8::2
> Connecting to overviewer.org (overviewer.org)|78.46.38.47|:443... connected.
> ERROR: The certificate of ‘overviewer.org’ is not trusted.
> ERROR: The certificate of ‘overviewer.org’ has expired.
> The certificate has expired
> gpg: no valid OpenPGP data found.

Running Debian GNU/Linux 9.4 (stretch)

**Comment by LeadMagnet** [comment]
Yeah I see the same thing. Just an over site I'm sure.

**Comment by CounterPillow** [comment]
Fixed, turns out someone didn't take the 5 minutes it takes to set up an automatic cert renewal
