### ISSUE TITLE
Ready queue broken in switch to Leaflet

### ISSUE THREAD

**Issue by SamuelEnglard** [overviewer/Minecraft-Overviewer#1466]
In e58d23b1a00d355c330399c3d31af63d77cc62ba the logic to call the Ready Queue for third-party integration was broken. The queue is now never run and `overviewer.isReady` is never set to true.

**Comment by CounterPillow** [comment]
Let me know if the change I just pushed fixes things. I've just plopped the runReadyQueue call at the end of the initialize function, and tested it to be working.
