### ISSUE TITLE
Error loading any version of client or resource pack with 0.12.267 (39d9dba)

### ISSUE THREAD

**Issue by dallmon** [overviewer/Minecraft-Overviewer#1467]
Running Overviewer 0.12.267 on Ubuntu 16.04 causes an error:
2018-07-19 14:26:27 E Sorry, This version of Minecraft-Overviewer only works with versions of Minecraft 1.12 and under
2018-07-19 14:26:27 E This is due to a change in the map chunk format that happened in snapshot 17w47a

I'm running Minecraft Server 1.13, and just decided to upgrade Overviewer to the latest version. It worked on the previous Overviewer version, in both cases with a 1.12 client for the textures.

My command line is:

```/usr/bin/overviewer.py --config=/mnt/Minecraft/ov.cfg```

And ov.cfg contains:

```
worlds["Creative"] = "/mnt/Minecraft/servers/Creative/world"

renders["CreativeDay"] = {
    "world": "Creative",
    "title": "Creative Daytime",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

outputdir = "/mnt/Minecraft/mcmap"
texturepath = "/mnt/Minecraft/jars/client_1.11.jar"
processes = 12
```

I have tried v1.11, v1.12.x and v1.12 client jars as well as v1.12 resource packs, but all give the same error. If I mangle the resource name, I get a file not found error, so I'm sure it is reading the file I have specified. Hardware is a Xeon E5 8-core with 32GB RAM, if that matters.

Thanks,
Dave

**Comment by bobfrankly** [comment]
Related to https://github.com/overviewer/Minecraft-Overviewer/issues/1454 1.13 changed the data format of their map files, which means no Overviewer until that's rewritten, which is not a small task.

**Comment by CounterPillow** [comment]
Closed as duplicate
