### ISSUE TITLE
Markers being checked by default is broken

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1474]
In markers.js, one of the configurable options is, "checked."

Here is my config example:
-----
    {
      "groupName": "Show_Warps039e_4279", 
      "icon": "warps.png", 
      "createInfoWindow": true, 
      "displayName": "Show Warps", 
      "checked": "true"
    }
-----

As you can see, I have "checked" set to true. But when I load my map, the markers are not checked by default.

**Comment by SkylixMC** [comment]
Someone please respond?

**Comment by memiux** [comment]
Not sure but maybe you should try with `"checked": true`, instead of `"checked": "true"`.

**Comment by devindice** [comment]
I dug into this as well, definitely a bug.

I tried forcing all on in the markers.js:
I think this variable is not being properly sent to the leaflet.js script.

I don't know js but I am trying.

There are no references for 'checked' in the overviewer.js

markers.js
var markers={
  "default_world_day": [
    {
      "groupName": "Spawns7b05_1ba8",
      "icon": "signpost_icon.png",
      "createInfoWindow": true,
      "displayName": "Spawns",
      "checked": true
    },
    {
      "groupName": "Players84f4_1ba8",
      "icon": "signpost_icon.png",
      "createInfoWindow": true,
      "displayName": "Players",
      "checked": true
    },
    {
      "groupName": "Homes7b14_1ba8",
      "icon": "signpost_icon.png",
      "createInfoWindow": true,
      "displayName": "Homes",
      "checked": true
    }
  ]
};

**Comment by devindice** [comment]
I found this in leaflet.js:
type="checkbox",i.className="leaflet-control-layers-selector",i.defaultChecked=o)
This is forcing checkboxes to off, I forced them on by changing the 0 to a 1. The checkboxes are checked but they do not actually populate markers on the map as it looks like the code afterwards only will do something if someone physically clicks on them. For example, I have 3 marker groups, I force them all checked with a 1, this then shows them as checked but no markers are actually displayed. When I then deselect a group by physically clicking on them, then the app detects an update and populates the markers for the other groups that were defaulted on.

**Comment by devindice** [comment]
I need to review this further at another time by adding white space to the code and making it easier to be read. This file is also dynamically created by a python script so changes will need to ultimately be made elsewhere. I see 2 areas in the leaflet.js file that this is being defined. One is using a variable to choose whether to enable markers by default and the other after it is hard coded for all markers to be off. I think this worked at one point in time but the hard code was added as a temporary fix.

There is also the issue where it only updates on the 'on-click' event.

**Comment by SkylixMC** [comment]
Alright, well thanks for looking into this. I will regularly be checking back for more info on this issue. Again, thanks a lot!

**Comment by devindice** [comment]
This is above my level, need someone else to dig in. Im very curious though.
