### ISSUE TITLE
How do you use regions.js

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1475]
After a lot of research, I am still clueless on how to go about using regions.js?

Does it even work?
Help!

**Comment by pironic** [comment]
Unfortunately the team is currently working on supporting MC 1.3 chunk version. Regions have all but been abandoned. We have received a few requests lately for them again... maybe we'll put it back on the roadmap. So many other things to tend to first though. Sorry about that.
