### ISSUE TITLE
Links to docs.overviewer.org are broken.

### ISSUE THREAD

**Issue by Charlweed** [overviewer/Minecraft-Overviewer#1476]
Currently, my web browsers are claiming "docs.overviewer.org’s server IP address could not be found."
That's 2018 Sept 5, 10:35 PST.

**Comment by Charlweed** [comment]
Works now, 1.5 hours later.

**Comment by CounterPillow** [comment]
Could've been either a DNS server issue on your side or a DNS server issue on readthedocs' side, `docs.overviewer.org` is just a CNAME to `overviewer.readthedocs.io` so there's not really much we could've done either way other than wait.

That being said, the full documentation is also included in the source of the overviewer, and you can build a local version of it with sphinx as follows:

```
cd Minecraft-Overviewer/docs/
make
```

By default, this will build the HTML version of the documentation, though depending on what tools you have installed and what you want you can also build pdf or epub versions.
