### ISSUE TITLE
minecraft113: some incorrect blocks

### ISSUE THREAD

**Issue by bgulanowski** [overviewer/Minecraft-Overviewer#1486]
I'm seeing:
- stair blocks that should be normal, but look like inside corners
- wheat and other crops that don't show development state, just as seeds
- beet crops (I think) look like blue glazed terracotta
- stripped logs are invisible
- slabs always render in lower half of block (not in screen shot)

Thanks for the great work.

![mc overviewer block errors 1 13](https://user-images.githubusercontent.com/186680/46377169-df96d200-c665-11e8-82b5-b4f4d0f05a8d.png)

**Comment by tyrexdunet** [comment]
Hi, I also have these problems for End Stone Bricks (206)

![786ccf5e57](https://user-images.githubusercontent.com/44790065/48033421-884fba00-e15b-11e8-9643-4b15058f9515.png)

![1d30f80f01](https://user-images.githubusercontent.com/44790065/48033462-a5848880-e15b-11e8-9198-af133967f2a6.png)

When can we expect an update ? :(

**Comment by jvaskonen** [comment]
Addresses the mushroom problems
https://github.com/overviewer/Minecraft-Overviewer/pull/1501

**Comment by jvaskonen** [comment]
Actually for sideways quartz pilliars, the side textures don't match the top textures. I've haven't dug at the part of the code where that problem lives.

**Comment by mtoensing** [comment]
Can't we close this since the merge of 13.2 into master branch? All blocks seem to work now.

**Comment by jsmienk** [comment]
@mtoensing I still have the above issues and I cloned and built Overviewer from GitHub yesterday. When was this fix merged?

**Comment by mtoensing** [comment]
with the master branch or the old 113 branch?

**Comment by bgulanowski** [comment]
Always good to remember to include a "fixes <hash>" in commit messages ;0)

The commit message for 53fa463 doesn't specify which specific issues it addresses. Does it address problems described here?

I'm verifying master now.

**Comment by bgulanowski** [comment]
I just tested with the latest master. My issues do not seem to be fixed. I made edits, ran save-all from the server, and ran overviewer. The new changes appear (I put some torches on the ground), but the problem stairs (used as a roof) are still a problem, as originally reported.

It would be great if there were a way to easily force re-render of just a particular set of coordinates.  I don't think it's necessary for the sake of testing, but it would make updating my map for to fix old render errors dramatically easier.

**Comment by bgulanowski** [comment]
Sorry, at least one problem was resolved: stripped logs render correctly now.

**Comment by bgulanowski** [comment]
Comparison of Minecraft vs overviewer:

![In-game](https://user-images.githubusercontent.com/186680/54072604-eea03280-424a-11e9-987d-e0c87a67f653.png)

![Render](https://user-images.githubusercontent.com/186680/54072603-eea03280-424a-11e9-85e4-ef0c3e1f59f6.png)

**Comment by mtoensing** [comment]
Ok, you are right. The Terracotta Blocks work now but the steps are not rotated correctly. I did not notice this until now. Sorry. Example: https://mc.marc.tv/iso/#/-10/64/-546/max/pudel%20-%20overworld/Day look at the arches.

**Comment by jsmienk** [comment]
Not just the walls. Also mossy cobblestone blocks are rendered as smaller black cubes.

**Comment by Chi-Yu** [comment]
petrified_oak_slab isn't rendering at all. I didn't even know those existed, but it seems they are the 1.13 replacement for the original beta wood slabs that where actually stone slabs but with a wood texture which can still be found in old beta worlds like ours.

**Comment by CounterPillow** [comment]
Man, Overviewer's hacky 1.13 support makes adding support for new blocks horrible. But at least petrified_oak_slab should be fixed now.

**Comment by CounterPillow** [comment]
There, mossy cobblestone blocks and walls should now render correctly again too.

**Comment by CounterPillow** [comment]
End stone bricks seem to render correctly. Can somebody make a list of things that still doesn't render properly with latest master, including their ID?

**Comment by mtoensing** [comment]
Hi, I don't know how to receive the id but stone and wood steps on ceilings are not rendered correctly. If you put a a step on the ceiling it is still in normal position. See screenshots here: https://github.com/overviewer/Minecraft-Overviewer/issues/1486#issuecomment-471204857

**Comment by temdur** [comment]
Receiving the ID:
F3 + H = shows advanced tooltips with the technical name.

WorldEdit has an info tool. Which can print information of a selected block into the chat log.

The following is only blocks I spotted in a world. 

Some slabs and double slaps have a wooden render:
```
Stone Brick Slab (minecraft:stone_brick_slab[type=double,waterlogged=false])
Stone Slab (minecraft:stone_slab[type=double,waterlogged=false])
Stone Slab (minecraft:stone_slab[type=bottom,waterlogged=false])
```

Stairs, all sides facing a wrong direction:
 ```
Stone Brick Stairs
(minecraft:stone_brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false])
Cobblestone Stairs (minecraft:cobblestone_stairs[facing=east,half=bottom,shape=straight,waterlogged=false])
Brick Stairs (minecraft:brick_stairs[facing=west,half=bottom,shape=straight,waterlogged=false])
Dark Oak Stairs (minecraft:dark_oak_stairs[facing=east,half=bottom,shape=straight,waterlogged=false])
Spruce Stairs (minecraft:spruce_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]
```

Will not be rendered at all (new bug?):
`End Rod (minecraft:end_rod[facing=up])`

Will not be rendered, when behind a stone wall? (new bug?):
`Redstone Lamp (minecraft:redstone_lamp[lit=true])`



Version: 0.13.41 / 99eebd5

**Comment by mtoensing** [comment]
stone_brick_stairs facing east 
stone_brick_stairs facing west

![2019-03-17_12 11 30](https://user-images.githubusercontent.com/136737/54489570-e761d000-48ad-11e9-9e71-eafddefa4de1.png)
![2019-03-17_12 11 39](https://user-images.githubusercontent.com/136737/54489571-e761d000-48ad-11e9-8b12-f53030937dd0.png)

Like this?

**Comment by temdur** [comment]
https://minecraft.gamepedia.com/Debug_screen#More_debug-keys

Press the keys F3+H at the same time. The debug menu will not open.

In the chat should appear a yellow text with:
[Debug]: Advanced tooltips: shown

Now hover over an item.

But you got the names already.

**Comment by mtoensing** [comment]
![2019-03-17_13 23 53](https://user-images.githubusercontent.com/136737/54490985-0c107480-48bb-11e9-967c-6665ca0b1c25.png)
<img width="403" alt="Screen Shot 2019-03-17 at 13 45 21" src="https://user-images.githubusercontent.com/136737/54490989-1599dc80-48bb-11e9-96bf-77ba0f670729.png">

**Comment by bold-gman** [comment]
Just a thought: Maybe we should update the Exmaple map (http://overviewer.org/example/) with all old an new blocks or create a whole new one instead of guessing what works and what does not?

**Comment by xcjs** [comment]
Stone brick slabs half slabs when stacked on top of each other and offset from normal blocks render as wood. In the image below, all the parts of the bridge except for the fence should be stone bricks.

Stone brick and wooden steps are also rendering in incorrect orientations. I believe that has already been noted, but I wanted to mention it again as the screenshot in question displays that problem.

![image](https://user-images.githubusercontent.com/5085205/54502075-31bf6d00-48ff-11e9-8133-b628f5b4cad0.png)

**Comment by mtoensing** [comment]
Is there anything we can do to help?

**Comment by xcjs** [comment]
@mtoensing Are you asking the bug reporters or the repository owners?

**Comment by mtoensing** [comment]
The repository owners. @CounterPillow

**Comment by kforney** [comment]
Any blocks of type minecraft:dark_prismarine_stairs or minecraft:dark_prismarine_slab do not render at all.

Example from Overviewer:

![mc_overviewer_notex](https://user-images.githubusercontent.com/5742001/54743892-17012880-4b8b-11e9-97ba-6bbc7cad4c20.png)

Example from in-game:

![Screenshot from 2019-03-21 03-36-38](https://user-images.githubusercontent.com/5742001/54743906-22545400-4b8b-11e9-9f80-0d62743cbba9.png)

**Comment by CounterPillow** [comment]
Fixed double stone brick slabs but the underlying issue is still there: the 1.13 block translation code sucks. I'll look into rewriting it when I've got more time/motivation and the Python 3 branch is merged.

**Comment by mtoensing** [comment]
@CounterPillow
It would be really great if you could make an example dockerfile to get startet with python3 ;)

**Comment by CounterPillow** [comment]
no

**Comment by mtoensing** [comment]
Thanks for the stairs fix. It works now. The shading is not right, though: 

![IMG_1757](https://user-images.githubusercontent.com/136737/55294134-833b2200-53fe-11e9-8c9a-33e106b462cb.png)

**Comment by IncredibleHolg** [comment]
@CounterPillow 
I noticed the prismarine slabs are still missing, adding them will require to associate a blockid. How did you figure out  the blockids for the prismarine stairs you added? Since they are 1.13 they have no real blockid any more.

**Comment by CounterPillow** [comment]
>How did you figure out the blockids for the prismarine stairs you added?

just pick one that's not allocated yet

**Comment by IncredibleHolg** [comment]
Created merge request #1550 for
* prismarine_brick_stairs
* prismarine_slab
* dark_prismarine_slab
* prismarine_brick_slab

**Comment by IncredibleHolg** [comment]
I am in the process of fixing the slabs upper/lower issue. 
![slabbing02](https://user-images.githubusercontent.com/41533138/55679931-99237800-5913-11e9-9b6c-4bac9be51fa7.png)
![slabbing01](https://user-images.githubusercontent.com/41533138/55679934-9c1e6880-5913-11e9-8ded-5819ce167266.png)

**Comment by IncredibleHolg** [comment]
Fixing the double slab ussue

![slabbing04](https://user-images.githubusercontent.com/41533138/55686451-a9624400-5961-11e9-8f84-944ea6aeba86.png)
![slabbing03](https://user-images.githubusercontent.com/41533138/55686455-ae26f800-5961-11e9-9267-64f1bdb3a583.png)

**Comment by CounterPillow** [comment]
I'm going to close this now since as far as I can tell, all problem blocks have been resolved. If you find further missing/broken blocks, please open a separate issue for that specific block.
