### ISSUE TITLE
Unable to use Overviewer with 1.13.2 maps

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1489]
Hi, 

there is no hint in the docs on how to proceed from here. I use Windows 10. Is there a binary for Windows with 1.13.1 support somewhere?

**Comment by shotah** [comment]
Try branch 113 that is what I've been using. https://github.com/overviewer/Minecraft-Overviewer/tree/minecraft113

**Comment by mtoensing** [comment]
Hi, is there a pre-compiled Version for windows ?

**Comment by shotah** [comment]
It's python and a bash script, there is no compiling it. You should probably spend some time reviewing the repo. Also here is an example dockerfile if you need further help. https://github.com/mide/minecraft-overviewer/blob/master/Dockerfile

**Comment by mtoensing** [comment]
ok. I am using a mac and used a vm until now. Is there a documentation how to run the 113 branch? I know what docker is but how do I run this what do I need to install?

**Comment by mtoensing** [comment]
python setup.py build
fails with 

`overviewer_core/src/overviewer.h:41:10: fatal error: 'Imaging.h' file not found`

on Mojave with Python 3.

**Comment by mtoensing** [comment]
Ok, i tried this with PIP but it just fails: http://docs.overviewer.org/en/latest/building/#osx

```
In file included from _imagingtk.c:19:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found
#       include <X11/Xlib.h>
                ^~~~~~~~~~~~
1 error generated.
error: command 'cc' failed with exit status 1
```

Can't someone upload pre-compiled binaries for macos mojave for 1.13.1?

**Comment by CounterPillow** [comment]
>It's python and a bash script, there is no compiling it.

overviewer has a C extension.

Build instructions for OS X are here: http://docs.overviewer.org/en/latest/building/#osx
