### ISSUE TITLE
How start with a zoomed in map?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1490]
Thanks to your help I am now able to use Overviewer on the 1.13 branch and 1.13 maps with docker: https://github.com/mtoensing/Docker-Overviewer-1.13.1

But I am not able to use the defaultzoom variable to start with a zoomed in map. I tried negative values and positive values  and changed min and max zoom. 

No change or a black screen. This is my map: https://mc.marc.tv/iso/ 

Any idea?

**Comment by mtoensing** [comment]
It is a duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/1479

**Comment by mtoensing** [comment]
I don’t get the question.

**Comment by NPCtom** [comment]
How did you start on a specific zoom level if you are using this on a website? My map is on https://minez.wiki and I want the user to automatically be zoomed in a little more than what it it now.

**Comment by mtoensing** [comment]
I hacked the 1.13. branch with this changes: https://github.com/overviewer/Minecraft-Overviewer/issues/1479

**Comment by mtoensing** [comment]
113 was merged into master and this was fixed. Thank you
