### ISSUE TITLE
Minecraft Version 1.13.2 - Is the 113 branch still working?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1491]
Hi, 

the new version 1.13.2 of MC is out now. Are we prepared and does this still work with https://github.com/overviewer/Minecraft-Overviewer/tree/minecraft113 ?

cheers
-Marc

**Comment by bmulley** [comment]
I have it running on my 1.13.2 server. It's not fast, but it's working.

**Comment by dgcurtis** [comment]
I've been getting a black screen only after rendering so I had just assumed it was still be worked on.

**Comment by mtoensing** [comment]
it works for me with my Docker Image: 
https://hub.docker.com/r/marctv/overviewer113/

Tutorial (German) for setting this up on a Synology NAS with 1.13.2 maps:
https://marc.tv/wie-generiere-ich-isometrische-karten-fuer-minecraft-mit-docker-und-synology/
