### ISSUE TITLE
createInfoWindow not working

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1494]
The following is a copy of my markers.js file.
`  "MS-SE": [
    {
      "groupName": "Show_Warpsd23f_aa80", 
      "icon": "signpost_icon.png", 
      "createInfoWindow": false, 
      "displayName": "Show Warps", 
      "checked": "true"
    }, `

As you can see, I am createInfoWindow set to false. However, when I click on the POI, it still opens a info window.

**Comment by CounterPillow** [comment]
I've just pushed a fix to the master branch for this.
