### ISSUE TITLE
instant segfault

### ISSUE THREAD

**Issue by Gartral** [overviewer/Minecraft-Overviewer#1498]
welp, like I said, instant segfault when I start overviewer 
I'm running Overviewer 0.12.278 on Ubuntu 18.04
```
 overviewer.py /var/lib/pufferd/servers/6d572630-e8de-4a7e-a490-5ab11db2da10/world /home/me/mcmap/
2018-11-14 04:32:40  Welcome to Minecraft Overviewer!
2018-11-14 04:32:41  Generating textures...
Segmentation fault
```
no further output, no red highlight error, just a segfault

**Comment by CounterPillow** [comment]
That's because our pre-built package is broken on Ubuntu 18.04 due to an ABI mismatch in Pillow. Try building Overviewer from source. If that doesn't help, please provide a full backtrace obtained with gdb.

**Comment by Gartral** [comment]
*thud* what a pain, ok, guess I'll set up a dev environment then... thanks.

**Comment by Gartral** [comment]
yep, that did the trick! thank you!
