### ISSUE TITLE
Docker - How to specify a user and group for the container to run as?

### ISSUE THREAD

**Issue by JTT-JustTheTip** [overviewer/Minecraft-Overviewer#1500]
How do you specify the UID and GID for the container to run as? As when i map my render directory to somewhere outside the container it doesnt have permission to write.

As a side note, the ports that the container runs on are 80 and 443, right?

Thanks

**Comment by CounterPillow** [comment]
I don't know why you're asking here considering we don't have an official docket container and don't know what docker container you're even talking about.

**Comment by JTT-JustTheTip** [comment]
Ahahaha I made a big mistake here, I posted the issue on the wrong GitHub repo, my bad sorry about that ahahaha meant to post it mide/minecraft-overviewer
