### ISSUE TITLE
Can't use render (may be caused by 1.4 map?)

### ISSUE THREAD

**Issue by cajlo** [overviewer/Minecraft-Overviewer#1505]
Hello,
I'm playing Minecraft 18w50a. Died on map - can't find a house. Classic.
So, try to use overviewer 0.12.296.
Firstly, it don't want to use resoursepack. I have a line "texturepath = "D:/Games/Minecraft/overviewer-0.12.296/worlds/texture/8bitCraft""(tryed with zip, jar, folder), but it just dont see it. So, okay. Installed MC 1.13 and now it is trying to render. But there immideately is a mistake. See the screen please (there also config file).
![image](https://user-images.githubusercontent.com/11216254/50731143-7ba50d80-116e-11e9-89de-d7da8d35fa19.png)

**Comment by matrixhacker** [comment]
The current version of overviewer at this time does not support MC 1.13.x or any following snapshots.
