### ISSUE TITLE
Fedora 29 Repo Request

### ISSUE THREAD

**Issue by strmtrupr2** [overviewer/Minecraft-Overviewer#1508]
Hi, I would like a rpm for Fedora 29 please.
Thank you for all your help with this, it looks really cool!
Scott

**Comment by enaut** [comment]
There is a copr repository maintained by me with 1.13 support:
https://copr.fedorainfracloud.org/coprs/enaut/minecraft-overviewer-weekly/

install with: 
# dnf copr enable enaut/minecraft-overviewer-weekly
# dnf install minecraft-overviewer

there is also the official repos (though this is afaik not with 1.13 support):
http://docs.overviewer.org/en/latest/installing/#centos-rhel-fedora

**Comment by strmtrupr2** [comment]
thanks!

**Comment by enaut** [comment]
I think you can close this issue as I can't because I'm not a team member.
