### ISSUE TITLE
How to remove fragments from old rendition?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1511]
<img width="1198" alt="screen shot 2019-02-02 at 13 05 03" src="https://user-images.githubusercontent.com/136737/52164029-4fd46380-26eb-11e9-8513-672038a5f7c9.png">

I rendered a bigger version of the map and then reduced the renderes are again with a smaller crop setting. I upload the map to the webserver with _rsync -azPh --delete_ Is there anything I can do to get rid of the fragments except to do a force-render. That would take hours...

**Comment by mtoensing** [comment]
@CounterPillow Any idea? Do I have to do a forced render?

**Comment by enaut** [comment]
Do it and be done ;)! you can also manually delete the tiles that are wrong - but this is awful work so just do the forcererender.
