### ISSUE TITLE
[Question] How to change content of progress.json with JSObserver? 

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1515]
Hi, 

I put this in my config.py: 

```
# Import the Observers
from observer import MultiplexingObserver, ProgressBarObserver, JSObserver

# Construct the ProgressBarObserver
ProgressBarObserver = ProgressBarObserver()

# Construct a basic JSObserver
jsObserver = JSObserver(outputdir, 30)

# Set the observer to a MultiplexingObserver
observer = MultiplexingObserver(ProgressBarObserver, jsObserver)
```

and I get this in my progress.json: 
{"messageTime": 1550586363.074757, "message": "Rendered 0 of 1534 tiles (0% ETA:?)", "update": 2325879546111.0}

How can I change this? I just want to get the percentage and ETA in different variables. I do not really understand the documentation in that point.

**Comment by tswsl1989** [comment]
It's not really possible to change what is written to progress.json unless you're willing to edit the main overviewer python scripts - specifically [observer.py](https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/observer.py) (probably with a corresponding change in [util.js](https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/data/js_src/util.js) to stop any changes causing issues when viewing the map in a browser).

If you're looking to use the information in your own javascript then the alternative is to parse the message field for the information you require.

There is some support for changing the message text, which was aimed at allowing translations. That still won't allow you to split ETA and percentage into their own variables, but would let you change the text format to be more easily parseable.

**Comment by mtoensing** [comment]
Ok, thanks .
