### ISSUE TITLE
Overviewer not using texture pack

### ISSUE THREAD

**Issue by Bobcat00** [overviewer/Minecraft-Overviewer#1521]
Just upgraded to Overviewer 0.13.2 and the render is using the default textures instead of my texture pack. There is no error message in the console, and I made no changes to the texture pack or path when upgrading.  This is with 1.12.2 and I'm using a 1.12.2 texture pack.

Old (correct) is on the bottom/left, new (wrong) is on the top/right:

![overviewer2](https://user-images.githubusercontent.com/3617206/53287770-09ed4700-374f-11e9-9953-fa3c24833fb3.png)

**Comment by CounterPillow** [comment]
Overviewer will fall back to a system installed client jar if the texturepath specified texture pack is missing some texture. We don't keep compatibility for older texture packs/client Jars as this would be too much work.
