### ISSUE TITLE
Player Names with Two Preceding Underscores vs. Special POIs

### ISSUE THREAD

**Issue by asbest0s** [overviewer/Minecraft-Overviewer#1523]
I'm using the following filter functions in the config file:

```
def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "https://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']
		
def playerSpawn(poi):
	if poi['id'] == 'PlayerSpawn':
		poi['icon'] = "bed.png"
		return "%s" % (poi['EntityId'])
```
A player has a name with two preceding and trailing underscores. For this player the playerIcons filter's avatar icon would be in the correct location but the image is missing from the final map with a typical missing image placeholder; the name is correct in the rollover text. The playerSpawn filter draws the bed icon in the correct location and the rollover text is "None".

**Comment by CounterPillow** [comment]
Looks like underscores break the avatar endpoint, that's something we need to fix in Overviewer-Web. Thanks for reporting it.

**Comment by CounterPillow** [comment]
Submitted a fix in https://github.com/overviewer/Overviewer-Web/pull/17, this should be fixed once it's merged and deployed.
