### ISSUE TITLE
"overlay" key in render dictionary ignored

### ISSUE THREAD

**Issue by demosjarco** [overviewer/Minecraft-Overviewer#1553]
so in overviewer v0.13.73 (win64) "overlay" key on a render is being ignored and shows up on every render even of different worlds.
![screenshot](https://user-images.githubusercontent.com/1209494/56378108-d9f77880-61c0-11e9-915e-1206d6ccc7c9.png)
[config.py](https://gist.github.com/demosjarco/1c210b4077ad7ad7227a16f23e4d6f86)
[live copy](https://www.demosjarco.dev/mcmaps/)

**Comment by CounterPillow** [comment]
This was the fault of @aheadley
