### ISSUE TITLE
Markers that point to external urls are loaded over http not https

### ISSUE THREAD

**Issue by demosjarco** [overviewer/Minecraft-Overviewer#1554]
In the `config.py`
![image](https://user-images.githubusercontent.com/1209494/56450340-3c906780-62da-11e9-9bb2-fd0e30c3799e.png)
and even in the `markersDB.js` after `--genpoi`, the urls are with https
![image](https://user-images.githubusercontent.com/1209494/56450287-bc6a0200-62d9-11e9-87b1-1c053a6a61f7.png)
however when the page loads in the browser, they are loaded with http
![image](https://user-images.githubusercontent.com/1209494/56450305-ede2cd80-62d9-11e9-84e9-15fee1698180.png).

**Comment by CounterPillow** [comment]
Found the issue, it's in Overviewer-Web actually, not in Overviewer itself. Flask redirects to a trailing slash URL with plain-text HTTP.

Fixed in https://github.com/overviewer/Overviewer-Web/pull/33.
