### ISSUE TITLE
[1.14] Dark strips in the corner of maps

### ISSUE THREAD

**Issue by n4ru** [overviewer/Minecraft-Overviewer#1558]
See: https://i.imgur.com/VzGSX88.png

Generated using the latest release (0.13.76).

**Comment by CounterPillow** [comment]
Minecraft bug, nothing we can really do about that.

**Comment by CounterPillow** [comment]
Actually we might be able to assume everything without light data is fully lit instead of fully dark, but that may introduce other glitches especially with the cave render.

**Comment by n4ru** [comment]
Could we do something like check distance to next block above the area without light data, and assume if it's over some amount that it's on the surface?

**Comment by CounterPillow** [comment]
would be incredibly slow
