### ISSUE TITLE
Spawn Icon not showing up on Chrome-based browsers

### ISSUE THREAD

**Issue by SpazmasterYT** [overviewer/Minecraft-Overviewer#1559]
Not sure if this is a specifically-chrome issue, but on google chrome and other chrome based browsers (slimjet browser in my case) the icon for spawn does not show up. If I hover my mouse over the general estimated area where the default spawn is, my mouse changes from the 🤚 to the 👆 cursor indicating a clickable item and a textbox shows up saying "Spawn", which means the spawn icon is still there, its just invisible. This is not an issue in Microsoft Edge, the spawn Icon still shows up on that browser.
![image](https://user-images.githubusercontent.com/44085597/56767329-13a42280-6771-11e9-941d-2e32929a6672.png)
![image](https://user-images.githubusercontent.com/44085597/56767502-88775c80-6771-11e9-8dc4-624b828083f0.png)

I do not use a configuration file for rendering, i just use the default rendering settings and I run the program using the syntax "overviewer.py sourceFolder destinationFolder"

This is done on a linux server running Ubuntu 18, if it matters.

**Comment by CounterPillow** [comment]
Neither Edge nor Chrome are showing the spawn icon, Edge is showing a broken image url icon.

Are you using Apache as the web server by any chance, and are you serving the map directly on the top level of the domain?

**Comment by SpazmasterYT** [comment]
I actually am using basic apache2 for the webserver. Now that I think of it, when I first rendered it on my home pc to test it out and then opened the index file, it used to show the home icon. On my server after I set up the webpage it started doing that.

What my server does is once a week it renders the files to a temp directory and then clears out my /html/ directory and then copies all data in the temp folder to the now empty html folder. Afterwards, the data remains in the temp folder so overviewer doesnt need to rerender stuff thats unchanged.

**Comment by CounterPillow** [comment]
That's because Apache in its default config has an alias that overrides the /icons/ directory with its own, so your browser is unable to load the Overviewer icons because Apache hijacked the icons URL. You can disable that rule in the Apache configuration.

**Comment by SpazmasterYT** [comment]
That was exactly the solution to my problem, I have the Icons working properly now.
