### ISSUE TITLE
v0.13.84 dropped 1.13 support

### ISSUE THREAD

**Issue by phoenixlzx** [overviewer/Minecraft-Overviewer#1563]
### Issue description

A new installed v0.13.84 of overviewer renders 1.13 worlds to blank. All tile picture files are blank which indicates a server-side issue. 
There is no error reported during render, as the system has both 1.14 and 1.13 client jar's installed. Specify `texturepath` to 1.13/1.13.2 client jar or corresponding version of texture pack does not solve this issue.
Remove 1.14 client jar will result in error however:

```
2019-04-30 08:54:08 E Could not find the textures while searching for 'assets/minecraft/textures/block/smooth_stone_slab_side.png'. Try specifying the 'texturepath' option in your config file.                                                                                                                                                                            
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.14-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)
```

### Reproduce

Generate a world with 1.13/1.13.2 server software, and render it with latest release (0004540).

### Workaround

Currently I downgraded to commit be69712 and it works well with 1.13/1.13.2 maps.

Maybe make separate releases if 1.13 support is to be dropped in future versions I think?

**Comment by CounterPillow** [comment]
Just install the 1.14 assets and you can render 1.13 maps just fine. We're not going to go through hoops supporting multiple Minecraft assets versions concurrently when we're already struggling to support just one.

**Comment by CounterPillow** [comment]
Oh, I see, if the complete render fails then that is indeed an issue, I'll test it.

**Comment by phoenixlzx** [comment]
Thank you for the quick update.

Since 1.13 and 1.14 both have big changes, it's okay to drop support for older versions. But my suggestion is if you won't support multiple version for any reason, please just mark one release as compatible with a specific legacy version so users won't be confused.

Thanks again.

**Comment by CounterPillow** [comment]
Should render fine again with 1.14 textures.
