### ISSUE TITLE
[1.14] Error while open 'World'

### ISSUE THREAD

**Issue by Surax23** [overviewer/Minecraft-Overviewer#1564]
Sorry for my English.
I have an issue while trying to render map for 1.14 version.
Some time ago I had server for 1.13, and two days ago I tried to install overviewer for that version. After installation and configuration overviewer did me a map, but... There was nothing. You could see it here: [](http://95.165.140.161/)
And I saw somewhere, that the last version of overviewer works fine with 1.14. So today I downloaded 1.14 server, started and the tried to render new map in overviewer, but it showed me next error:
`E Render normalrender's world is 'World', but I could not find a corresponding entry in the worlds dictionary.`

Please, tell me, what am I supposed to do?

**Comment by CounterPillow** [comment]
Are you using a configuration file?

**Comment by Surax23** [comment]
Oh, link has been disappeared. Here it is: http://95.165.140.161/

> Are you using a configuration file?

Thank you, CounterPillow. I see that the name of a map in config should be the exact name that minecraft creates, and without editing it must be "My world". I was stupid, and I edited that string.

**Comment by CounterPillow** [comment]
Ok, since it seems to work now I take it I can close this issue. Let me know if you have any other issues.

PS: Your icons aren't being displayed on the map because Apache is hijacking http://95.165.140.161/icons/, you can disable the alias it uses for this in the Apache config.
