### ISSUE TITLE
Show last render time

### ISSUE THREAD

**Issue by Dinip** [overviewer/Minecraft-Overviewer#1565]
Hello,
Is there any way to show on the map render web page when was the last render time? I update the render 2 times per day but it was helpful to the players to see when was the last render. It is useful for me so I can see if everything is alright.
Thanks!

**Comment by domialex** [comment]
Just put that at the end of your .ini.
```
# Import the Observers
from observer import MultiplexingObserver, ProgressBarObserver, JSObserver

# Construct the ProgressBarObserver
ProgressBarObserver = ProgressBarObserver()

# Construct a basic JSObserver
jsObserver = JSObserver(outputdir, 30)

# Set the observer to a MultiplexingObserver
observer = MultiplexingObserver(ProgressBarObserver, jsObserver)

**Comment by domialex** [comment]
messageTime in the progress.json shows the date of the last update.
You can use that value, it's a Unix Timestamp.

**Comment by CounterPillow** [comment]
In fact, JSObserver will show that as far as I know.
