### ISSUE TITLE
Howto downgrade overviewer to pre mc 1.14

### ISSUE THREAD

**Issue by Elvi81** [overviewer/Minecraft-Overviewer#1566]
Yeah i saw there was a fix to make it handle 1.13.2 but it still seems to have issues with 1.13.2 worlds as of version 0.13.86, i tried to do a complete rerender and all i got was just recently visited chunks while the rest of the main world stayed black and yet it took about 4 hours to complete.
Run on Centos 7.
http://digital-legacy.sytes.net/mc/map/

**Comment by CounterPillow** [comment]
The bottom left has a little indicator telling you which region file you're hovering over. Can you find a region file that isn't rendered but should be, and then upload that file to https://overviewer.org/uploader/ so I can take a look at it? Thanks.

**Comment by Elvi81** [comment]
Done r.3.0.mca

**Comment by CounterPillow** [comment]
Thanks, I see what the problem is and will get around to fixing it soon.
