### ISSUE TITLE
Map not rendering [MC 1.12.2]

### ISSUE THREAD

**Issue by tzaeru** [overviewer/Minecraft-Overviewer#1568]
Heya,

After running Overviewer with `overviewer.py /home/tzaeru/Minecraft/PiF\ Craft/Saluland/ .` (Saluland being the name of our current world), nothing seems to render.

I've the generated files available here: https://www.tzaeru.com/p/mc/MosaOverviewer/

In some zoom levels, it complains about missing pngs like missing world-lighting/0/1/1.png and stuff like that.

Running Ubuntu & our server is pretty mod-heavy. Might I need to e.g. somehow accommodate for Biome's O' Plenty or so?

**Comment by tswsl1989** [comment]
The missing tiles just mean that there are no tiles in that area, and are a normal message.
The transparent images being served are a bit more strange. Can you confirm what version of Overviewer you have?

**Comment by tzaeru** [comment]
I tried both with prebuilt and self-built Overviewer, version tag for both is `Minecraft Overviewer 0.13.86 (c77fcc5)`

**Comment by CounterPillow** [comment]
Can you upload one of your .mca files to https://overviewer.org/uploader so that I can take a look at it? Thanks

**Comment by scline** [comment]
I am also noticing this issue, using Pixelmon (uses Minecraft version 1.12.2). I am in the middle of a full re-render due to troubleshooting but will upload one of those files for our site when its completed.

http://pixelmon.darkwindcraft.com

**Comment by scline** [comment]
Uploaded two files using your tool, going to try some older versions to see if I can get things to render :)

`pixelmon.darkwindcraft.html.tar.gz` - post-rendered map (its only 12MB likely due to not having pictures)

`pixelmon.darkwindcraft.mca_single.tar.gz` - single mca file from the map, can upload more or all if that helps. Its about 2GB for all of them though.

**Comment by tzaeru** [comment]
> 
> 
> Can you upload one of your .mca files to https://overviewer.org/uploader so that I can take a look at it? Thanks

Uploaded a random region file to the uploader. Also all of them available zipped up here: https://www.tzaeru.com/p/mc/region.zip

**Comment by CounterPillow** [comment]
Thanks for the samples, let me know if there's still issues left with regards to empty maps.

**Comment by tzaeru** [comment]
> 
> 
> Thanks for the samples, let me know if there's still issues left with regards to empty maps.

Thanks!

Works like a charm now https://www.tzaeru.com/p/mc/MosaOverviewer/

Awesome job with the project, kudos!
