### ISSUE TITLE
[1.14] Lanterns don't render

### ISSUE THREAD

**Issue by beeradmoore** [overviewer/Minecraft-Overviewer#1569]
As title says, lanterns don't render. 
Went to look at adding it myself assuming it'd go in with the torch stuff. But lantern.png has multiple sprites on the single png, not sure how to split that up or how to display it correctly. Light from them still renders fine.

![Screen Shot 2019-05-04 at 10 47 08 am](https://user-images.githubusercontent.com/904737/57171691-061a2700-6e5a-11e9-9875-7ed71450025e.png)

Lanterns are both on the wall and on the grass in this rendering. This was rendered with 0.13.86.

**Comment by Surax23** [comment]
Good day.
Don't know if I have to create new issue. There is not only lanterns problem, but new fences too.
Ingame pic: http://prntscr.com/o3ifto
Map pic: http://prntscr.com/o3igm7

**Comment by IncredibleHolg** [comment]
I have a similar problem wirh #1580 with the texture for stonecutter and grindstone.

**Comment by IncredibleHolg** [comment]
Ok, lets collect the parts we need to resolve  this.
* The lantern model is defined in json, which is implemented similar for the torches.
* The standing an hanging variants have different models
* The textture  is holding the different parts of the lantern in one PNG.

Lantern block  texture:

![lantern](https://user-images.githubusercontent.com/41533138/61170465-b2b70a00-a569-11e9-8b79-67a28e03d17e.png)

Standing lantern model, `lantern.json`

```json
{
    "parent": "block/block",
    "textures": {
        "particle": "block/lantern",
        "all": "block/lantern"
    },
    "elements": [
        {   "from": [ 5, 0, 5 ],
            "to": [ 11, 7, 11 ],
            "faces": {
                "down":  { "uv": [  0, 9,  6, 15 ], "texture": "#all", "cullface": "down" },
                "up":    { "uv": [  0, 9,  6, 15 ], "texture": "#all" },
                "north": { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "south": { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "west":  { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "east":  { "uv": [ 0, 2, 6,  9 ], "texture": "#all" }
            }
        },
        {   "from": [ 6, 7, 6 ],
            "to": [ 10, 9, 10 ],
            "faces": {
                "up":    { "uv": [  1, 10,  5, 14 ], "texture": "#all" },
                "north": { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "south": { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "west":  { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "east":  { "uv": [ 1, 0, 5,  2 ], "texture": "#all" }
            }
        },
        {
            "from": [ 6.5, 9, 8 ],
            "to": [ 9.5, 11, 8 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "north": { "uv": [ 11, 1, 14, 3 ], "texture": "#all" },
                "south": { "uv": [ 11, 1, 14, 3 ], "texture": "#all" }
            }
        },
        {
            "from": [ 8, 9, 6.5 ],
            "to": [ 8, 11, 9.5 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "west": { "uv": [ 11, 10, 14, 12 ], "texture": "#all" },
                "east": { "uv": [ 11, 10, 14, 12 ], "texture": "#all" }
            }
        }
    ]
}
```
Hanging lantern model, `hanging_lantern.json`

```json
{
    "parent": "block/block",
    "textures": {
        "particle": "block/lantern",
        "all": "block/lantern"
    },
    "elements": [
        {   "from": [ 5, 1, 5 ],
            "to": [ 11, 8, 11 ],
            "faces": {
                "down":  { "uv": [  0, 9,  6, 15 ], "texture": "#all"},
                "up":    { "uv": [  0, 9,  6, 15 ], "texture": "#all" },
                "north": { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "south": { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "west":  { "uv": [ 0, 2, 6,  9 ], "texture": "#all" },
                "east":  { "uv": [ 0, 2, 6,  9 ], "texture": "#all" }
            }
        },
        {   "from": [ 6, 8, 6 ],
            "to": [ 10, 10, 10 ],
            "faces": {
                "down":  { "uv": [  1, 10,  5, 14 ], "texture": "#all"},
                "up":    { "uv": [  1, 10,  5, 14 ], "texture": "#all" },
                "north": { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "south": { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "west":  { "uv": [ 1, 0, 5,  2 ], "texture": "#all" },
                "east":  { "uv": [ 1, 0, 5,  2 ], "texture": "#all" }
            }
        },
        {
            "from": [ 6.5, 11, 8 ],
            "to": [ 9.5, 15, 8 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "north": { "uv": [ 11, 1, 14, 5 ], "texture": "#all" },
                "south": { "uv": [ 11, 1, 14, 5 ], "texture": "#all" }
            }
        },
        {
            "from": [ 8, 10, 6.5 ],
            "to": [ 8, 16, 9.5 ],
            "rotation": { "origin": [ 8, 8, 8 ], "axis": "y", "angle": 45},
            "shade": false,
            "faces": {
                "west": { "uv": [ 11, 6, 14, 12 ], "texture": "#all" },
                "east": { "uv": [ 11, 6, 14, 12 ], "texture": "#all" }
            }
        }
    ]
}
```

**Comment by IncredibleHolg** [comment]
The regions within the texture (scaled by 10)
0, 9,  6, 15 

![grafik](https://user-images.githubusercontent.com/41533138/61196093-a26b7000-a6cc-11e9-8e8c-0da707274693.png)

0, 2, 6,  9

![grafik](https://user-images.githubusercontent.com/41533138/61196210-3f2e0d80-a6cd-11e9-8eb9-80aba2673d3d.png)

 1, 10,  5, 14 

![grafik](https://user-images.githubusercontent.com/41533138/61196264-9338f200-a6cd-11e9-8386-9afe212b85f2.png)

1, 0, 5,  2

![grafik](https://user-images.githubusercontent.com/41533138/61196290-cda28f00-a6cd-11e9-92de-57ea8a50e389.png)

11, 1, 14, 3 

![grafik](https://user-images.githubusercontent.com/41533138/61196336-338f1680-a6ce-11e9-8e43-af5b2b1ee0f3.png)

11, 10, 14, 12

![grafik](https://user-images.githubusercontent.com/41533138/61196395-ac8e6e00-a6ce-11e9-90f1-e0f70c034ec4.png)

**Comment by IncredibleHolg** [comment]
Claiming the block ID 11373 for the lantern
```c
block_lantern = 11373,
```

**Comment by IncredibleHolg** [comment]
I implemented a simplified model of the lantern, since it is so tiny.

Before:

![lantern-001](https://user-images.githubusercontent.com/41533138/61997399-5099f100-b0a1-11e9-9a5d-5f2432389d3a.png)

after:

![lantern-002](https://user-images.githubusercontent.com/41533138/61997404-5bed1c80-b0a1-11e9-9674-273a2ea7c882.png)
