### ISSUE TITLE
Black spots on 1.14 world (Unknow region type)

### ISSUE THREAD

**Issue by warbog** [overviewer/Minecraft-Overviewer#1572]
Hi, 
When I'm trying to render my world (version 1.14), I firstly get error messages:
https://imgur.com/a/whZacFM
"Unknown region type"
Then it finally finishes with other errors:
https://imgur.com/a/FaHm1Dt
"It way be corrupt"

Inside my world file : https://imgur.com/a/A1fQvV7
The map rendered (with black spots) : https://imgur.com/a/FIWvj7f

Why is that ? is that because of the version 1.14 ?
Thanks in advance

**Comment by warbog** [comment]
And here is my config file:
worlds["monde"] = "WORLDS/world_omg_old_4"

renders["Florian"] = {
	"world": "monde",
	"title": "Ile de Florian",
	"rendermode": smooth_lighting,
	"dimension": "overworld",
	"crop": (280,-1320,770,-1900),
	"defaultzoom": 3,
}

outputdir = "RENDER_FLORIAN/"

**Comment by CounterPillow** [comment]
The warnings are unrelated to the black spots.

**Comment by warbog** [comment]
I'd like to render my world without black spots, how do I do it ?
(I figured out that in rendermode "normal", I don't have black spot, but I'd like the smooth_lighting one)

**Comment by CounterPillow** [comment]
>I'd like to render my world without black spots, how do I do it ?

It's a bug I'm still investigating, and Mojang's fault.

**Comment by warbog** [comment]
Oh alright then, good luck ! 
Very good work so far !

**Comment by KrusnikViers** [comment]
I have met the very same bug and noticed that the light-spreading objects are actually working inside such areas. Can not it be clouds, stored in the world file - not rendered themselves, but dropping a shadow on the surface below?

e.g: https://imgur.com/a/sbVF7ZH

**Comment by CounterPillow** [comment]
>Can not it be clouds, stored in the world file - not rendered themselves, but dropping a shadow on the surface below?

No, it's because skylight and blocklight are separate pieces of data.

**Comment by tollers** [comment]
Might this be relevant?

```
2019-05-23 19:43:22  Welcome to Minecraft Overviewer!
2019-05-23 19:43:22 W Unkown region type in '[serverpath]/world/poi'
2019-05-23 19:43:22  Generating textures...
2019-05-23 19:43:28 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/local/bin/overviewer.py", line 628, in <module>
    ret = main()
  File "/usr/local/bin/overviewer.py", line 537, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()}) # TODO find a better way to do this
  File "/usr/local/lib/python2.7/dist-packages/overviewer_core/world.py", line 212, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/local/lib/python2.7/dist-packages/overviewer_core/world.py", line 1101, in get_chunk
    skylight = numpy.frombuffer(section['SkyLight'], dtype=numpy.uint8)
KeyError: 'SkyLight'
```

**Comment by CounterPillow** [comment]
@tollers you didn't update Overviewer.

**Comment by Pokihead** [comment]
I have the same bug, only normal rendermode works without these black spots.
Does the XX.90 update fix it? Or are you going to say if it is fixed?
By the way best Mapping Software 👍

**Comment by tollers** [comment]
@CounterPillow I had just updated it. I just now uninstalled and reinstalled and got the same :/.

**Comment by CounterPillow** [comment]
@Pokihead no, it is not yet fixed. I am going to say when it is fixed by closing this issue when I've fixed it.

@tollers you are not using the latest Overviewer, I can tell by the line numbers in your traceback not matching up to the actual source code in git.

**Comment by Pokihead** [comment]
@CounterPillow  ok thanks a lot

**Comment by IncredibleHolg** [comment]
It seems, after loding chunks with 1.14.2 the black spots are  fixed.

**Comment by chungy** [comment]
For anyone with the issue still:

Make sure you have Minecraft 1.14.2 (server or client), then:

If you are playing single-player (or "open to LAN" games), open the world selection screen, select your world, click the Edit button, and then click "Optimize World" and make sure "Erase Cache" is checked, then click one of the two buttons below (backup is safest, but the other is probably safe too).

If you have a multiplayer server, launch the game like so: `java -jar server.jar --forceUpgrade --eraseCache`. If you normally run the server via a service manager (such as [via systemd](https://gist.github.com/chungy/0b2c438c7db90b32701a), you can type `stop` after everything is finished and loaded and continue to run the service as normal.

Minecraft will then scan every chunk in the game and recalculate lighting data. Every chunk will be updated and Overviewer will re-render everything. This takes a long time both on Minecraft's side and on Overviewer's side, but it should only be required once.

**Comment by Pokihead** [comment]
> 
> 
> For anyone with the issue still:
> 
> Make sure you have Minecraft 1.14.2 (server or client), then:
> 
> If you are playing single-player (or "open to LAN" games), open the world selection screen, select your world, click the Edit button, and then click "Optimize World" and make sure "Erase Cache" is checked, then click one of the two buttons below (backup is safest, but the other is probably safe too).
> 
> If you have a multiplayer server, launch the game like so: `java -jar server.jar --forceUpgrade --eraseCache`. If you normally run the server via a service manager (such as [via systemd](https://gist.github.com/chungy/0b2c438c7db90b32701a)), you can type `stop` after everything is finished and loaded and continue to run the service as normal.
> 
> Minecraft will then scan every chunk in the game and recalculate lighting data. Every chunk will be updated and Overviewer will re-render everything. This takes a long time both on Minecraft's side and on Overviewer's side, but it should only be required once.

This does not fix the Black spots for me. They are at the same location as before this, in my case only in desert locations.

**Comment by einarjh** [comment]
@Pokihead A screenshot of your issue would help in determining if you're seeing the same bug as others. Flushing the cache really should do the trick.

**Comment by Pokihead** [comment]
@einarjh Sorry for the late answer. The new overviewer version 0.14.2 nearly fixed it. So there now there are only a few black spots left. Here is a Screenshot of the Spots.
![OverviewerBlackSpot](https://user-images.githubusercontent.com/37344330/60334214-3e8e3b00-999b-11e9-9e0c-c2a93e878d3b.jpg)

**Comment by CounterPillow** [comment]
I have made no changes relating to any of this in those versions so this is probably just your world data changing, not Overviewer doing anything new.

**Comment by Pokihead** [comment]
Oh ok so you mean it could help if i would travel trough this areas in Minecraft and after that it should be gone?

**Comment by CounterPillow** [comment]
Probably, yeah

**Comment by Pokihead** [comment]
ok it worked. So everything is fine again thanks a lot :D
