### ISSUE TITLE
genPOI Ignores "crop"

### ISSUE THREAD

**Issue by jobe1986** [overviewer/Minecraft-Overviewer#1574]
Basically the genPOI script ignores the "crop" setting for worlds and as a result searches through region files it doesn't need to to find entities. As a result it takes longer then it needs to.

For example in my setup I have the world and spawn within a 4096 block radius centered on  X=8192,Z=0, with regions generated in a 4096 block radius centred on X=0,Z=0 too. However I am only rendering the first of those areas, and as such have "crop" set to cover only half of the total area generated. However genPOI still checks all the generated chunks in the unrendered portion and adds markers there too.

**Comment by CounterPillow** [comment]
Fixed, let me know if this fix causes weird results with multiple crop zones and such. Thanks for reporting this!

**Comment by CounterPillow** [comment]
Ok multiple crop zones appear to be completely broken right now anyway, cool.
