### ISSUE TITLE
How to create an overview map on minecraft?

### ISSUE THREAD

**Issue by alex4200** [overviewer/Minecraft-Overviewer#1576]
I am trying to use the overviewer 0.13.87 to create a map of a minecraft 14.1 world. The output says that I am having 89478485 tiles, and the rendering speed is bout 5 tiles per second. 

That means I have to wait 200 days(!!) for the map to be completed. And that is waaaay too long to be useable.

So basic question: How can I create a map from a minecraft world? Am I something missing? Are there some options? What is the problem?

**Comment by CounterPillow** [comment]
If you have previously interrupted a render, the ETA will be wildly off as the console output will tell you.
