### ISSUE TITLE
No such file or directory: 'tmprcobkz'

### ISSUE THREAD

**Issue by MichelArendt** [overviewer/Minecraft-Overviewer#1577]
So this is the first time I'm generating markers out of signs, but the following error appears:
![Screenshot_1](https://user-images.githubusercontent.com/5015666/58302562-32bec000-7dc2-11e9-8487-64b8d4b2b4a7.png)

It seems to be processing the region files OK but the generation of the JS files is not working.

**Comment by CounterPillow** [comment]
What filesystem is the output directory on?

**Comment by MichelArendt** [comment]
I'm sorry for the post, it was a file permission issue on my computer! Realized after you've asked CounterPillow.
