### ISSUE TITLE
1.14.2 KeyError: 'BlockLight'

### ISSUE THREAD

**Issue by TheBloodyScreen** [overviewer/Minecraft-Overviewer#1582]
While trying to run a newly cloned and built instance of Overviewer on a converted 1.14.2 world with a config known to work with 1.13.2 I get his error and I have been unable to find a solution to this. 
![](https://puu.sh/DC1ko/d463e30157.png)

I also get these errors which I don't believe are part of the same problem.
![](https://puu.sh/DC1oI/5affeff825.png)

I'm running on debian 9 stretch.

**Comment by CounterPillow** [comment]
Those line numbers don't line up with Overviewer git master so you're running an outdated version. Line 1263 is currently `data = region.load_chunk(x, z)`, not `blocklight = ...`

**Comment by TheBloodyScreen** [comment]
Turns out I'm just a dumbass running the wrong directory.
Though I am concerned about those poi warnings since they also happen on the current version.
Are those safely ignored?

**Comment by CounterPillow** [comment]
Yes, you can ignore them
