### ISSUE TITLE
Incorrect markers.js generation

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1591]
There is an issue with markers.js specifically with:
 `"createInfoWindow":` and `"checked":`

The issue is that the "true" or "false" parameters after this are generated with quotations marks around them. Because of that if for example "createInfoWindow" is set to false in the generation config, the markers.js file that is generated says:
`"createInfoWindow": "false",`

So the quotations mark around "false" should not exist. Because then they do, the false parameter fails to work.

**Comment by CounterPillow** [comment]
Can't reproduce with the following config:

```python
worlds['world'] = "~/.minecraft/saves/113test"

outputdir = "/tmp/113map"

def signFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

renders["day"] = {
    'title':'Day',
    'world':'world',
    'rendermode':'lighting',
    'forcerender': True,
    'markers':[ dict(name="Signs", createInfoWindow=False, checked=False, icon="signpost.png", filterFunction=signFilter),]
}
```

My guess is you were the one who actually put `createInfoWindow="false"` instead of `createInfoWindow=False`.
