### ISSUE TITLE
Debian repository dead, or merely resting?

### ISSUE THREAD

**Issue by ProfYaffle** [overviewer/Minecraft-Overviewer#1593]
Looks like the repo is offline or empty (because of failed builds?)...

apt-get update fails:

```bash
E: The repository 'http://overviewer.org/debian ./ Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

Re-import key appears to work:

```bash
$ wget -O - https://overviewer.org/debian/overviewer.gpg.asc | sudo apt-key add -
--2019-06-23 14:10:16--  https://overviewer.org/debian/overviewer.gpg.asc
Resolving overviewer.org (overviewer.org)... 78.46.38.47
Connecting to overviewer.org (overviewer.org)|78.46.38.47|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1687 (1.6K) [application/octet-stream]
Saving to: ‘STDOUT’

-                   100%[===================>]   1.65K  --.-KB/s    in 0s      

2019-06-23 14:10:16 (371 MB/s) - written to stdout [1687/1687]

OK
```

Re-installation returns nothing - current version installed (which you'd expect if the apt-get update is failing because there's no new catalog):

```bash
$ sudo apt-get install minecraft-overviewer

Reading package lists... Done
Building dependency tree       
Reading state information... Done
minecraft-overviewer is already the newest version (0.13.90-0~overviewer1).
0 to upgrade, 0 to newly install, 0 to remove and 6 not to upgrade.
```

apt-cache policy agrees for the same reasons:

```bash
$ apt-cache policy minecraft-overviewer

minecraft-overviewer:
  Installed: 0.13.90-0~overviewer1
  Candidate: 0.13.90-0~overviewer1
  Version table:
 *** 0.13.90-0~overviewer1 500
        500 http://overviewer.org/debian ./ Packages
        100 /var/lib/dpkg/status

<snip>
```

Direct trip to https://overviewer.org/downloads suggests build problems:

![image](https://user-images.githubusercontent.com/6093716/59976708-3790b280-95c0-11e9-9217-f010be3f085c.png)

Direct trip to repo at https://overviewer.org/debian suggests either restricted view or not present:

![image](https://user-images.githubusercontent.com/6093716/59976721-568f4480-95c0-11e9-81f3-b3e11c8a6506.png)

**Comment by CounterPillow** [comment]
Yes, we're currently doing some migrations in preparation for Python 3, and hope to have it done soon. You can always build Overviewer yourself from source if you have a pressing need to download it.

Also, FYI, the repo url is `https://overviewer.org/debian/`, the slash at the end matters.
