### ISSUE TITLE
ImportError: No module named observer

### ISSUE THREAD

**Issue by einarjh** [overviewer/Minecraft-Overviewer#1594]
I updated to the new 1.14 deb package tonight (which seems to be a dummy build for some new build system?), and now I can't use the JSObserver progress report, as per http://docs.overviewer.org/en/latest/config/#observers - it results in the following error:

```
$ overviewer.py -p 2 --config=/etc/overviewer_sg.conf
2019-06-24 21:14:26 E Error parsing /etc/overviewer_sg.conf
2019-06-24 21:14:26 E The traceback below will tell you which line triggered the error

2019-06-24 21:14:26 E Partial traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/overviewer_core/configParser.py", line 84, in parse
    rendermodes.__dict__, self._config_state)
  File "/etc/overviewer_sg.conf", line 1, in <module>
    from observer import JSObserver
ImportError: No module named 'observer'
```

Commenting out the lines "from observer import ProgressBarObserver" and "observer = JSObserver(outputdir, 10)" fixes the error. Some python module not being included in the deb package?

**Comment by tswsl1989** [comment]
As of the new .14 release, Overviewer is using Python 3. This means that there's a small syntax change required in config files, [announced here](https://overviewer.org/blog/2019/6/23/overviewer-0-14-is-out-making-the-move-to-python-3/)

Change `from observer import ProgressBarObserver` to `from .observer import ProgressBarObserver` and you should be back in business

**Comment by CounterPillow** [comment]
Oops, forgot to update the observer docs. Will do that real quick.
