### ISSUE TITLE
Whats up with the new colors?

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1599]
![image](https://user-images.githubusercontent.com/34877092/60288772-ec89de80-98e2-11e9-9e77-3219e8467e0e.png)
As seen in the above image, the ocean colors are vastly different. I have rough lines appearing over the ocean transitioning to a different color. Why is that happening :/?

How to I fix that?

**Comment by CounterPillow** [comment]
Those are biome colours and have been applied to water for absolute ages, the reason why they're looking funky is that you probably used some world editing tool that messed them up real bad.
