### ISSUE TITLE
Question/Suggestion (Relating to WOW)

### ISSUE THREAD

**Issue by SkylixMC** [overviewer/Minecraft-Overviewer#1600]
In the WOW overviewer map here https://overviewer.org/wow/#/-2410/64/6763/-9/0/0 (which I know is several years old and still uses google maps), the marker popups have images.

I think its very useful/cool to be able to do that. Is there currently any way to inset an image in to a POI popup? If not, I think it will be a cool feature!

**Comment by edo-2313** [comment]
There is! I assume you refer to manual POIs but you could also do this in automatically generated ones with some modifications.
Where you define your POI, just insert the image using HTML img tag in the name field and the filter will automatically add it to the poi popup
For example, you should have

`'manualpois':[
                   {'id':'Home',
                    'x':-447,
                    'y':87,
                    'z':-45,
                    'name':'Home of X\n<img src="URLTOIMG">'}]`

The only problem with this is that if you hover over a POI it will display the URL inside the img tag but this shouldn't be an issue

**Comment by CounterPillow** [comment]
>The only problem with this is that if you hover over a POI it will display the URL inside the img tag but this shouldn't be an issue

You can also change that behaviour by having your manual POI filter return a tuple, so Overviewer will use one item as a hover text and the other as the popup text.

Also note your manualpois thing is useless without the corresponding filter function.

**Comment by edo-2313** [comment]
How should I setup the filter to return a tuple? I didn't know it was possible to do so...

(Oh and btw, I didn't write the filter function because I think he is already returning poi[name]

**Comment by CounterPillow** [comment]
http://docs.overviewer.org/en/latest/signs/#filter-functions

>It is also possible to return a tuple from the filter function to specify a hovertext different from the text displayed in the info window. The first entry of the tuple will be used as the hover text, the second will be used as the info window content:
>```python
>def chestFilter(poi):
>    if poi['id'] == "Chest" or poi['id'] == 'minecraft:chest':
>        return ("Chest", "Chest with %d items" % len(poi.get('Items', [])))
>```

**Comment by edo-2313** [comment]
Oh thanks, i read that page a million times but completely ignored that line
