### ISSUE TITLE
Overviewer does not work (i.e. EXTREMLY slow)

### ISSUE THREAD

**Issue by alex4200** [overviewer/Minecraft-Overviewer#1601]
I am using the minecraft overviewer (0.13.87) on a mac 10.14.5. I am redering a 1.14.1 java-version minecraft map without using any options. I get a message 

`The unfinished render was a --forcerender. Rerendering any tiles older than 06/25/19 21:02:12.`

That seems fine. I do not see the need to render something that has been rendered already before. Then I see the following text: 

`Rendering 89478485 total tiles.`

So about 90 million tiles (or blocks). I assume that means that 90 millions blocks have changed in 4 days. That is impossible. 

Then the render starts with rendering less than 2 tiles per second. LESS THAN 2 BLOCKS PER SECOND!

How is that possible? What is going on? I have to wait 15000 hours for the render to complete? That is inacceptable! That is not useable! That is 2 years. TWO YEARS!!!

I cannot wait two years for the render to complete. 

Is there a working alternative available for the overviewer? Can it be fixed? I cannot wait two years for the render to finish.

**Comment by edo-2313** [comment]
Mine does that too. I've read that if you resume an unfinished render it greatly overstimates the ETA and tiles to be render, but it will finish before that so it's completely normal. The thing that annoys me is that the tiles number should be the same as the first uncomplete render but even mine goes from ~150k to ~3500k so I think it's a bug in the calculation.

**Comment by CounterPillow** [comment]
>So about 90 million tiles (or blocks). I assume that means that 90 millions blocks have changed in 4 days. That is impossible.

This is wrong, tiles are not blocks

>The unfinished render

Interrupted renders show a bogus ETA as it shows a mathematical worst case scenario, which is not accurate.

**Comment by alex4200** [comment]
So the estimate is off by a factor of about 1000?

**Comment by CounterPillow** [comment]
Do an actual clean render (i.e. stop interrupting the program) and you'll find out!

**Comment by alex4200** [comment]
I will see in about 18 hours. I will tell you

**Comment by alex4200** [comment]
@CounterPillow How long is the estimation to do a first render (in hours/days) for a 2 GB world? Just a normal rendering without any extras. And just a rough estimation.

**Comment by CounterPillow** [comment]
That depends on:

1. how the chunks in the world are laid out
2. how fast your CPU is
3. what rendermode you use
4. how fast your storage medium is
5. how fast your operating system's file system layer is

so I cannot possibly answer this question, especially since I haven't rendered a world of that size in recent times.
