### ISSUE TITLE
Please rebuild your c_overviewer module. It is out of date!

### ISSUE THREAD

**Issue by alex4200** [overviewer/Minecraft-Overviewer#1603]
When starting the overviewer I get an error

`Please rebuild your c_overviewer module. It is out of date!`

How to do that? I did not found any information in the `README.md`.

Version: Commit 7d1a04b0fec9439e1898601b7ebece19bb09ece9

**Comment by alex4200** [comment]
Found the instructions a bit hidden here: http://docs.overviewer.org/en/latest/building/#build-instructions-for-various-operating-systems

**Comment by alex4200** [comment]
I run the command on the mac 

`PIL_INCLUDE_DIR="/path/to/Pillow-[version]/libImaging" python3 setup.py build`

and the build completed successfully, but I still get the same error again.

**Comment by CounterPillow** [comment]
Can't reproduce, builds fine for me.

The likeliest cause is that you have some other c_overviewer module installed in a system path or other path which python searches.

Without the full output of the build command I can't help you further.

**Comment by alex4200** [comment]
Yes, I had some other c_overviewer module installed in my path. Cleaning it up fixed the issue.
