### ISSUE TITLE
"This may be a bug. Please let us know!" =)

### ISSUE THREAD

**Issue by InterArma7** [overviewer/Minecraft-Overviewer#1606]
C:\Users\CDL\AppData\Roaming\.minecraft\Editing Tools\overviewer>overviewer.exe --config= C:/Users/CDL/Desktop/my_configfile
2019-07-08 07:17:00 E You must either specify --config or give me a world directory and output directory.
usage:
overviewer.exe [--rendermodes=...] [options] <World> <Output Dir>
overviewer.exe --config=<config file> [options]

positional arguments:
  world                 Path or name of the world you want to render.
  output                Output directory for the rendered map.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Specify the config file to use.
  -p PROCS, --processes PROCS
                        The number of local worker processes to spawn.
                        Defaults to the number of CPU cores your computer has.
  --pid PID             Specify the pid file to use.
  --rendermodes RENDERMODES
                        If you're not using a config file, specify which
                        rendermodes to render with this option. This is a
                        comma-separated list.
  --forcerender         Force re-render the entire map.
  --check-tiles         Check each tile on disk and re-render old tiles.
  --no-tile-checks      Only render tiles that come from chunks that have
                        changed since the last render (the default).
  --check-terrain       Try to locate the texture files. Useful for debugging
                        texture problems.
  -V, --version         Display version information and then exits.
  --check-version       Fetch information about the latest version of
                        Overviewer.
  --update-web-assets   Update web assets. Will *not* render tiles or update
                        overviewerConfig.js.
  -q, --quiet           Print less output. You can specify this option
                        multiple times.
  -v, --verbose         Print more output. You can specify this option
                        multiple times.
  --simple-output       Use a simple output format, with no colors or progress
                        bars.

Other Scripts:
  These scripts may accept different arguments than the ones listed above.

  --genpoi              Run the genPOI script.
  --skip-scan           When running GenPOI, don't scan for entities.
  --skip-players        When running GenPOI, don't scan player data.

2019-07-08 07:17:01 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 650, in <module>
  File "overviewer.py", line 266, in main
  File "overviewer.py", line 607, in list_worlds
  File "overviewer_core\world.py", line 1713, in get_worlds
  File "overviewer_core\nbt.py", line 31, in wrapper
  File "overviewer_core\nbt.py", line 40, in load
  File "overviewer_core\nbt.py", line 204, in read_all
  File "overviewer_core\nbt.py", line 186, in _read_tag_compound
  File "overviewer_core\nbt.py", line 186, in _read_tag_compound
  File "overviewer_core\nbt.py", line 185, in _read_tag_compound
  File "overviewer_core\nbt.py", line 161, in _read_tag_string
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 482, in read
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by CounterPillow** [comment]
There's a corrupt world somewhere in your saves directory.

**Comment by InterArma7** [comment]
I appreciate your quick reply! Quick follow-up if I may: Would removing all but the world I’m trying to render from the saves folder possibly correct this?

**Comment by CounterPillow** [comment]
Sure, though you'll only run into this if you list the worlds which only happens if you run overviewer without any arguments, which you wouldn't really do anyway if you wanted to render a map.

On second thought I'm going to reopen this so we handle corrupt worlds in the listing a bit more gracefully.

**Comment by CounterPillow** [comment]
There, this might fix it.
