### ISSUE TITLE
Config file not recognized

### ISSUE THREAD

**Issue by InterArma7** [overviewer/Minecraft-Overviewer#1607]
Hello,

I've created a config file in Notepad, but when I direct overviewer towards it, I get the same response no matter the file's location, name or if I use forward / back slashes. Am I missing something?

C:\Users\CDL\AppData\Roaming\.minecraft\Editing Tools\overviewer>overviewer.exe --config=C:\Users\CDL\Desktop\simpleconfigfile
2019-07-08 11:20:45 E The settings file you specified ('C:\\Users\\CDL\\Desktop\\simpleconfigfile') does not exist, or is not a file

C:\Users\CDL\AppData\Roaming\.minecraft\Editing Tools\overviewer>overviewer.exe --config=C:\Users\CDL\Desktop\simpleconfigfile
2019-07-08 11:23:49 E The settings file you specified ('C:\\Users\\CDL\\Desktop\\simpleconfigfile') does not exist, or is not a file

**Comment by tswsl1989** [comment]
Are you sure the file is just called `simpleconfigfile`?

On Windows, file extensions are normally hidden. The default extension for a text file is `.txt`, so the correct command for you might be: 
`overviewer.exe --config=C:\Users\CDL\Desktop\simpleconfigfile.txt`

**Comment by InterArma7** [comment]
Ahh, I hadn't considered that. Once I added the .txt *and* changed my config file's paths to forward slashes it recognized the command. Thank you! : )

**Comment by InterArma7** [comment]
Closed as adding .txt worked
