### ISSUE TITLE
End Smooth Lighting not defined

### ISSUE THREAD

**Issue by InterArma7** [overviewer/Minecraft-Overviewer#1609]
The Overviewer documentation file (Release 0.13, pg. 21) gives an example of how to define end_smooth_lighting, yet the Overviewer considers it a syntax error:

**********The example from pg. 21:
end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]

*********My config file:
worlds["Valandil"] = "C:/Users/CDL/AppData/Roaming/.minecraft/saves/Valandil - 1.14.3 - 20190706"

renders["survivalday"] = {
    "world": "Valandil",
    "title": "The End",
    "rendermode": end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)],
}

outputdir = "C:/Users/CDL/AppData/Roaming/.minecraft/Editing Tools/Overviewer Config Test 20190711a"

*********The error:
C:\Users\CDL\AppData\Roaming\.minecraft\Editing Tools\overviewer-0.14.19>overviewer.exe --config=C:\Users\CDL\Desktop\my_configfile20190711.txt
2019-07-11 07:15:19 E Syntax error parsing C:\Users\CDL\Desktop\my_configfile20190711.txt
2019-07-11 07:15:19 E The traceback below will tell you which line triggered the syntax error

2019-07-11 07:15:19 E Partial traceback:
Traceback (most recent call last):
  File "overviewer_core\configParser.py", line 83, in parse
  File "C:\Users\CDL\Desktop\my_configfile20190711.txt", line 6
    "rendermode": end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)],
                                      ^
*************
Note: The caret ^ aligns just beneath the = sign, if that's of any significance...

Thanks for the help!

**Comment by tswsl1989** [comment]
I believe the definition of the render mode and its use need to go on seperate lines, like so:
```python
worlds["Valandil"] = "C:/Users/CDL/AppData/Roaming/.minecraft/saves/Valandil - 1.14.3 - 20190706"
end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]
renders["survivalday"] = {
"world": "Valandil",
"title": "The End",
"rendermode": end_smooth_lighting
}

outputdir = "C:/Users/CDL/AppData/Roaming/.minecraft/Editing Tools/Overviewer Config Test 20190711a"
```

**Comment by InterArma7** [comment]
Thank you! That was very helpful. Generating now..

**Comment by InterArma7** [comment]
Issue resolved based on tswsl1989's advice (and correcting my lack of dimension specification). Thank you!
