### ISSUE TITLE
Textures turn black when sun isn't visible 

### ISSUE THREAD

**Issue by therealRedrum** [overviewer/Minecraft-Overviewer#1610]
I'm having an issue with Werrus Ultimate shader where if I head into a cave, or into a room with no sun light projecting onto the block I am on, the textures all turn black. I've tried adjusting every possible setting but nothing helps. I'm going into the composite.fsh but nothing seems out of the ordinary... I'm thinking its the suns light mapping? or maybe a shadowing issue, but torches don't help the problem.

Here are some images of the issue: https://imgur.com/a/RoKarx9

**Comment by tswsl1989** [comment]
Looking at the screenshots, your problems appear to be in-game and not an issue with Overviewer.
You will need to file a bug with the creators of Werrus Ultimate instead.
