### ISSUE TITLE
KeyError: 'name' while generating POI

### ISSUE THREAD

**Issue by jedenastka** [overviewer/Minecraft-Overviewer#1615]
Hi. I have recently discovered that Overviewer can generate POI for maps. So I prepared config and ran genpoi - but it threw KeyError: 'name' exception.
Here's the paste with full traceback and the config I used: https://pastebin.com/wZ0w8U8p

**Comment by tswsl1989** [comment]
Different POIs have different attributes available. At least one of the POIs found in your world doesn't have a name attribute. This is why the examples all test the type of the POI before using it.

There's a few different ways to work around this issue. Either catch the exception and handle it with a `try...except` block, or test to see if the `name` key exists before using it, like so:

```python
def placeFilter(poi):
    if 'name' in poi:
        return poi['name']
```
This will ignore any POI that doesn't define a name.

**Comment by jedenastka** [comment]
> Different POIs have different attributes available.
THX, that's what I need.
