### ISSUE TITLE
Windows OV 0.14.57 - ModuleNotFound: No module named 'numpy.random.common'

### ISSUE THREAD

**Issue by Fealeo** [overviewer/Minecraft-Overviewer#1620]
Hello Guys, 

Since upgrading to the 0.14.57 version I do get this error:

> Traceback (most recent call last):
>   File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>   File "site-packages\numpy\__init__.py", line 150, in <module>
>   File "c:\worker\win64\ci_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>   File "site-packages\numpy\random\__init__.py", line 180, in <module>
>   File "mtrand.pyx", line 1, in init numpy.random.mtrand
> ModuleNotFoundError: No module named 'numpy.random.common'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 980, in _find_and_load
> SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set

Any Idea on how to correct this ?

Best regards,

**Comment by CounterPillow** [comment]
Download a newer version, we've fixed this already.

**Comment by ocard** [comment]
> Download a newer version, we've fixed this already.

Mind telling what you did to fix this? I'm actually getting the same error on an app I'm developing. Sorry for the intrusion.

**Comment by CounterPillow** [comment]
@ocard downgrade numpy to 1.16.x until PyInstaller gets its shit together. See https://github.com/overviewer/Minecraft-Overviewer/issues/1618
