### ISSUE TITLE
Broken Link - 404 Error - http://overviewer.org/example/

### ISSUE THREAD

**Issue by sammyrTX** [overviewer/Minecraft-Overviewer#1621]
## Using the link to http://overviewer.org/example/ results in a 404 Error.

(I would be happy to assist if it is just a matter of updating the get request in the app.js file to redirect to the appropriate html. Assuming you are using node, of course)

Thanks!

**Comment by CounterPillow** [comment]
https://github.com/overviewer/Overviewer-Web/issues/36

And thank god we're not 10x enough to use node for anything
