### ISSUE TITLE
Older Version - MC 1.10.2

### ISSUE THREAD

**Issue by Lastknightnik** [overviewer/Minecraft-Overviewer#1625]
hi there,

sorry for the question here but i still use for a server-based project Minecraft 1.10. I just used the overviewer many times but now the old version isn't supported anymore. I just want to get the older overviewer back but i'm not able to find it. Does anyone have the package for me?

thanks a lot,
Lastknightnik

**Comment by huntedhawk** [comment]
https://github.com/overviewer/Minecraft-Overviewer/releases/tag/old-id-format

Try that it's an older release but says it supports older version

**Comment by CounterPillow** [comment]
You can checkout an arbitrarily old commit with git and then build it yourself.
