### ISSUE TITLE
WebP rendering mode seems to have a huge memory leak

### ISSUE THREAD

**Issue by MEDVEDx64** [overviewer/Minecraft-Overviewer#1636]
![изображение](https://user-images.githubusercontent.com/1608808/63421123-b8c5c380-c410-11e9-9097-8af402baf210.png)

When I set `"imgformat": "webp"` in my render config, Overviewer working process runs out of memory dramatically fast, consuming all 4GB available on my server in a few minutes, though png and jpg modes' mem consumption is constantly around ~250MB.

I used the recent git build on Debian 8.5 amd64.
Render config was the following:
`
renders[0] = {
    "world": "doktor",
    "title": "doktor (overworld)",
    "rendermode": smooth_lighting,
    "minzoom": 2,
    "defaultzoom": 2,
    "imgformat": "webp",
    "imglossless": False,
    "imgquality": 70,
    "crop": (-4000, -4000, 4000, 4000)
}
`

**Comment by CounterPillow** [comment]
Pretty sure that's either an issue in Pillow or in libwebp.

>I used the recent git build on Debian 8.5 amd64.

Debian 8 is EOL and has been since 2018, it's entirely possible this is a bug in your packages that has already been fixed by upstream in the past 4 years.
