### ISSUE TITLE
[Support] World coords not correct after render

### ISSUE THREAD

**Issue by LeadMagnet** [overviewer/Minecraft-Overviewer#1638]
Using 0.14.70 to render a 250 by 250 void world.

The Map is centered at zero zero, however the OV render map is way off (179 by -166). The map "ground" level is 100. There is a world border in place 250 by 250.

Map can be viewed here: http://maps.emcs.fun/worlds/staff/index.html#/132/64/-82/-5/staff%20-%20overworld/staff

Run command used: overviewer.exe --forcerender -c STAFF_config.py
Config used:
`worlds["staff"] = "/MCWorlds/STAFFWorld"

renders["staff"] = {
    "world": "staff",
    "title": "Staff World",
    "rendermode": "normal",
    "dimension": "overworld",
	"forcerender": True,
	
}

outputdir = "/inetpub/wwwroot/online/worlds/staff"`

I manually edited the overviewerConfig.js to set the center and spawn to 0,100,0

Any thoughts?

TIA

**Comment by LeadMagnet** [comment]
Well this is a void world, nothing in it but the 250x250 quartz block build platform. A perfectly flat surface.

Mountains and ravines can cause coords to be slightly out, but since there are none that doesn't apply.

The change I made to overviewerConfig.js just seemed to make the problem worse, even though the actual world is centered on zero zero.

**Comment by robosphinx** [comment]
Overviewer displays the map as a collection of 2D images, it has no knowledge of height once the images are rendered. Coordinates displayed are at y=64, which is standard ocean level. You may be able to rebuild Overviewer to treat y=100 as ocean level, or you could move your platform to y=64.

**Comment by LeadMagnet** [comment]
Thanks @robosphinx that sorted it
