### ISSUE TITLE
Signs and Chest POI are not extracted and rendered

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1641]
Hi, 

I tried to render chests and signs on my map but the MarkerDB JS Object is always empty. But there are tons of signs and chests on the map. Spawns and player marker work perfectly.

`def signFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "https://mc.marc.tv/assets/steve.png"
        return "Last known location for %s" % poi['EntityId']

def playerSpawns(poi):
    if poi['id']=='PlayerSpawn':
        poi['icon'] = "https://mc.marc.tv/assets/bed.png"
        return "Spawn for %s" % poi['EntityId']

def chestFilter(poi):
    if poi['id'] == 'Chest':
        poi['icon'] = "https://mc.marc.tv/assets/sign.png"
        return "Chest with %d items" % len(poi['Items'])

thingsToMaker = [
    dict(name="Players", filterFunction=playerIcons),
    dict(name="PlayerSpawn", filterFunction=playerSpawns),
    dict(name="Signs", filterFunction=signFilter),
    dict(name="Chests", filterFunction=chestFilter)

renders["day_complete"] = {
    'world': 'pudel',
    'title': 'Day Complete',
    'forcerender': True,
    'rendermode': 'lighting',
    "dimension": "overworld",
    'markers': thingsToMaker
}
]`

Entrypoint in my docker ist this: 

`ENTRYPOINT ["/bin/bash", "-c","/tmp/overviewer/overviewer.py --config=/tmp/config/config.py --skip-scan --genpoi && /tmp/overviewer/overviewer.py --config=/tmp/config/config.py"]
`

Here is the whole dockerfile: https://github.com/mtoensing/Docker-Minecraft-Overviewer/blob/master/Dockerfile

I wonder what causes this since the spawn and chest thing works perfectly fine.

**Comment by mtoensing** [comment]
removed "--skip-scan". Now the signs work. Chests won't show up.

**Comment by CounterPillow** [comment]
That's because in new Minecraft worlds, the Chest entity ID is no longer "Chest". [The documentation](http://docs.overviewer.org/en/latest/signs/) tells you what entity ID to look for.

**Comment by mtoensing** [comment]
I looked here: https://minecraft.gamepedia.com/Chunk_format It does not seem to be "chest" (lower case). Sorry, maybe someone could be so kind to add the correct id to the documentation please. I am lost here.

**Comment by CounterPillow** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/308818/64069586-be12e180-cc4c-11e9-84ab-7be568aa86ef.png">
