### ISSUE TITLE
Polylines in current Overviewer

### ISSUE THREAD

**Issue by darkspirit510** [overviewer/Minecraft-Overviewer#1643]
Hi @all. I created my config file a few years ago (server version 1.11 or so) with working polylines. I read about the big discussion for 1.13. Yesterday I had some spare time and tried to render a map for my 1.13.2. This worked great, but:

No polylines get drawn on my map. (but also no error). Moreover I can't find polylines in the docs anymore. Did anyone remove them for the 1.13 update?

Here's a snippet from my config:

`ubahn = [
	{
		'id':'bahntunnel',
		'x':10000,
		'y':64,
		'z':10000,
		'polyline':(
			{'x':1317, 'y':64, 'z':52},
			{'x':1317, 'y':64, 'z':-1211},
			{'x':799, 'y':64, 'z':-1211}
		)
	},
	{
		'id':'bahntunnel',
		'x':10000,
		'y':64,
		'z':10000,
		'polyline':(
			{'x':1052, 'y':64, 'z':-988},
			{'x':1052, 'y':64, 'z':-1221},
			{'x':798, 'y':64, 'z':-1221}
		)
	}
	[...]` 

Is this intended beahiour or a bug?

**Comment by CounterPillow** [comment]
Polyline support has not yet been reimplemented since the leaflet rewrite
