### ISSUE TITLE
Minecraft 1.15 Reshape Array Crash

### ISSUE THREAD

**Issue by tjmgit** [overviewer/Minecraft-Overviewer#1650]
**Console Output with -v flag**

overviewer.py:299  7796 2019-09-25 20:57:44 DEBUG    Using 'C:\\Users\\Tyler McCarthy\\AppData\\Roaming\\.minecraft\\saves\\Wamingaloo' as the world directory
overviewer.py:300  7796 2019-09-25 20:57:44 DEBUG    Using 'L:\\mcmap' as the output directory
overviewer.py:368  7796 2019-09-25 20:57:44 INFO     Welcome to Minecraft Overviewer!
overviewer.py:369  7796 2019-09-25 20:57:44 DEBUG    Current log level: 10.
files.py:43        7796 2019-09-25 20:57:44 DEBUG    Detected that chmods work in 'L:\\mcmap'
files.py:56        7796 2019-09-25 20:57:44 DEBUG    Detected that overwriting renames do NOT work in 'L:\\mcmap'
assetmanager.py:60 7796 2019-09-25 20:57:44 DEBUG    Traceback (most recent call last):
  File "overviewer_core\assetmanager.py", line 52, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'L:\\mcmap\\overviewerConfig.js'

overviewer.py:478  7796 2019-09-25 20:57:44 DEBUG    Found the following render thing: OrderedDict([('world', 'C:\\Users\\Tyler McCarthy\\AppData\\Roaming\\.minecraft\\saves\\Wamingaloo'), ('dimension', ('default', 0)), ('title', 'Overviewer Render (lighting)'), ('rendermode', [<overviewer_core.rendermodes.Base object at 0x0000023E7F995BE0>, <overviewer_core.rendermodes.EdgeLines object at 0x0000023E7F995C18>, <overviewer_core.rendermodes.Lighting object at 0x0000023E7F995C50>]), ('northdirection', 0), ('imgformat', 'png'), ('imgquality', 95), ('imglossless', True), ('bgcolor', (26, 26, 26, 0)), ('defaultzoom', 1), ('optimizeimg', []), ('rerenderprob', 0.0), ('markers', []), ('overlay', []), ('showspawn', True), ('base', ''), ('poititle', 'Markers'), ('minzoom', 0), ('manualpois', []), ('showlocationmarker', True), ('worldname_orig', 'world')])
world.py:266       7796 2019-09-25 20:57:44 DEBUG    regiondir is 'C:\\Users\\Tyler McCarthy\\AppData\\Roaming\\.minecraft\\saves\\Wamingaloo\\DIM-1\\region'
world.py:267       7796 2019-09-25 20:57:44 DEBUG    rel is 'DIM-1\\region'
world.py:279       7796 2019-09-25 20:57:44 DEBUG    Scanning regions.  Type is 'DIM-1'
world.py:1483      7796 2019-09-25 20:57:44 DEBUG    regiondir is C:\Users\Tyler McCarthy\AppData\Roaming\.minecraft\saves\Wamingaloo\DIM-1\region, has type 'DIM-1'
world.py:292       7796 2019-09-25 20:57:44 DEBUG    Done scanning regions
world.py:266       7796 2019-09-25 20:57:44 DEBUG    regiondir is 'C:\\Users\\Tyler McCarthy\\AppData\\Roaming\\.minecraft\\saves\\Wamingaloo\\region'
world.py:267       7796 2019-09-25 20:57:44 DEBUG    rel is 'region'
world.py:279       7796 2019-09-25 20:57:44 DEBUG    Scanning regions.  Type is None
world.py:1483      7796 2019-09-25 20:57:44 DEBUG    regiondir is C:\Users\Tyler McCarthy\AppData\Roaming\.minecraft\saves\Wamingaloo\region, has type None
world.py:292       7796 2019-09-25 20:57:44 DEBUG    Done scanning regions
overviewer.py:501  7796 2019-09-25 20:57:44 INFO     Generating textures...
overviewer.py:503  7796 2019-09-25 20:57:54 DEBUG    Finished generating textures.
overviewer.py:509  7796 2019-09-25 20:57:54 DEBUG    Asking for regionset 0.
world.py:1688      7796 2019-09-25 20:57:54 DEBUG    Initializing a cache with key 'C:\Users\Tyler McCarthy\AppData\Roaming\.minecraft\saves\Wamingaloo\region'
world.py:169       7796 2019-09-25 20:57:54 DEBUG    You asked for None, and I found the following candids: [<RegionSet regiondir='C:\\Users\\Tyler McCarthy\\AppData\\Roaming\\.minecraft\\saves\\Wamingaloo\\region'>]
overviewer.py:660  7796 2019-09-25 20:57:54 ERROR    An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 650, in <module>
  File "overviewer.py", line 559, in main
  File "overviewer_core\world.py", line 219, in find_true_spawn
  File "overviewer_core\world.py", line 1352, in get_chunk
ValueError: cannot reshape array of size 1024 into shape (16,16)

**Comment by krynr** [comment]
I ran intothe same problem, but I also just switched to the newest snapshot. My test world works fine (I haven't opened that one yet) as does a backup from before opening the world using the newest snapshot.
