### ISSUE TITLE
ubuntu 18.04 build issue? Imaging.h not found

### ISSUE THREAD

**Issue by BitcoinJake09** [overviewer/Minecraft-Overviewer#1651]
In file included from overviewer_core/src/main.c:18:0:
overviewer_core/src/overviewer.h:40:10: fatal error: Imaging.h: No such file or directory
 #include <Imaging.h>
          ^~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Failed to build Overviewer!

**Comment by CounterPillow** [comment]
Install pillow from the Ubuntu repositories and not through pip.

**Comment by ArcaneDisgea** [comment]
And if we have and we still receive this error?

**Comment by CounterPillow** [comment]
Then you should probably provide more info as to your Ubuntu version, what pillow package you installed and with what command.

**Comment by IncredibleHolg** [comment]
Hi,
I updated my Docker testing lab ( https://github.com/IncredibleHolg/OverviewerDocker ) to check
whether there are  recently introduced incompatibilities, but there are none.

The recent master branch compiles and runs for ubuntu:18.04 and ubuntu:19.10.
