### ISSUE TITLE
ssl cert for docs.overviewer.org is invalid

### ISSUE THREAD

**Issue by Scrxtchy** [overviewer/Minecraft-Overviewer#1653]
the certificate is only valid for `*.readthedocs.io`
I'm unsure on your webserver configuration, but you can use a single certificate with support for mulitple domains with certbot.
This may ease in configuration and updating certificates

**Comment by CounterPillow** [comment]
We don't link to HTTPS on docs.overviewer.org for that reason, and it's not something we can easily fix because the hosting of the docs are done by readthedocs, not us, and making TLS work with them is a PITA.

**Comment by Scrxtchy** [comment]
Is there an issue with linking https://overviewer.readthedocs.io/en/latest/ ?
