### ISSUE TITLE
JSObserver Error when folder doesn't exist.

### ISSUE THREAD

**Issue by posicat** [overviewer/Minecraft-Overviewer#1657]
Rendering a world for the first time I got the following error because I didn't have the output folder.  However without the JSObserver it happily creates the folder first.  Obviously not a critical problem, but an easy low-hanging-fruit for a Friday afternoon fix perhaps.

Exception: JSObserver: Output directory specified (/home/mc/public_html/overviewer/) doesn't appear to exist. This should be the same as the Overviewer output directory

**Comment by CounterPillow** [comment]
Thanks, was an easy fix. Not sure why whoever added the check didn't add the mkdir.
