### ISSUE TITLE
How to export the map as one big high res image?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1658]
Hi! 

Is there a way to export to map as one really big image? I would like to print the map.

**Comment by CounterPillow** [comment]
You can use `contrib/png-it.py` to generate one large image.

**Comment by luisdavid42** [comment]
Hello!

Is there any docuemntation or examples on how to specify the parameters? Thanks!

**Comment by CounterPillow** [comment]
Use `-h` or `--help` to see documentation about its invocation.

**Comment by luisdavid42** [comment]
> Use `-h` or `--help` to see documentation about its invocation.
Thanks. Can't seem to find the TILESET parameter description. What does it represent and how should it be specified?

**Comment by CounterPillow** [comment]
The name of your render in your config file, which is also the same as the directory name of the tile images if I recall correctly. It's the subfolder in your render output that has "blank.png" in it.

**Comment by LunchBox951** [comment]
I am trying to use png-it.py with this command line but it isn't working. What am I doing wrong?

`python png-it.py -m 16000 -z 5 -o C:\Minecraft\Render\overworld C:\Minecraft\Render`
