### ISSUE TITLE
Ocean floor covers legitimate caves when using the Cave render mode

### ISSUE THREAD

**Issue by MediocreFred** [overviewer/Minecraft-Overviewer#1659]
The ocean floor blocks the view of many legitimate caves when using the Cave render mode. It would be much nicer if the ocean floor was not considered part of a cave, especially if your map is dominated by the different ocean biomes like mine is. You can see in my attached image how it is not exactly great to look at. If there is a way to filter out the ocean floor, then it should be added to the docs. If it is already there then I should learn how to read.
![Selection_109](https://user-images.githubusercontent.com/32444519/66778202-0e5e9f80-ee99-11e9-9737-96866e70af56.png)

**Comment by dgrimreaper** [comment]
Without really knowing how the code works, I think in cave.c it's still not quite right for daylight light level.  Seems to happen for blocks 15 levels below sea level.
