### ISSUE TITLE
having an issue working with command prompt

### ISSUE THREAD

**Issue by MariusDarkblade** [overviewer/Minecraft-Overviewer#1661]
ok so i am not all that good with writing code all i know is python coding doesnt work with my computer or at least i'm so horrible at it i cant get it to work. with past versions i managed to get it working using cd cd D:\overviewer-0.14.72 to load overviewer and then typing in 
overviewer.exe "C:\Users\\AppData\Roaming\.minecraft\saves\amped" "D:\MinecraftMaps\amped"
to start making the map. with this new version though nothing is happening. it doesnt load overviewer cause when i type the second part in i get 'overviewer.exe' is not recognized as an internal or external command, operable program or batch file. what am i doing wrong? all i want is a simple map created, i dont need tags for signs and all the other bells and whistles a decent programmer could get this thing to show.

**Comment by EyeOfMidas** [comment]
You should also include the full path to overviewer.exe in quotes as well.

**Comment by CounterPillow** [comment]
>You should also include the full path to overviewer.exe in quotes as well.

You don't need to if you're cd'd in the right directory.

The problem here is that you are trying to cd into a directory that's on a different drive.

do this:
```
D:
cd overviewer-0.14-72
```

Then run the overviewer.exe command.

**Comment by CounterPillow** [comment]
Btw this particular pitfall of the Windows command line is covered here http://docs.overviewer.org/en/latest/win_tut/windowsguide/#common-pitfalls

**Comment by MariusDarkblade** [comment]
ah, thats why. it completely slipped my mind that it wasnt in C drive.
