### ISSUE TITLE
Overviewer for Minecraft: Bedrock Edition World Format

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1662]
I guess somebody has to ask this question: Can we somehow use the new world format with the rest of the overviewer code? At least it is documented: https://minecraft.gamepedia.com/Bedrock_Edition_level_format

**Comment by barrett777** [comment]
Fyi this is a duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/921

There's a bit of discussion over there
