### ISSUE TITLE
How can i resume a rendering of a world?

### ISSUE THREAD

**Issue by NewCrazyLeon** [overviewer/Minecraft-Overviewer#1672]
i know how to stop a rendering but how exactly can i resume it after i stopped it?

**Comment by deltaidea** [comment]
Just run the same rendering command again, it will detect previous progress. Does it not do that for you?

**Comment by CounterPillow** [comment]
Yes, you just run the command again. It will enter checktiles mode so the ETA will be wildly off but it will resume from where it left off.
