### ISSUE TITLE
Question about CLI Arguments

### ISSUE THREAD

**Issue by mide** [overviewer/Minecraft-Overviewer#1673]
👋 Howdy - I've got a quick question about the `./overviewer.py` command line arguments; are any of them mutually exclusive from one another? 

When reading [the documentation](http://docs.overviewer.org/en/latest/running/#options), it doesn't seem that any are mutually exclusive (meaning that any flags can be passed in any combination) but, it's been reported that `--genpoi` can't be used with `--no-tile-checks` (report on https://github.com/mide/minecraft-overviewer/issues/45 which uses vanilla Minecraft-Overviewer). 

I'm just looking for the "official" stance on this; is this a bug with Minecraft-Overviewer (the flags should be used/ignored), or should some arguments not be passed with some others (the current behavior is expected). This feedback will help me determine what the "fix" is.

Been a big fan of the project for a long time (and even contributed to [a bounty for it](https://www.bountysource.com/issues/58413427-support-for-1-13-chunk-format)). Thanks for the help!

**Comment by deltaidea** [comment]
Overviewer runs a completely different underlying script when you specify `--genpoi`. The docs [say here](http://docs.overviewer.org/en/latest/signs/#the-genpoi-option) that:

> A –genpoi run will NOT generate a map render, it will only generate markers.

And:

> The genPOI.py script is also provided, and can be used directly. [...] genPOI comes with a few options of its own.

Then `--skip-scan`, `--skip-players` etc. are described.

Are you trying to generate the map and the points of interest in the same run? Unfortunately, you have to run it twice. Here's how I do it:

```sh
python3 ../overviewer.py --config=config.py --processes 8
python3 ../overviewer.py --config=config.py --genpoi [--skip-scan]
```

**Comment by mide** [comment]
Okay, thanks. This answers my question!
