### ISSUE TITLE
How can i update a map?

### ISSUE THREAD

**Issue by NewCrazyLeon** [overviewer/Minecraft-Overviewer#1674]
my map doesnt update, i tried save -on but when i run it the same thing is happening like --help and i checked if the map updates but it didnt.
do you know how to make the map updating?

**Comment by NewCrazyLeon** [comment]
overviewer.exe save -on thats what i typed

**Comment by enaut** [comment]
To update the map you have to call exactly the same command as the one to create the map. The command you mention will not create the map. Please reread the Tutorial and figure out the right commands: http://docs.overviewer.org/en/latest/running/

**Comment by NewCrazyLeon** [comment]
so i just have to recreate the map and the map will then update automaticly?

**Comment by CounterPillow** [comment]
yes
