### ISSUE TITLE
Is it safe to run Overviewer while the world is in use?

### ISSUE THREAD

**Issue by PhoenixDiscord** [overviewer/Minecraft-Overviewer#1675]
Hello,

I'm thinking of moving from Dynmap back to Overviewer, and I have two questions.

Is it safe to render the world while it's being used? Is it possible for Overviewer to affect my server TPS? How much and how to make the lag lower?

Thanks.

**Comment by CounterPillow** [comment]
>Is it safe to render the world while it's being used?

Yes, Overviewer only opens files in read-only mode.

>Is it possible for Overviewer to affect my server TPS? How much and how to make the lag lower?

Yes, it can. You can however either limit its impact by increasing it's "nice" value so the scheduler doesn't give it as much CPU time, or you can limit the number of processes Overviewer spawns with the `--processes` option.
