### ISSUE TITLE
Overlapping tiles all over the rendered map

### ISSUE THREAD

**Issue by hieutvan** [overviewer/Minecraft-Overviewer#1676]
Hi there ;)

I've used Overviewer for quite a while and I found it's great! However, the rendered map usually has corrupt and overlapping tiles (as shown in the screenshot below). I've tried force-render, as well as deleting the render folder. I always execute the rendering process at midnight, at which no players are present. Please help me soon! Thanks!

I'm using MC 1.14.4, OV is built from source

![1226869725](https://user-images.githubusercontent.com/45692885/68640623-f717de00-053a-11ea-8549-843a915ceace.png)

**Comment by Tantriss** [comment]
Hi, do you render directly from the world folder or do you copy the world folder in another location and render from here ?
Because I had the same problem until I updated my script to `rsync` the world folder and render from the copy.

**Comment by hieutvan** [comment]
Wow so OV has to render from a static folder? That worked! Thanks a lot!

I think this probably should be added into the Readme.

**Comment by Doregon** [comment]
@hieu-van A little late but I have just added a note and I hope that my pull request will be accepted. The same happened to me.
