### ISSUE TITLE
Getting a black screen with only a spawn icon when I open the index.html

### ISSUE THREAD

**Issue by jheitor** [overviewer/Minecraft-Overviewer#1680]

**Comment by enaut** [comment]
Either you did not wait long enough for the render to finisch (in the commandline there is a progress - it takes hours rather than minutes). Or you did ignore a rendering error in the terminal.

**Comment by CounterPillow** [comment]
We can't help you if you don't give us more information.

1. Your browser and version
2. The console output of Overviewer
3. The version of overviewer you are using
4. In case you are able to share it, your world.
