### ISSUE TITLE
overviewer crashes since 1.15 with my world

### ISSUE THREAD

**Issue by RodolpheGohard** [overviewer/Minecraft-Overviewer#1684]
Hello, today I tried to run the overviewer on my world (worked before) and I get this error:

> C:\Users\gohard.r\Downloads\overviewer-0.14.72>overviewer.exe C:\Users\gohard.r\AppData\Roaming\.minecraft\saves\Menthe C:\Users\gohard.r\AppData\Roaming\.minecraft\overviewer-maps\Menthe
> 2019-12-11 10:43:47  Welcome to Minecraft Overviewer!
> 2019-12-11 10:43:47  Generating textures...
> 2019-12-11 10:44:09 E An error has occurred. This may be a bug. Please let us know!
> See http://docs.overviewer.org/en/latest/index.html#help
> 
> This is the error that occurred:
> Traceback (most recent call last):
>   File "overviewer.py", line 650, in <module>
>   File "overviewer.py", line 559, in main
>   File "overviewer_core\world.py", line 219, in find_true_spawn
>   File "overviewer_core\world.py", line 1352, in get_chunk
> ValueError: cannot reshape array of size 1024 into shape (16,16)

**Comment by CounterPillow** [comment]
Update
