### ISSUE TITLE
Since upgrading server.jar to 1.15, Overviewer ends with a "cannot reshape array of size" error

### ISSUE THREAD

**Issue by chaseflynn** [overviewer/Minecraft-Overviewer#1692]
I get the following when running my Overviewer render (that worked without issue on v 1.14 of Minecraft server):

------

2019-12-15 20:47:29  Welcome to Minecraft Overviewer!
2019-12-15 20:47:29  Generating textures...
2019-12-15 20:47:36 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 650, in <module>
  File "overviewer.py", line 559, in main
  File "overviewer_core\world.py", line 219, in find_true_spawn
  File "overviewer_core\world.py", line 1328, in get_chunk
ValueError: cannot reshape array of size 1024 into shape (16,16)

Press [Enter] to close this window.

------

I haven't submitted a bug on Github before, nor for this application.  Please let me know if further documentation is needed.

**Comment by CounterPillow** [comment]
Update your overviewer version

**Comment by chaseflynn** [comment]
> Update your overviewer version

I have the latest from overviewer’s site. Is there a different place with a newer version?

**Comment by CounterPillow** [comment]
Are you on an RPM-based distro by any chance? Our RPM builders are broken, so you'll have to build from source if that's the case.

**Comment by chaseflynn** [comment]
> Are you on an RPM-based distro by any chance? Our RPM builders are broken, so you'll have to build from source if that's the case.

No.  But I found my mistake.  I changed the config file path in my shortcut, but not the folder one.  It's running now - thanks!
