### ISSUE TITLE
Add beehives from 1.15 to the MineralOverlay

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1694]
Hi! I try to find beehives in our world and would like to make them visible on a layer. So i asked myself: What is the blockid of a beehive? I look in https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/src/mc_id.h but did not find it. So how do I do it?

**Comment by Gyzie** [comment]
The new 1.15 blocks have not yet been added to Overviewer and therefor don't have a block ID yet. But once they are added you will find the block ID in the file you referred to.

**Comment by Gyzie** [comment]
I've created a pull request for the missing blocks #1701 once it gets merged the item id's will be:
```
block_beehive = 11501,
block_bee_nest = 11502,
block_honeycomb_block = 11503,
block_honey_block = 11504,
```
