### ISSUE TITLE
Strange dithering in all biomes (water, forrest) since 1.15

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1696]
Areas that have been changed since 1.15 have a strange looking dither. You can see it in those screenshots. 
<img width="417" alt="mixed" src="https://user-images.githubusercontent.com/136737/71326734-aa430200-24ff-11ea-9d5a-e3ba8e824223.png">

The first screen shows the difference how the same area looks after something has changed in 1.15 and somebody swam along.. 

<img width="692" alt="1 14 4" src="https://user-images.githubusercontent.com/136737/71326735-aa430200-24ff-11ea-8f91-26088a6a295f.png">

Above is a screenshot how it should look. 

<img width="540" alt="1 15" src="https://user-images.githubusercontent.com/136737/71326736-aa430200-24ff-11ea-9776-052b624a3286.png">

Above is how it look since 1.15

<img width="864" alt="1 15 zoomed" src="https://user-images.githubusercontent.com/136737/71326737-aadb9880-24ff-11ea-94bc-84f5a69c3d74.png">
Zoomed screen

**Comment by Katipo007** [comment]
It affects all biomes (it's just more noticeable on the water), it appears the new biome decoding isn't quite right

**Comment by mtoensing** [comment]
Oh. I changed the title

**Comment by jhardin-impsec** [comment]
I see the same thing, but only in water. I'm using a custom texture pack which may somehow be suppressing the behavior on land.

**Comment by mtoensing** [comment]
Maybe somebody can find the cause of the the problem and fix it.

**Comment by mtoensing** [comment]
Thank you!

**Comment by mtoensing** [comment]
it is sadly not fixed We have a new problem now: #1698

**Comment by jhardin-impsec** [comment]
Looks fine for me. Further comments on #1698
