### ISSUE TITLE
New rendering problems on water biomes related to #1696

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1698]
This bug is related to the fix for #1696. Water appears without any structure. It s rendered as a blue area without the water details. 

Before "fix" for #1696
<img width="1271" alt="Screen Shot 2019-12-23 at 21 16 51" src="https://user-images.githubusercontent.com/136737/71378838-96fc6900-25c9-11ea-993a-8e95c09864b1.png">
After fix of #1696
<img width="1271" alt="Screen Shot 2019-12-23 at 21 16 57" src="https://user-images.githubusercontent.com/136737/71378851-995ec300-25c9-11ea-8308-fa7249e11d17.png">
Should look more or less like this: 
<img width="1044" alt="Screen Shot 2019-12-23 at 21 19 08" src="https://user-images.githubusercontent.com/136737/71378957-ea6eb700-25c9-11ea-89f3-c66177b54839.png">

Example map with new bug, old bug (cache) and how it should look: https://mc.marc.tv/iso/

**Comment by jhardin-impsec** [comment]
I don't see this. Here is the same part of the map that I posted to #1696, just now rerendered with the changes to fix that bug:

![mco_banding_fixed](https://user-images.githubusercontent.com/7682732/71381417-529ca900-2588-11ea-93a5-163c79b9a114.png)

It looks fine at all zoom levels.

**Comment by mtoensing** [comment]
On your part of the map is no differently shaped water. That‘s the reason why you don‘t see it. Have a look at my whole map. You see that there are parts that show water details without the fuzziness before 1.14 and now after the fix for the dithering there is only one water color. Or is this the indented result and we have to life with it?

**Comment by mtoensing** [comment]
<img width="677" alt="Screen Shot 2019-12-24 at 12 54 30" src="https://user-images.githubusercontent.com/136737/71412132-96f17d00-264c-11ea-9175-ac7c87791519.png">
I can confirm that it works again. It seems like a lower resolution layer though.

**Comment by CounterPillow** [comment]
Yes, Minecraft apparently lowered the resolution of biomes. We could filter it but that's added complexity for something you barely notice in most cases; the water colouring is something seemingly only Overviewer does and not the game, and it's also the only place where you notice the lower resolution.

**Comment by mtoensing** [comment]
Merry Xmas first of all! Maybe in this case I personally would prefer a blue surface and not the edgy pattern. Or you could just use a bilinear filter. But I guess that is what you mean with a filter. 
I would prefer this 
<img width="931" alt="not-edgy" src="https://user-images.githubusercontent.com/136737/71414625-13d62400-2658-11ea-9a39-6412505f0ffc.png">
over that
<img width="1165" alt="edgy" src="https://user-images.githubusercontent.com/136737/71414621-1173ca00-2658-11ea-8c4d-cf5ae593cfae.png">

**Comment by mtoensing** [comment]
I say that because we printed our whole map and those edgy pattern would not look to good ;-)

![WhatsApp Image 2019-11-15 at 13 25 18](https://user-images.githubusercontent.com/136737/71414771-b68ea280-2658-11ea-94ff-e7987dfdb624.jpeg)
![WhatsApp Image 2019-11-15 at 13 25 12](https://user-images.githubusercontent.com/136737/71414772-b68ea280-2658-11ea-89a2-b4ac16f2b726.jpeg)

**Comment by CounterPillow** [comment]
Cool! I'll look into how Minecraft renders water and how Overviewer does it and then add an option to disable our non-Minecraft-canon water tinting I guess.

**Comment by mtoensing** [comment]
Thank you. Your work is much appreciated!

**Comment by jhardin-impsec** [comment]
OK, I can confirm too. Agreed it's a bit chunky - looks like it's working on minimum 2-block "pixels".
