### ISSUE TITLE
Manual POIs in Minecraft-Overviewer 

### ISSUE THREAD

**Issue by NakedSkull1991** [overviewer/Minecraft-Overviewer#1710]
Please write down a video tutorial, it is very difficult for me to understand how adding points works.

Without a specific example, it is difficult for me to do something myself, since I do not understand this programming language. 

[Unfortunately the instructions didn't help me ](http://docs.overviewer.org/en/latest/signs/#the-genpoi-option)

**Comment by Katipo007** [comment]
Here is an example from my setup

```python
# list of manual locations
manual_locations = [
    {
        'id':'Location',
        'x':-3900,
        'y':64,
        'z':6824,
        'name':'Pig Racing',
        'description':'Happens once a week!'
    },
    {
        'id':'Location',
        'x':0,
        'y':64,
        'z':0,
        'name':'ATM',
        'description':''
    }
]


renders['normalrender'] = {
    'world':'world',
    'title':'Overworld',
    'dimension': 'overworld',
    'northdirection': "upper-left",
    'manualpois': manual_locations,  # add this line to your render(s)
}
```

**Comment by CounterPillow** [comment]
@Katipo007 your example is missing the render dictionary key for the markers filter, which means this won't create a markers group, which means it won't work.

The documentation contains a working example for Manual POIs: http://docs.overviewer.org/en/latest/signs/#manual-pois

**Comment by Katipo007** [comment]
My apologies. CounterPillow is correct, I missed copying a few lines from my config.
Follow the example referenced by CounterPillow.
