### ISSUE TITLE
SyntaxError: can use starred expression only as assignment target

### ISSUE THREAD

**Issue by FRLVME** [overviewer/Minecraft-Overviewer#1711]
File "/srv/overviewer-Minecraft-Overviewer-751ba39/overviewer_core/textures.py", line 4524
    @material(blockid=[199, *range(21000,21013+1)], data=list(range(32)), transparent=True, nospawn=True)
                           ^
SyntaxError: can use starred expression only as assignment target

**Comment by CounterPillow** [comment]
What version of Python are you using?
