### ISSUE TITLE
genPOI: Scans render region sets more then once

### ISSUE THREAD

**Issue by jobe1986** [overviewer/Minecraft-Overviewer#1723]
OK, firstly I will state that I made a minor modification to genPOI, but that was only a simple print() call to produce a tiny bit of extra output to help with debugging.

But anyway as a result of that I was able to determine that each of the cropped region sets defined by my config were scanned more then once and as a result the entire process took far longer then it should have.

The command used to run genPOI in this instance was:
`/home/simplanet/overviewer/bin/overviewer.py -p 2 --config=/home/simplanet/overviewer/overviewer.conf --genpoi 2>&1 | /usr/bin/tee -a /home/simplanet/logs/overviewerpoi.log`

Attached are the config I used (.txt added because github refused .conf), the FULL output of genPOI, and a summarised output demonstrating the above issue (and the added print() outputs)

[summary.log](https://github.com/overviewer/Minecraft-Overviewer/files/4191754/summary.log)
[overviewer.log](https://github.com/overviewer/Minecraft-Overviewer/files/4191756/overviewer.log)
[overviewer.conf.txt](https://github.com/overviewer/Minecraft-Overviewer/files/4191764/overviewer.conf.txt)

**Comment by jobe1986** [comment]
Oh forgot to attach the diff showing the minor change I made for debugging:

[debug.diff.txt](https://github.com/overviewer/Minecraft-Overviewer/files/4191842/debug.diff.txt)

**Comment by tswsl1989** [comment]
Looking at the code, I'm wondering if something odd is happening here such that the filters aren't being grouped with the regionsets properly:

https://github.com/overviewer/Minecraft-Overviewer/blob/a929b55d4e2d614f3c31b8ba8dfdf86263246150/overviewer_core/aux_files/genPOI.py#L546-L550

Do you see the same multiple scans if you run in single process mode?

**Comment by jobe1986** [comment]
Although the test run is still going I can at this point confirm that at least one region set has been scanned more then once as both these lines have been output so far:
```
2020-02-12 12:15:19  Looking for entities in <overviewer_core.world.CroppedRegionSet object at 0x7fa31642d828>...
2020-02-12 12:40:33  Looking for entities in <overviewer_core.world.CroppedRegionSet object at 0x7fa31642d828>...
```

**Comment by jobe1986** [comment]
And as promised heres the final output of that run:
[overviewer-02.log](https://github.com/overviewer/Minecraft-Overviewer/files/4192773/overviewer-02.log)

**Comment by cliffmeyers** [comment]
I've experienced this issue too but didn't see it filed. I was working on this the other night and opened a PR recently that should fix it:  #1755

**Comment by cliffmeyers** [comment]
@jobe1986 if you're able to pull the branch down and test, let me know!

**Comment by jobe1986** [comment]
Seems resolved in current head.
