### ISSUE TITLE
Windows prebuilt package not working

### ISSUE THREAD

**Issue by proudft** [overviewer/Minecraft-Overviewer#1724]
Following instructions on http://docs.overviewer.org/en/latest/installing/  gets me just some error messages that sound like something isn't installed when I run overviewer.exe.  Screenshot below.  I thought it might be the drive or directory name or something but I get the same error message when just trying "overviewer --help"

This is the 64-bit install on a 64-bit machine. I installed the Visual C++ 2008 Redistributable Package (x64), and started to install the Visual C++ 2010 Redistributable Package (x64), but that one said I already had a later version so I left it alone.

I barely know python, so the error messages leave me a bit mystified.  I set my path= to nothing in case some old install of python or something else was messing with it, but no change.

![over_error](https://user-images.githubusercontent.com/2680066/74381114-b9c42600-4d9f-11ea-9caa-2afa7dca938b.png)

**Comment by CounterPillow** [comment]
Hi, this is a known issue with setuptools/pyinstaller right now. We'll try to get it fixed soon.
