### ISSUE TITLE
Super big mca file?

### ISSUE THREAD

**Issue by NumseBacon** [overviewer/Minecraft-Overviewer#1726]
Hello! So I ran overviewer etc etc etc and then it said something along the lines of "Holy shit what is wrong with (some coords)" like what is going on there?
And then two questions. 
Is there a way to make it easier to render when its a server instead of downloading the file everything... And then is there a way to make it speed up rendering?

**Comment by CounterPillow** [comment]
>Hello! So I ran overviewer etc etc etc and then it said something along the lines of "Holy shit what is wrong with (some coords)" like what is going on there?

You have an MCA file with tremendously huge coordinates, namely above 500000 making this several million blocks offset from the world centre. This is usually a sign of a stray chunk that has been generated by Minecraft.

>Is there a way to make it easier to render when its a server instead of downloading the file everything...

**Comment by NumseBacon** [comment]
It's not over 500k and how would I run it on the server or the two other options

**Comment by CounterPillow** [comment]
>It's not over 500k

But that's what the code checks.

https://github.com/overviewer/Minecraft-Overviewer/blob/51efdbaa4e79763a58c09fbda2155bcb2f346298/overviewer_core/world.py#L1531-L1537

If you're not more specific, I can't help you.

>how would I run it on the server

You need shell access, e.g. through SSH, for this.
