### ISSUE TITLE
Is the exit code of overviewer after successful generation not 0?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1729]
Hi! 

I start overviewer with this command: 

`/tmp/overviewer/overviewer.py --config=/tmp/config/config.py`

the log show this message in the last line: 

`7.79t/s eta 00h 00m 05s  98% [=====================================================================================================  ] 1158 7.92t/s eta 00h 00m 01s
`

overviewer shows no error and everything seems to be fine. But the surrounding container "exits unexpectedly".

<img width="326" alt="Screen Shot 2020-02-19 at 08 18 35" src="https://user-images.githubusercontent.com/136737/74811124-289a0580-52f1-11ea-8f4d-3256c72a6dee.png">

https://github.com/mtoensing/Docker-Minecraft-Overviewer/blob/master/Dockerfile

This changed a few months ago. It was ok before. I know @CounterPillow  hates docker but could somebody at least give me a hint if the problem is on my side or if it is overviewer?

**Comment by CounterPillow** [comment]
Overviewer's exit code on success is 0. You can check this from a shell by looking at the variable `$?`.
