### ISSUE TITLE
[Question] Add static content to generated index.html?

### ISSUE THREAD

**Issue by darkspirit510** [overviewer/Minecraft-Overviewer#1749]
Is there any config way to add content to the generated index.html (leaflet plugins and other js stuff) or do I have to do this by script after generation?

**Comment by DragonDev1906** [comment]
You can use the (custom-web-assets)[http://docs.overviewer.org/en/latest/config/#custom-web-assets]. By copying the index.html file from `overviewer_core/data/web_assets/index.html` to the folder specified by custom-web-assets you should be able to modify the file and see the changes in your output
