### ISSUE TITLE
overviewer.py command not found

### ISSUE THREAD

**Issue by BenRulez** [overviewer/Minecraft-Overviewer#1750]
Hi, im not the best when it comes to linux but i know enough to run my server, i tried running overviewer.py and it just says "Overviewer.py: no such file or directory" tried it as ./overviewer.py aswell
i followed the install guide and everything went fine until this point
I do have python installed but havent used it before

**Comment by cliffmeyers** [comment]
- Are you able to confirm where `overviewer.py` was installed on your system? Which install guide did you follow? Did you install from a package or build from source?
- Please also run `echo $PATH` so we can understand whether the executable is on your path or not

**Comment by BenRulez** [comment]
As i said im not the best with this stuff, i know enough to get by.
I dont know where overviewer.py is installed, i was in my home folder when i installed (using the guide on the documentation, installed from package)

**Comment by EvilSupahFly** [comment]
I would follow the "Building" instructions in [the Documentation](http://docs.overviewer.org/en/latest/building/#linux) for best results. The packaged version (at least on my Linux Mint 19.3 install) doesn't work.

After you download and install everything is tells you (make sure you put everything in one folder - I made an "Overviewer" folder in my Home folder to simplify everything), you would need to do both `python3 setup.py build` and `python3 setup.py install` so you can call it from anywhere.

This probably goes without saying, but you'll have better results in a terminal. :stuck_out_tongue:

**Comment by CounterPillow** [comment]
Please don't run `setup.py install`, I hate having to help users who have like 3 different versions of overviewer partying up in their global python directories causing issues for everyone involved.

**Comment by EvilSupahFly** [comment]
I guess I took for granted that people would only install one, or remove older versions first. Sorry!
