### ISSUE TITLE
Performance issues with local build

### ISSUE THREAD

**Issue by clandrew** [overviewer/Minecraft-Overviewer#1753]
Hello, I'm comparing
1\) The downloaded Windows binary Overviewer.exe, version v0.15
2\) Locally built Overviewer.py, version v0.13

here 1) performs about 10x faster than 2).

The problem could be improvements in Overviewer itself, or the .exe performs better than the .py script, or my local build is built in some kind of debug way. It's not clear how the .exe is produced or how to build it locally so it's hard to speculate about. 

To make sure I'm not "doing it wrong", how am I supposed to local build and have it perform well?

**Comment by CounterPillow** [comment]
What the hell is "version v0.5" and "version v0.3"?

Also, what did you build it with?

**Comment by clandrew** [comment]
That should have said v0.15 and v0.13, missing a 1.

It was built with Developer Command Prompt for VS 2017 with Python 2.7.15 x86, following the "building with Visual Studio" instructions on this page:
[http://docs.overviewer.org/en/latest/building/](http://docs.overviewer.org/en/latest/building/)

**Comment by clandrew** [comment]
I edited it to fix the version numbers

**Comment by CounterPillow** [comment]
Well, me and agrif did make Overviewer substantially faster between those two versions, so I doubt it's a problem with your build but a problem with your choice of version. Why are you using such an old version anyway?
