### ISSUE TITLE
"Sorry, you requested dimension 'Nether' for nether, but I couldn't find it"

### ISSUE THREAD

**Issue by EvilSupahFly** [overviewer/Minecraft-Overviewer#1754]
I was testing the new 20w14-infinite snapshot (having seen several prominent YouTubers test drive it already), and wanted to map the different dimensions just for lolz.

As expected, Overviewer was able to map all of the new dimensions by referencing them appropriately in the config file, except for the original Nether:
```
seann on black-beast Wed Apr 15 03:03 PM
[~/.local/share/multimc/instances/20w14infinite Snapshot Testing/.minecraft/saves] $ cat 20w14-Infinite.py
from .optimizeimages import pngnq, optipng

worlds["20w14-Infinite"] = "/home/seann/.local/share/multimc/instances/20w14infinite Snapshot Testing/.minecraft/saves/-1881547168"

new_nether_smooth = [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.9)]
#old_nether_smooth = [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.4)]

imgformat = "png"

def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

renders["Overworld"] = {
    "world": "20w14-Infinite",
    "title": "Overworld",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "overworld",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["Nether"] = {
    "world": "20w14-Infinite",
    "title": "Nether",
    "rendermode": new_nether_smooth,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "Nether",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM1142927152"] = {
    "world": "20w14-Infinite",
    "title": "DIM1142927152",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM1142927152",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM1255756068"] = {
    "world": "20w14-Infinite",
    "title": "DIM1255756068",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM1255756068",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM1644068866"] = {
    "world": "20w14-Infinite",
    "title": "DIM1644068866",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM1644068866",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM2140661813"] = {
    "world": "20w14-Infinite",
    "title": "DIM2140661813",
    "rendermode": new_nether_smooth,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM2140661813",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM355196910"] = {
    "world": "20w14-Infinite",
    "title": "DIM355196910",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM355196910",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM721984490"] = {
    "world": "20w14-Infinite",
    "title": "DIM721984490",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM721984490",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

renders["DIM839619722"] = {
    "world": "20w14-Infinite",
    "title": "DIM839619722",
    "rendermode": smooth_lighting,
    "optimizeimg":[pngnq(sampling=1), optipng(olevel=3)],
    "dimension": "DIM839619722",
    "markers": [dict(name="All signs", filterFunction=signFilter),
                dict(name="All players", filterFunction=playerIcons)],
}

outputdir = "/home/seann/Maps/20w14-Infinite/"
```
If I refer to the nether as `"dimension": "nether"`, or ` "dimension": "Nether",` (I assumed it might be case-sensitive), it fails to find it.

However, if I refer to it as ` "dimension": "DIM-1",`, Overviewer maps finds it but unlike traditional renders, it doesn't cut the roof off, so everything is obscured and I can't see all the cool stuff in the new Nether Biomes on the rendered map.

I know it's probably crazy to be trying this with a snapshot version, but the Snapshots eventually lead to stable releases, and if this is an issue with the snapshot, then unless I screwed something up, it could very well carry forward.

I turned on debug, and the complete render output from my Terminal (this run being the failed entry for `"dimension": "Nether"`) is [available here](https://paste.ubuntu.com/p/Wd8TwxKn2c/) if someone wants to have a look and let me know if I screwed something up, or if there's something else going on.

[System specs](https://paste.ubuntu.com/p/9vQhMvMHc5/), just in case, and of course the output from `uname` and `overviewer.py --version` should you also require them:
```
Linux black-beast 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Minecraft Overviewer 0.15.28 (7af188d)
built on Thu Apr  9 20:35:34 2020
```

Screenshot of Dimension list from rendered map:
![Screenshot from 2020-04-15 18-24-05](https://user-images.githubusercontent.com/3280846/79394991-b5a2b900-7f46-11ea-971b-76da5405f72f.png)

**Comment by EvilSupahFly** [comment]
No ideas why it doesn't like this particular snapshot? I'll try updating Overviewer and see what happens.

**Comment by Kaemmelot** [comment]
I don't know about this snapshot, but you need to use `"dimension": "nether"` (all small) or `"dimension": "DIM-1"`. They are the same, because `"nether"` is converted [here](https://github.com/overviewer/Minecraft-Overviewer/blob/204bcd0310d7e874b2770d0007fa1d96f03ed652/overviewer_core/settingsValidators.py#L232). Maybe the dimension is something else in that snapshot. You could try to look into the world folder `/home/seann/.local/share/multimc/instances/20w14infinite Snapshot Testing/.minecraft/saves/-1881547168` for the correct name of the subdirectory.

Also **don't forget** to do a force render. If you just want to re-render the nether, I suggest adding `"forcerender": True,` as explained [here](https://docs.overviewer.org/en/latest/config/#map-update-behavior).

**Comment by EvilSupahFly** [comment]
Excellent advice! The original Nether is still named DIM-1, but I did see in the blob that dimensions are case sensitive, so I'll change it to "nether", add 'force-render' and see what happens.

![Screenshot_20200501-100920](https://user-images.githubusercontent.com/3280846/80811679-61c5e000-8b94-11ea-9ef3-6282e54352cf.png)

**Comment by EvilSupahFly** [comment]
Sorry..... with the way things have been lately, I didn't have time to get back to this until this week.

That being said, it works now having fixed the letter case. I was sure I used all lower case during my initial tinkering in April, but I guess I missed it.

The point is that now it works the way I expected, so I'm closing this issue.

Thanks!
