### ISSUE TITLE
Support 1.16

### ISSUE THREAD

**Issue by crlang44** [overviewer/Minecraft-Overviewer#1766]
Support the upcoming version Minecraft 1.16
Definitely willing to help out on this if needed but would need some guidance.

Noted changes:
https://www.minecraft.net/en-us/article/minecraft-snapshot-20w17a
https://www.minecraft.net/en-us/article/minecraft-snapshot-20w18a

Current Renders from 20w18a:
![image](https://user-images.githubusercontent.com/4143306/80847685-6eaef780-8bc5-11ea-80c8-d7884a172bea.png)
![image](https://user-images.githubusercontent.com/4143306/80847688-7078bb00-8bc5-11ea-9b9e-2d09c897ab39.png)

**Comment by iRath96** [comment]
Thanks for reporting this -- but this is already tracked in #1760 and a fix is given by PR #1759 which is yet to be merged.

**Comment by crlang44** [comment]
That right there is a best case scenario response! Thank you very much, I think I only searched on 1.16 when I was looking if someone already submitted a ticket for it. I will close this one in favor of #1760
