### ISSUE TITLE
Question: 2d world map?

### ISSUE THREAD

**Issue by JulienTant** [overviewer/Minecraft-Overviewer#1770]
Hi,

I'm sorry i've looked in the documentation but could not find the answer : can we generate a 2d map instead of 3d ?

**Comment by enaut** [comment]
No 2D is not possible only "3D" from different perspectives. It's not really 3D though it's called isometric view. If you want a top-down 2D view there are other tools to do that.  Look for something fitting your needs here: https://minecraft.gamepedia.com/Programs_and_editors/Mapping

**Comment by eminence** [comment]
I confirm that overviewer only supports a 3d isometric view (it does not support a top-down view)
