### ISSUE TITLE
Apache default aliases and /icons subfolder are colliding.

### ISSUE THREAD

**Issue by Webbeh** [overviewer/Minecraft-Overviewer#1773]
Hi.

This is not really a bug, more like a change request.

With Apache 2's default configuration on some systems (notably Arch Linux), the `/icons` subfolder is aliased to apaches default icons, for fancy indexing.

There are a few ways to disable that option, the easiest being to just re-alias `/icons` to the folder they should actually be pointing to, but it's a little hacky.

If people don't disable this, no icons in `/icons` subfolder will show, since the wrong folder is read.

I know you can change the web path by yourself, but to avoid a potential issue with people who don't know much about Apache configuration, maybe it would be best to rename the `/icons` folder to something else, for example simply `/icon` or `/markers`, or something similar.

It will avoid some headaches for everyone :)

Thank you !

**Comment by CounterPillow** [comment]
I've been thinking about doing this for a while, but one issue is that anyone with some custom markers that use our shipped icons would have their config break, which isn't very fair to those people smart enough to use nginx.

**Comment by Webbeh** [comment]
>  which isn't very fair to those people smart enough to use nginx.
Not everyone neds that :shrug: 

How about a move to `/markers` and add a symlink from `/icons` to `/markers` ?

**Comment by IncredibleHolg** [comment]
As far as I can see, the only relevant part of code processing /icons is in 

```python
        dump = dict()
        dump['CONST'] = dict(tileSize=384)
        dump['CONST']['image'] = {
            'defaultMarker':    'signpost.png',
            'signMarker':       'signpost_icon.png',
            'bedMarker':        'bed.png',
            'spawnMarker':      'icons/marker_home.png',
            'spawnMarker2x':    'icons/marker_home_2x.png',
            'queryMarker':      'icons/marker_location.png',
            'queryMarker2x':    'icons/marker_location_2x.png'
        }
```

Ho about having "icons/..." as deefault string and add an option to use another prefix string?

**Comment by Webbeh** [comment]
The only real problem is really that people who have /icons as an alias by default will most likely either know about it and change it themselves, or won't know why their icons are not found.

Having it changed to something else and adding a symlink from /icons to that new location doesn't break compatibility with existing setups (except in rare edge cases of people disabling symlinks).

I'm only suggesting this as a cautionary measure. Didn't see any issue reported here about it, so maybe the proper course of action could be a simple warning in the docs and a config option to rename the folder, as you suggested.

**Comment by bold-gman** [comment]
Apache having the default alias icons leads to most people not using the icons in the first place. I don't think most users will go the long and hacky road to deactivate the setting, so custom icons are more or less a minority use case.
On principle, as long as there is no RFC or other standard, you should be free to name paths and folders however you want. But since Apache is a very big player in the Web ecosystem, that choice should be reconsidered, as it collides with real life applications.

**Comment by Webbeh** [comment]
It wouln't be a problem if the spawn icon (that is shown automatically by default by Overviewer on all maps) wasn't in that folder :)

**Comment by bold-gman** [comment]
That's the same reason why I even found out about it. Would not have noticed otherwise.

**Comment by 66tree** [comment]
If you're trying to figure out how to fix this on a Debian based system I was able to fix the collision by editing /etc/apache2/mods-enabled/alias.conf. I commented out the following: ```
#Alias /icons/ "/usr/share/apache2/icons/"

        #<Directory "/usr/share/apache2/icons">
        #       Options FollowSymlinks
        #       AllowOverride None
        #       Require all granted
        #</Directory>
Restart Apache using `sudo systemctl restart apache2`
```

**Comment by Webbeh** [comment]
@66tree that is not a good solution, as it disables the /icons folder globally.

Simply redo an `Alias /icons <over viewer icons full path>` in the virtual host definition for overviewer.

It will disable the global alias only for that virtual host, keeping the fancy indexes for everything else.

**Comment by 66tree** [comment]
@Webbeh Thanks for the reply. I deleted my comment so I wouldn't steer anyone in the wrong direction!

**Comment by bold-gman** [comment]
In the end, it comes down to either sticking with the principle of naming the folder "icons" and offering another solution for apache users (configurable pathname, or at least a short description in the documentation on how to change the alias for one vhost, like @Webbeh did) or to changing the folder to something else.

Now, I get that time is always the most spare ressource here, so expanding the documentation looks like a good middleground to me.
