### ISSUE TITLE
Add new map to render without having to re-render old maps?

### ISSUE THREAD

**Issue by pomtom44** [overviewer/Minecraft-Overviewer#1775]
I have a world which has been slowly growing over time and I have been getting weekly saves of the world to do some timelapse style work using overviewer and screenshotting it

the problem is my world is now 50GB big, and still growing
If I was to put all the world downloads into one folder for overviewer to take and convert into a single webpage (where you can pick the date you want to view) the world folder would be around 250-300GB big, and each week it would at at least another 50GB if not more as the world grows

Is there a way to take a map, render it, delete the world data, add a new world and add to the original map without deleting anything that was rendered before?

**Comment by enaut** [comment]
The easiest way is probably to allways render to "current" and right before rendering you copy the directory of the maps. If you use a capable filesystem that compresses dublicates this does not result in huge diskspace used. You could use btrfs snapshots on linux:  https://www.linux.com/training-tutorials/how-create-and-manage-btrfs-snapshots-and-rollbacks-linux-part-2/

**Comment by IncredibleHolg** [comment]
I have a worlupdate script, botj for changes in the world and changes in Overviewer.
It looks like this:

```bash
#!/bin/bash
# extract to tmp
WORLDFILE=$HOME/WRK/Minecraft/ServerBackup/vanilla18_200531.tar.gz
OVDIR=/home/hdunkel/WRK/GIT/GitHub/IncredibleHolg/IncH_Minecraft-Overviewer
#OVDIR=../Minecraft-Overviewer
OVERVIEWER=${OVDIR}/overviewer.py
#BRANCH=addblocks-dec19-01
BRANCH=master
## start rendering
( cd $OVDIR/ && git checkout  $BRANCH && python3 setup.py build  )|| exit 1
if [ ! -d tmp ] ; then mkdir tmp ; fi
tar -zxf $WORLDFILE -C tmp/
# sync to working world copy
rsync  --delete -rtv tmp/minecraft/ minecraft/
# cleanup tmp
rm -rf tmp/minecraft
# start rendering

python3  $OVERVIEWER  -c  vanilla18.py

```

The config file ```vanilla18.py``` referres to the ```minecraft``` folder containing the worlddata updated with rsync.
