### ISSUE TITLE
Docs: XSS in example filter functions

### ISSUE THREAD

**Issue by jedenastka** [overviewer/Minecraft-Overviewer#1795]
In [this](http://docs.overviewer.org/en/latest/signs/#filter-functions) example filter function there is a XSS vulnerability.

If you write this on a Minecraft sign:

![2020-07-01_18 08 33](https://user-images.githubusercontent.com/33988779/86267048-66276d00-bbc6-11ea-8d98-4aa684f3a769.png)

and then click on its marker on Overviewer, an alert pops up:

![image](https://user-images.githubusercontent.com/33988779/86267248-b7cff780-bbc6-11ea-8da2-abdce3b1266d.png)

This is probably an oversight in Leaflet, but you should change the example (maybe include a warning that you need to sanitize it yourself).

NOTE: Escaping the formatting client-side would prevent intended formatting of the text, please, don't do this.

**Comment by CounterPillow** [comment]
Intended behaviour

**Comment by jedenastka** [comment]
@CounterPillow It's okay if it's intended, I only want the example to be changed, or to at least have a warning.

**Comment by CounterPillow** [comment]
I guess I'll adjust the escaped HTML example to actually work on Python 3, and add a small note to the first filter example, but generally speaking I'd rather not have example code that serves as examples be cluttered up by things.
