### ISSUE TITLE
Overviewer never progresses after updating from v 0.14.96 to 0.15.81

### ISSUE THREAD

**Issue by chaseflynn** [overviewer/Minecraft-Overviewer#1798]
Now, when I run Overviewer on my 1.16.1 world, it sticks at 

> 2020-07-01 19:58:13  Welcome to Minecraft Overviewer version 0.15.81 (27eabb0)!
2020-07-01 19:58:13  Forcerender mode activated. ALL tiles will be rendered.
2020-07-01 19:58:13  Generating textures...

It's still using plenty of CPU and I've let it run for at least an hour but it never advances past the above.  I appreciate any assistance - let me know what I can attach that would be helpful (config file below)

Thanks!

-------------------------- config file -----------------------

worlds["SOAP!"] = "C:\\Users\\chase\\Desktop\\SOAP MC server\\world"

processes = 2

myendrender = end_lighting = [Base(), EdgeLines(), Lighting(strength=0.5)]
end_smooth_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.5)]

renders["survivalday"] = {
	"world": "SOAP!",
	"title": "Overworld - Day",
	"rendermode": smooth_lighting,
	"dimension": "overworld",
}

renders["survivalnight"] = {
	"world": "SOAP!",
	"title": "Overworld - Night",
	"rendermode": smooth_night,
	"dimension": "overworld",
}

renders["survivalcave"] = {
	"world": "SOAP!",
	"title": "Overworld - Caves",
	"rendermode": cave,
	"dimension": "overworld",
}

renders["survivalnether"] = {
    "world": "SOAP!",
    "title": "Survival Nether",
    "rendermode": nether_smooth_lighting,
    "dimension": "nether",
}

renders["survivalend"] = {
	"world": "SOAP!",
	"title": "The End",
	"rendermode": myendrender,
	"dimension": "end",
}

outputdir = "C:\inetpub\wwwroot\Maps"

**Comment by chaseflynn** [comment]
With verbose logging enabled, this are the last lines in the command prompt:

`world.py:1772      16440 2020-07-03 09:00:18 DEBUG    Initializing a cache with key 'C:\Users\chase\Desktop\SOAP MC server\world\region'`
`world.py:171       16440 2020-07-03 09:00:18 DEBUG    You asked for None, and I found the following candids: [<RegionSet regiondir='C:\\Users\\chase\\Desktop\\SOAP MC server\\world\\region'>]`

**Comment by CounterPillow** [comment]
Can you upload your level.dat for me? It seems that's the thing it's doing here.

**Comment by chaseflynn** [comment]
[level.zip](https://github.com/overviewer/Minecraft-Overviewer/files/4870281/level.zip)

**Comment by CounterPillow** [comment]
Hmmm, that level.dat actually works fine for me, so it's not stuck on anything relating to that. I'll need to look into it further before I can tell you what other info I need.

Since I presume you never see the preprocessing message, I speculate it's stuck somewhere in the constructor of the TileSet object.

As an aside note, please don't use backslashes in paths. They have unintended side effects since they are used for special character sequences in strings, and Windows is perfectly happy with forward slashes. It's surprising your config works at all considering "\Users" would make python try to interpret this as unicode point "sers"

**Comment by chaseflynn** [comment]
It appears running Overviewer as administrator gets it past where it was getting stuck.  I'm going to guess that has something to do with access privileges to the web server folder where Overviewer is putting the map files.  Why it would've suddenly started after updating Minecraft to 1.16.1 and Overviewer to the latest version is beyond me.  But it's working!  Thank you for your time and let me know if you needed any follow up info.
