### ISSUE TITLE
How to inject html,css or js in the build process programmatically?

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1799]
Sometimes I would like to add html (favicon, menu), css (to hotfix things like this #1794 or js (to add custom functions) to the overviewer. I could change the files with a shell script on the server but maybe there is a nicer way to accomplish that? Maybe something I can add in the config.py? What is considered best practice?

**Comment by CounterPillow** [comment]
http://docs.overviewer.org/en/latest/config/#custom-web-assets
