### ISSUE TITLE
Build docs incorrect

### ISSUE THREAD

**Issue by davemac30** [overviewer/Minecraft-Overviewer#1802]
The build document (<https://github.com/overviewer/Minecraft-Overviewer/blob/master/docs/building.rst>), states:

> If you choose to install pillow through pip instead of your distribution's package manager, you won't get the pillow headers...

I've tested building from source on several distro images (debian, ubuntu, fedora, centos and alpine) using the distro-supplied pillow and have found that it is necessary to copy three headers from <https://github.com/python-pillow> in every case. The docs should reflect this.

**Comment by CounterPillow** [comment]
Ubuntu ships the headers: https://packages.ubuntu.com/search?searchon=contents&keywords=Imaging.h&mode=exactfilename&suite=focal&arch=any

As does Arch Linux:
```
pacman -Ql python-pillow | grep -e 'Imaging.h$'
python-pillow /usr/include/python3.8/Imaging.h
```

**Comment by CounterPillow** [comment]
Fedora ships them in python3-pillow-devel.

So yeah I'm closing this because it's just straight up not true.

**Comment by davemac30** [comment]
Hmm, well, that's embarrassing. Thanks for the info - building fine now!
