### ISSUE TITLE
Nether Render not looking good due to new 1.16 blocks at the nether roof

### ISSUE THREAD

**Issue by PeaEyeEnnKay** [overviewer/Minecraft-Overviewer#1806]
Due to soul soil/sand, and possibly other new nether blocks, being able to exist at the roof of the nether the render of the nether for certain biomes is not great.

Looking through the code on the master branch, the new nether blocks do not have block ids in the mc_block_id enum contained in mc_id.h

And the code in primitive/nether.c would need to be updated

for (y = NETHER_ROOF - 1; y >= 0; y--) {
    blockid = get_data(state, BLOCKS, x, y - (state->chunky * 16), z);
    if (block_class_is_subset(blockid, (mc_block_t[]){block_bedrock, block_netherrack, block_quartz_ore, block_lava}, 4))
        data->remove_block[x + 1][y][z + 1] = true;
    else
        break;
}

I'm not sure what else would need to be tweaked, as this is the first time I've ever looked at the code.

![NetherSoulSoilBiome](https://user-images.githubusercontent.com/3463847/86788972-b12a0000-c05e-11ea-8d2f-71e3368fd90a.png)

**Comment by PeaEyeEnnKay** [comment]
Close up showing one of the problem areas that shows the soul sand/soil causing the problem on my world.

![NetherSoulSoilBiome_Zoomed](https://user-images.githubusercontent.com/3463847/86790554-79bc5300-c060-11ea-9340-fcda183d29ab.png)

**Comment by LeadMagnet** [comment]
My render looks very similar. Even with "nether_smooth_lighting" in the config it looks like above, where as historically slicing off the top 4 or 5 levels made the render perfect.

No sure how to address this.

**Comment by robosphinx** [comment]
I've updated my nether.c (line 42 in the original source, I think?) as follows:

`if (block_class_is_subset(blockid, (mc_block_t[]){block_bedrock, block_netherrack, block_quartz_ore, block_lava, block_soul_sand, block_basalt, block_blackstone}, 7))`

It has cleaned up [my nether render](http://map.callumhume.com/#/-58/64/-10/-2/World%20-%20nether/Nether) significantly, though it seems I'm still missing one or two blocks, based on the patches of visible bedrock in various areas. Seems like maybe they're in specific biomes...

I am using @IncredibleHolg 's [my-116-blocks](https://github.com/IncredibleHolg/Minecraft-Overviewer/tree/my-116-blocks) branch, which has 1.16 blocks defined in mc_id.h

**Comment by LevelZero-dev** [comment]
Soul Soil and Nether Gold Ore are probably at least two you are missing, both are not present yet in mc_id.h on that branch.
From what I can see, Soul Soil can generate at any Y value, while Nether Gold Ore can generate up to Y=117

**Comment by IncredibleHolg** [comment]
I added this two blocks
![ngold+soil](https://user-images.githubusercontent.com/41533138/89325295-e12de880-d688-11ea-91ef-cd282e007e24.png)

**Comment by IncredibleHolg** [comment]
Looks good, I incease the brightness using
```python
my_nether_lighting = [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.5)]
```
![nether_topremoved](https://user-images.githubusercontent.com/41533138/89328610-f0636500-d68d-11ea-83c6-4a81e7d52842.png)

**Comment by IncredibleHolg** [comment]
@LevelZero-dev  do you know, whether gilded_blackstone can spawn near the nether roof?

**Comment by LevelZero-dev** [comment]
Gilded Blackstone only spawns as part of Bastion Remnants.
I haven't been able to determine if there is a limit to the Y values where Bastion Remnants can spawn.

This would lead to another issue though .. if Bastion Remnants can spawn near the nether roof, removing them would maybe not be the best option ...

**Comment by CounterPillow** [comment]
I'll close this now since IncredibleHolg's changes are in the master branch, let me know if there's still issues with the nether roof stripping.

**Comment by PeaEyeEnnKay** [comment]
Thank you all.

Other than some known issues reported elsewhere (ancient debris topped columns for example) this is working okay now in 0.16.4.
