### ISSUE TITLE
Question: How to update a map?

### ISSUE THREAD

**Issue by kiel814** [overviewer/Minecraft-Overviewer#1814]
This is not an issue, only a question.

What I want to do is overwrite the parts of the map that have been updated and leave the ones that have not changed?

As I understand it:
If I don't specify anything, the map will not be updated. Only new chunks will be added.
If I use forcerender, it is basically the same as deleting the contents of the output folder and rendereing everything again (since I do not delete any files from the world folder).

I believe the rerenderprob parameter may be related to what I want. Is it? The explanation in the documention is not clear to me.
> This is the probability that a tile will be rerendered even though there may have been no changes to any blocks within that tile. 

Why would I want to re render something that has not had any changes?

Any help?
Thanks!

**Comment by tswsl1989** [comment]
You're not quite there with your first point:
> If I don't specify anything, the map will not be updated. Only new chunks will be added.

If you don't specify anything, new chunks will be added *and changed chunks updated*

The `rerenderprob` parameter is useful if you're changing render parameters on a map but don't want to re-render the entire thing at once to get the changes to show. New and updated tiles would be rendered with the new settings immediately, and old tiles will gradually be updated over successive renders.

Hope that helps - if not, feel free to reopen the issue.
