### ISSUE TITLE
World Rendering Question 2

### ISSUE THREAD

**Issue by Broyojo** [overviewer/Minecraft-Overviewer#1820]
Just to clarify, but if you render a world, in my case it was a 1.16.1 world, does the overviewer modify anything about the save because I am worried about that.

**Comment by CounterPillow** [comment]
no, it opens all files read-only, so even if there was a bug it would not be able to modify the world data. You can verify this yourself by looking at the following line in nbt.py: https://github.com/overviewer/Minecraft-Overviewer/blob/1355f8c49e365918cffc8763303394638bd38bf8/overviewer_core/nbt.py#L30
