### ISSUE TITLE
Incorrect version reported?

### ISSUE THREAD

**Issue by Hraefin** [overviewer/Minecraft-Overviewer#1824]
I have installed Overviewer 0.15.88 in Linux using the debian repository per the instructions on the website.

When I run /usr/local/src/Minecraft-overviewer/overviewer.py -V it returns version 0.15.83 (8ec2a99)

I'm trying to figure out if this is an issue with my installation (e.g. old version hanging out somewhere) or if the version tag in the repo was not properly updated.

apt version minecraft-overviewer
reports
0.15.88-0~overviewer1

The reason I question the version is that I am not seeing any 1.16.x blocks render, and I had thought some of those were rolled into the newest release.  Regardless, something seems amiss.

**Comment by CounterPillow** [comment]
Your /usr/local version is not the version from the repositories.

**Comment by Hraefin** [comment]
Thanks.  I am running Mint Linux and apparently it does not work from the repository as shown in the documentation.
I downloaded the tar and installed.   Is there any way you could make an update to the docs for non-debian users?  I installed python 3 (3.8 actually) and ran the python build and it did not work.  I then ran the python install and it also didn't work.  On a whim, I tried installing it a second time and then it worked properly.  Not sure why...

Thanks.

**Comment by CounterPillow** [comment]
"and it did not work" is not really anything I can do anything with.

>and webassets

what? There's nothing you need to do with the webassets at all.
