### ISSUE TITLE
Stairs not rendering correctly

### ISSUE THREAD

**Issue by matej-darebnik** [overviewer/Minecraft-Overviewer#1825]
Hi, after merge from 116-blocks yesterday, stairs stopped rendering correctly:
![image](https://user-images.githubusercontent.com/51075039/89570999-3dc70a00-d827-11ea-805b-30e0ad43523a.png)

This is how it looks ingame:
![image](https://user-images.githubusercontent.com/51075039/89570952-2c7dfd80-d827-11ea-9767-b68f0022c681.png)

Version of overviewer:
Minecraft Overviewer 0.16.0 (50b84e9)
built on Wed Aug  5 17:15:03 2020

**Comment by matej-darebnik** [comment]
I have just noticed that my wooden roofs do not seem to be affected, so I have tried rendering dark oak stairs and also tried cobblestone. It seems that some types of stairs render correctly, while others look weird...

![image](https://user-images.githubusercontent.com/51075039/89572843-fd1cc000-d829-11ea-9f4b-9ec068f2f535.png)

![image](https://user-images.githubusercontent.com/51075039/89572540-854e9580-d829-11ea-9272-02e329b4e000.png)

**Comment by IncredibleHolg** [comment]
I will try to pin down the commit, that introduced this bug.
