### ISSUE TITLE
Mushroom Stems not rendering

### ISSUE THREAD

**Issue by mrspinn** [overviewer/Minecraft-Overviewer#1828]
Mushroom stem blocks don't appear to be rendering in the latest versions of overviewer 0.16.0

Version: 0.16.0

Minecraft version 1.16.1

![image](https://user-images.githubusercontent.com/34923439/89687114-96e97900-d8cd-11ea-918a-101747d8e565.png)

**Comment by CounterPillow** [comment]
Should be fixed now thanks to Auron956.
