### ISSUE TITLE
Make an image of certain coords with zoom

### ISSUE THREAD

**Issue by Beanster199** [overviewer/Minecraft-Overviewer#1844]
I just render my world and im trying to generate a PNG image on certain coords of the world with the max zoom possible. 

I'm using `png-it.py` to generate the image but when i try to add the max zoom parameter ( if i set it to 1 it generates without problem) i get next message:
> Error! No images found in this zoom level. Is this really an Overviewer tile set directory?

I tried add more zoom to my overviwerconfig but still dont work
My config for overviwer is: 
```
worlds["world"] = r'C:\Users\%User%\AppData\Roaming\.minecraft\saves\MyWorld'

renders["survivalday"] = {
    "world": "world",
    "title": "Daytime",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "maxzoom": 18,
}

outputdir = r'C:\Users\%User%\Desktop\backup\map'
maxzoom = 18
```

Is there a way so i could generate and PNG image of certain coords with max zoom on that coords possible? 

Its most possible i'm missing something or some argument any help is appreciated

**Comment by LeadMagnet** [comment]
In the past, I have used Site-Shot (https://www.site-shot.com/) to get website screen shots for testing, documenting, etc.

They have an API call to generate the image and return the result which can then be saved anywhere.

Not exactly a solution to your MAX zoom issue, but it works. Hope it helps.
