### ISSUE TITLE
Is it important to stop server before rendering?

### ISSUE THREAD

**Issue by altucor** [overviewer/Minecraft-Overviewer#1860]
I interested when i'm able to run generation of map safely for game server and for getting correct result from overviewer? Let's assume i have enough power for running server and rendering at same time, so is it safe to run map generation on working server or it is better to stop it before?

**Comment by twoprops** [comment]
> On Oct 11, 2020, at 11:42, altucor <notifications@github.com> wrote:
> 
> 
> is it safe to run map generation on working server or it is better to stop it before?
> 

If you run Overviewer against an active world, you'll get errors in the rendering. You don't have to stop your server, though. You can just issue a "save-off" command to the server, then "save-all", then run the render, then issue "save-on" when Overviewer is finished.

Be sure your script will issue the save-on command even if Overviewer exits with an error, or you can lose changes to the world if the server crashes.

**Comment by altucor** [comment]
Cool, thank you for fast and detailed response.

**Comment by altucor** [comment]
https://gist.github.com/altucor/5bf1805227b3ec76a29adbe4913e181b#file-overviwer-service -  just want to share my solution, maybe some one can discuss how it can be improved.
And this is where mc-0 name of the session comes:
https://gist.github.com/altucor/54d63adbd4341f1dff0ae5d18c6f5e64#file-minecraft-service
