### ISSUE TITLE
Seemingly scrambled map generated

### ISSUE THREAD

**Issue by boyenn** [overviewer/Minecraft-Overviewer#1888]
Hi, I've just generated an overviewer map based on a freshly generated world.

You can see the generated result here : https://bob-smp-map.website-eu-central-1.linodeobjects.com/#/-15/64/32/-2/world/world-lighting

As you can immediately tell, the images are all out of order and scrambled.

I looked through FAQ and could not find this issue mentioned. Quick search here on github does not come up with anything either.
Is this a known issue, did I just do something wrong ?

( I used the latest master and built it on ubuntu 20 )

**Comment by ShadowXVII** [comment]
Generally this can be caused by the render config being changed -- i.e. crop, or the render output having more files than it should.

However I tried a fresh render and I'm getting _some_ weird sections still. Still haven't quite figured out what's going on.

**Comment by ShadowXVII** [comment]
For example, this was a forcerender -- strange, rogue chunks from other areas.

![image](https://user-images.githubusercontent.com/446329/107890989-11c3d880-6f70-11eb-8ac8-3da14c279d97.png)

**Comment by ShadowXVII** [comment]
I think it's an issue with left-over tiles... Tried a --check-tiles but it didn't fix it. Going to try a fresh render.
![image](https://user-images.githubusercontent.com/446329/107896950-f2d33f80-6f8b-11eb-84b6-0dd0975a28d7.png)

**Comment by ShadowXVII** [comment]
So, I tried deleting all render files and generating a fresh render, still corrupted. But on different tiles.

![image](https://user-images.githubusercontent.com/446329/107911170-07293380-6fb0-11eb-8347-228869539e43.png)

**Comment by robosphinx** [comment]
I used to have this issue and it was because I was rendering from an active world folder.  My render script now sends `save-off` and `save-all` to the Minecraft server before rendering, then `save-on` after the render is complete.  I no longer get these out-of-place chunks on my maps.  Another option is to copy the live world files to a dummy location and render using that dummy location as your target, so files don't change while rendering.

**Comment by CounterPillow** [comment]
I just pushed a change to maybe address this, can someone tell me if an overviewer version >= 0.17.17 still has this issue as often? Thanks

**Comment by ibmibmibm** [comment]
I didn't observed that render error occuring again since I 4 days ago.

**Comment by CounterPillow** [comment]
Thanks, I'll mark this as fixed then. I think it can still happen in very rare circumstances where all the stars align and we get a chunk written to right after we re-read its location, but this could also happen equally likely when just copying an active world.
