### ISSUE TITLE
Windows defender and Webroot detect Overviewer.exe as Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by bartlanz** [overviewer/Minecraft-Overviewer#1893]
I am new to this tool, I extracted the Win64 installer and was immediately warned of this from Windows defender. I tried downloading it again on another PC and received a similar warning from Webroot.

Windows defender and Webroot detect Overviewer.exe as Trojan:Win32/Wacatac.B!ml

**Comment by CounterPillow** [comment]
False positive, report it to Microsoft. It's also not an installer, overviewer.exe is literally just a bundled python interpreter.

**Comment by CounterPillow** [comment]
Microsoft said they've fixed the false-positive detection now.

**Comment by robtherobot12** [comment]
Just an update - sometimes windows defender glitches and picks up the threat anyway, and then it goes away after a quick scan.

(sorry for bump)

**Comment by CounterPillow** [comment]
We'll probably have to deal with this false detection for the rest of Overviewer's existence, with it occasionally returning. I recommend adding some sort of exclusion rule for whatever directory you store it in.

We've also had to nicely ask Google not to flag our website as malicious for offering Overviewer for download. It's not fun but we're putting in the work to make sure the application remains available despite the tech-oligopolys target painted on our backs.

As an aside note: we'll be looking into the new Windows package manager for distributing Overviewer. Hopefully, it does not suffer from these issues. Or maybe it will.

**Comment by robtherobot12** [comment]
Hi,
For me windows defender simply stopped detecting it as a threat as soon as I scanned, so I didn't have a problem.
I wish you luck with your new windows package!
