### ISSUE TITLE
Bitdefender reported overviewer 16.12 is infected with Trojan.GenericKD.36161889

### ISSUE THREAD

**Issue by pfmahoney** [overviewer/Minecraft-Overviewer#1896]
I searched the issues list and I did a quick google search and I don't see anyone else mentioning it.

I downloaded the 64-bit version from here:
https://overviewer.org/builds/win64/131/overviewer-0.16.12.zip

And Bitdefender immediately quarantined it with the notification:
Feature: Antivirus

The file overviewer\overviewer-0.16.12\overviewer.exe is infected with Trojan.GenericKD.36161889 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

I'll compile it from source, but I wanted to post and highlight the possible issue for investigation.

**Comment by CounterPillow** [comment]
false positive, as was the same shit by Microsoft. BitDefender likely just cargoculted Microsoft's (now reversed) detection.

Please do not report this to us since it's not our problem, but the problem of your snakeoil vendor (BitDefender).

**Comment by pfmahoney** [comment]
Ok.   Thanks for the response.
