### ISSUE TITLE
Error on creating world map

### ISSUE THREAD

**Issue by DarkSmileee** [overviewer/Minecraft-Overviewer#1902]
Hi, 

I'm getting the following error when generating a world map: 

https://pastebin.com/zt9GG3S1

Needed information?:
MC version: 21w06a (Fabric)
ISO: Windows 64bits
Version overviewer: overviewer-0.16.12 (64 bits)

**Comment by pietrobenito** [comment]
I'm getting the same error with 21w06a. I think there might be changes to the world builder that could be incompatible with Overviewer.

**Comment by fabiancz** [comment]
Same error on Debian Linux:

```
2021-03-04 12:28:03  Generating textures...
2021-03-04 12:28:35 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 653, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1464, in get_chunk
    chunk_data['NewBiomes'] = (len(biomes.shape) == 3)
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by rjp** [comment]
This is a super-quick hack to get things rendering without fixing the underlying issue.

```
diff --git a/overviewer_core/biome.py b/overviewer_core/biome.py
index 9910165..6e21af9 100644
--- a/overviewer_core/biome.py
+++ b/overviewer_core/biome.py
@@ -28,3 +28,5 @@ def reshape_biome_data(biome_array):
         # but they appear to either be wrong or have explained it with the eloquence of a
         # caveman.
         return biome_array.reshape((4, 64, 4))
+    elif biome_len == 1536:
+        return biome_array.reshape((4, 96, 4))
```

(the problem being that now the world is 50% taller which makes the biomes 50% bigger and the original code didn't know what to do with that.)

**Comment by pietrobenito** [comment]
> This is a super-quick hack to get things rendering without fixing the underlying issue.
> 
> ```
> diff --git a/overviewer_core/biome.py b/overviewer_core/biome.py
> index 9910165..6e21af9 100644
> --- a/overviewer_core/biome.py
> +++ b/overviewer_core/biome.py
> @@ -28,3 +28,5 @@ def reshape_biome_data(biome_array):
>          # but they appear to either be wrong or have explained it with the eloquence of a
>          # caveman.
>          return biome_array.reshape((4, 64, 4))
> +    elif biome_len == 1536:
> +        return biome_array.reshape((4, 96, 4))
> ```
> 
> (the problem being that now the world is 50% taller which makes the biomes 50% bigger and the original code didn't know what to do with that.)

Seems to work great. Have you put in a pull request? @rjp

**Comment by rjp** [comment]
> Seems to work great. Have you put in a pull request? @rjp

There's more that needs to be done, alas - this just lets it render, it doesn't do anything to let negative levels appear on the map and I guess won't handle anything above 256 either. But I'll have a look, see if I can prod the relevant bits.

**Comment by pietrobenito** [comment]
@rjp Ah. Of course. Might make my own branch with this workaround in, because I'm only really concerned with the top layer. Thanks for working on this. I wouldn't have known where to start!

**Comment by rjp** [comment]
Looks like the official world height change has been pushed back to Winter 2021 which should give people enough time to work out how to handle it in Overviewer.

**Comment by CounterPillow** [comment]
Yeah I just tried it with the latest snapshots and couldn't reproduce, so I guess I need to try 21w06a. Thanks for letting us know, will look into how to handle this cleanly
