### ISSUE TITLE
Version number not detected

### ISSUE THREAD

**Issue by drnixon** [overviewer/Minecraft-Overviewer#1910]
In overviewer.py line 371 I can see:
`logging.info("Welcome to Minecraft Overviewer version %s (%s)!" % (util.findGitVersion(), util.findGitHash()[:7]))`

However when running the Python script, the terminal output fails to execute util.findGitVersion():
`2021-03-23 15:33:40  Welcome to Minecraft Overviewer version unknown (unknown)!`
`2021-03-23 15:33:40  Generating textures...`

Overviewer built from source on macOS 11.2.3. I'm not pulling from Git, just building from the tar.gz file downloaded directly from overviewer.org. (Unclear which version: download on overviewer.org shows 0.16.12 as current, but source download link is for 0.16.11?)

**Comment by CounterPillow** [comment]
> I'm not pulling from Git, just building from the tar.gz file

That would be why. It uses git to find the version; it's simply the number of commits since the last tag.

> (Unclear which version: download on overviewer.org shows 0.16.12 as current, but source download link is for 0.16.11?)

the last change in .12 did not require a new source tarball release, so buildbot didn't make one.
