### ISSUE TITLE
Blackstone bricks not rendering

### ISSUE THREAD

**Issue by XTsam** [overviewer/Minecraft-Overviewer#1914]
When i render my world with a texture pack on, polished blackstone bricks render as if its the void and it is completely black, this shouldnt be an issue on my texture packs part because every other block can render smoothly except for polished blackstone bricks

**Comment by drnixon** [comment]
See pull #1901 , some 1.16 textures are still not incorporated.

**Comment by CounterPillow** [comment]
Hi, polished blackstone bricks et al should render now in the latest version (0.16.37)
