### ISSUE TITLE
How do i use my GPU to render?

### ISSUE THREAD

**Issue by Joemordecool** [overviewer/Minecraft-Overviewer#1919]
The question its simple, i have a GPU and want to use it to render my world, i read the doc how to use it and the only thing about rendering its form the CPU, maybe doesn't support GPU yet but y want to know

**Comment by IncredibleHolg** [comment]
Since most of the work is done by NumPy, this should apply:
https://stackoverflow.com/questions/49605231/does-numpy-automatically-detect-and-use-gpu
You may try this

**Comment by Joemordecool** [comment]
Thank you, was so usefull, now i have to implement it haha

**Comment by CounterPillow** [comment]
Closing as duplicate of #1506
