### ISSUE TITLE
Is it possible to zoom further in?

### ISSUE THREAD

**Issue by Gamemap** [overviewer/Minecraft-Overviewer#1921]
Is this already possible or will this be added?
I think it is related to this: #791

**Comment by CounterPillow** [comment]
Currently this is not possible. The reason for this is that Overviewer generates little sprites for each block at a fixed resolution, which is the most zoomed in resolution. These currently are all hardcoded. From the most zoomed in tiles, the more zoomed out levels are then generated by stitching four of them together and resizing them by half.

Once we have blockmodel rendering, having different max resolutions should be possible.

**Comment by Gamemap** [comment]
Thank you

**Comment by Gamemap** [comment]
@CounterPillow Is it currently possible to zoom further out? (I haven't tried it yet)

**Comment by CounterPillow** [comment]
I don't think there's any control letting you zoom out further, the default is to have the most zoomed out zoomlevel be the one that fits the whole world in one screen and nobody seems to have requested there to be a way to make it even smaller

**Comment by Gamemap** [comment]
You are right. Smaller is not necessary. I had somehow not been thinking about this.

Thank you for your help,
Gamemap
