### ISSUE TITLE
Crying Obsidian not rendering properly

### ISSUE THREAD

**Issue by felix920506** [overviewer/Minecraft-Overviewer#1923]
This is what it looks in game:
![image](https://user-images.githubusercontent.com/25688628/117526707-65871080-aff9-11eb-9930-da7266ec160e.png)
This is what it looks through Overviewer hosted via Nginx
![image](https://user-images.githubusercontent.com/25688628/117526723-7d5e9480-aff9-11eb-8146-41da95417700.png)

Software Version: 0.16.12
OS: Ubnutu Server 20.04 64bit
Textures: Official 1.16.1 JAR

**Comment by CounterPillow** [comment]
Renders now in the latest version of Overviewer
