### ISSUE TITLE
Overviewer rendering only old location

### ISSUE THREAD

**Issue by SachevskiyArtem** [overviewer/Minecraft-Overviewer#1928]
I want my render center to be in another place from spawn, but how can I do this?

My config:

```
renders["survivalday"] = {
"world": "Village Modernize",
"title": "Daytime",
"rendermode": normal,
"dimension": "overworld",
'crop': sizeRender,
'texturepath': texturePath,
'forcerender': force,
'center': [1547, 64, -7092],
}
```

What I get:
https://i.imgur.com/sMREVHD.png

**Comment by SachevskiyArtem** [comment]
> 
> 
> Your crop seems to be cropping out the part you're trying to render.

No, It is not the problem. I mean, I need to move the map render center to another point of minecraft world, that's the problem. So crop is just a rendersize, it does nothing wrong

**Comment by CounterPillow** [comment]
I'm still not sure I understand. Is the problem that the spawn marker is in the wrong place?
Because crop zones are in absolute coordinates, not around the center.

**Comment by SachevskiyArtem** [comment]
> 
> 
> I'm still not sure I understand. Is the problem that the spawn marker is in the wrong place?
> Because crop zones are in absolute coordinates, not around the center.


Spawn marker is just right in place. But the center, from where render starts, is still in the very first spawn place. But I want it to be exactly where spawn marker is. I have erased the crop. Now, of course, I see the place I wanted to see, but the center is stiil really far and renders the places I don't want to render

https://i.imgur.com/WA8iG5P.png

**Comment by CounterPillow** [comment]
I see, so the problem is that we center the map on like 0,0,0 and not on the spawn location. I'll look into it.

You can render just the new location by adjusting your crop coordinates, by the way. They are in world coordinates after all, so just press F3 or mouse around on the map and watch the bottom left coordinate display.

**Comment by CounterPillow** [comment]
I can't reproduce the problem you're seeing, we're centering on the position specified by "center" by default. If it's not rendering something you wish to render, it's because you need to update your crop coordinates; reminder, they're in absolute coordinates, not around your center.

**Comment by SachevskiyArtem** [comment]
Ok, thank you!
