### ISSUE TITLE
Cannot use the latest version of overviewer

### ISSUE THREAD

**Issue by malandrinoor** [overviewer/Minecraft-Overviewer#1929]
I have tried to use the v0.16.39 of overviewer that's stated on the download site (windows 10 64bit version) and get an error when trying to render my map. I don't have any problems with the former version the 0.16.8 version one. I do the same with the cd command and then the overviewer.exe "save file" "new folder" and hit enter. 

I get this error message:

**This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 578, in main
  File "overviewer_core\assetmanager.py", line 76, in initialize
  File "overviewer_core\assetmanager.py", line 150, in _output_assets
  File "PIL\Image.py", line 1932, in save**
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\malan\\Documents\\Nueva carpeta (2)\\world-lighting\\blank.png'

**Comment by CounterPillow** [comment]
Make sure any security software you are running isn't blocking overviewer from writing files. Anti-ransomware software may do this.

**Comment by malandrinoor** [comment]
> Make sure any security software you are running isn't blocking overviewer from writing files. Anti-ransomware software may do this.

genius! turned off the ransomware protection while I tried to render my map and it worked, is there a way to have it to work without having to turn this off every time I want to update my map?

**Comment by CounterPillow** [comment]
You can probably add your overviewer path to your security software's exception list.
