### ISSUE TITLE
How do I change the distance that is being rendered?

### ISSUE THREAD

**Issue by Tacos4Spackos** [overviewer/Minecraft-Overviewer#1930]
Hello everyone,
I am new and don't know my way around that well yet and I need your help. I want to increase the render distance but don't know how. Can you help me?

**Comment by CounterPillow** [comment]
Could you elaborate on what you mean by "render distance"? The zoom or how much of the world overviewer renders?

**Comment by Tacos4Spackos** [comment]
I mean how much of the world overviewer renders

**Comment by CounterPillow** [comment]
Overviewer can only render what Minecraft has already generated; we read the chunk data from the disk. Minecraft is "lazy" in generating, meaning that it waits for you to visit a certain location to generate it and write it to disk. I do believe there are tools to pregenerate a Minecraft world, but I don't have any personal experience with them.
