### ISSUE TITLE
[JSObserver] - message not shown on the map

### ISSUE THREAD

**Issue by Gamemap** [overviewer/Minecraft-Overviewer#1933]
If I use the JSObserver a `progress.json` is created with a message but the message is not shown at the bottom-right corner.

I used the documentation code and added the message field:
```
## An example that updates both a LoggingObserver and a JSObserver
# Import the Observers
from .observer import MultiplexingObserver, LoggingObserver, JSObserver

# Construct the LoggingObserver
loggingObserver = LoggingObserver()

# Construct a basic JSObserver
messages=dict(totalTiles="Rendering %d tiles", renderCompleted="Render completed in %02d:%02d:%02d", renderProgress="Rendered %d of %d tiles (%d%% ETA:%s)")
jsObserver = JSObserver(outputdir, 10, messages) # This assumes you have set the outputdir previous to this line

# Set the observer to a MultiplexingObserver
observer = MultiplexingObserver(loggingObserver, jsObserver)
```

**Comment by CounterPillow** [comment]
Show us your full config file, please

**Comment by Gamemap** [comment]
Could it be that it only shows up when running as an http server?
When I create a Python server it is displayed.

**Comment by Gamemap** [comment]
I created an http server using python in cmd.exe and connected to firefox with localhost.

**Comment by CounterPillow** [comment]
Yes, it requires a running HTTP server from what I understand.

**Comment by Gamemap** [comment]
Thank you

**Comment by Gamemap** [comment]
@CounterPillow Perhaps it would be helpful to others if this was included in the documentation.
