### ISSUE TITLE
chains missing

### ISSUE THREAD

**Issue by IncredibleHolg** [overviewer/Minecraft-Overviewer#1936]
Chains are not rendered

**Comment by IncredibleHolg** [comment]
@buscher 
Hi, when I looked at the chains, I noticed the model is quite similar to the end-rod -- which was also not implemented at this time.

Would you like to add this, since your end-rod code could be recycled for this?

**Comment by CounterPillow** [comment]
the sprite code used for e.g. flowers might come in handy as well

**Comment by buscher** [comment]
I will look into it. The flower hint is a good one, as a chain is more of a sprite than a 3d object like an end rod.
But it was to wait a bit, because of limited time and I want to finish other stuff first :)
