### ISSUE TITLE
setup.py - error: ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by selfslaughter** [overviewer/Minecraft-Overviewer#1940]
Trying to build overviewer now complains about needing c99 mode set. Manually adding it to setup.py appears to work as intended.

Strangely, it works as is under Ubuntu/WSL on my local machine, but throws this error without setting said c99 flag just after your recent -O3 addition on our actual server running centos (noting that this previously ran as is until recently as well). 

running build
running build_py
copying overviewer_core/overviewer_version.py -> build/lib.linux-x86_64-3.6/overviewer_core
copying overviewer_core/textures.py -> build/lib.linux-x86_64-3.6/overviewer_core
copying overviewer_core/world.py -> build/lib.linux-x86_64-3.6/overviewer_core
copying overviewer_core/aux_files/genPOI.py -> build/lib.linux-x86_64-3.6/overviewer_core/aux_files
copying overviewer_core/data/web_assets/index.html -> build/lib.linux-x86_64-3.6/overviewer_core/data/web_assets
running build_ext
building 'overviewer_core.c_overviewer' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m/Imaging -I/usr/include/python3.6m -c overviewer_core/src/main.c -o build/temp.linux-x86_64-3.6/overviewer_core/src/main.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement -O3
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m/Imaging -I/usr/include/python3.6m -c overviewer_core/src/composite.c -o build/temp.linux-x86_64-3.6/overviewer_core/src/composite.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement -O3
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I. -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m/Imaging -I/usr/include/python3.6m -c overviewer_core/src/iterate.c -o build/temp.linux-x86_64-3.6/overviewer_core/src/iterate.o -Wno-unused-variable -Wno-unused-function -Wdeclaration-after-statement -Werror=declaration-after-statement -O3
overviewer_core/src/iterate.c: In function ‘generate_pseudo_data’:
overviewer_core/src/iterate.c:339:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (size_t i = 0; i < sizeof(blocks)/sizeof(blocks[0]); ++i) {
         ^
overviewer_core/src/iterate.c:339:9: note: use option -std=c99 or -std=gnu99 to compile your code
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 273, in run
    build.run(self)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

Failed to build Overviewer!
Please review the errors printed above and the build instructions
at <http://docs.overviewer.org/en/latest/building/>.  If you are
still having build problems, file an incident on the github tracker
or find us in IRC.

**Comment by CounterPillow** [comment]
This is super weird, I've never seen gcc complain about for loop initialisation before. What version of gcc is this? I don't see how `-O3` could even make this an issue.

Also can you try this patch?

```patch
diff --git a/setup.py b/setup.py
index 19a2934..a74ca72 100755
--- a/setup.py
+++ b/setup.py
@@ -298,6 +298,7 @@ class CustomBuildExt(build_ext):
                 e.extra_compile_args.append("-Wdeclaration-after-statement")
                 e.extra_compile_args.append("-Werror=declaration-after-statement")
                 e.extra_compile_args.append("-O3")
+                e.extra_compile_args.append("-std=gnu99")
 
 
         # build in place, and in the build/ tree
```

**Comment by CounterPillow** [comment]
Ok I applied this in master and apparently it fixes our CentOS7 builds, which is nice.

Looks like .6 was the first broken version, so well before the `-O3` change. Weird.

**Comment by CounterPillow** [comment]
I just realised why: older gcc versions defaulted to an earlier standard of the C language + gnu extensions.

stdint.h was still available on those because, well, the file is around despite being a c99 thing, I assume.

**Comment by selfslaughter** [comment]
Ahh, sorry for the confusion. Yeah, I just meant adding the flag in after the -O3 flag like you just posted worked for me. Wasn't sure exactly when it broke.

So if that's committed, our versions should match again now. Happy days. :)
