### ISSUE TITLE
W Unable to get player name for UUID

### ISSUE THREAD

**Issue by drnixon** [overviewer/Minecraft-Overviewer#1950]
Was running a final render on a 1.16.5 world using Overviewer version 0.16.43 (bd06e9e) to save visual state prior to 1.17 refresh. UUID cache threw an error, didn't match some of the players, with message "W Unable to get player name for UUID [player UUID]". Looking up UUIDs in one of the many UUID to player name reference sites showed a match for the affected players. Tried re-running POI generation after removing the existing UUID cache, and net result was that NO player UUIDs were matched. Overviewer finished run with "Wrote UUID cache with 0 entries" even though it showed that it had tried to match UUIDs for multiple players. (Small server, 11 players, it tried to match all 11 and reported error for each.)

Unclear what happened here. Last render with same Overviewer build didn't throw this error. Did something change with the 1.17 release? I'm trying to run latest Overviewer on the upgraded 1.17 map now, generating a clean map into a new empty directory, but won't know if UUIDs are successfully matched until after the initial render completes.

**Comment by CounterPillow** [comment]
> Did something change with the 1.17 release?

If it did then I'm not aware of it, the player UUID resolution thing in genPOI uses a very old API that I don't think we're supposed to be using anymore, so it's possible that they've turned that off just now.

**Comment by jobe1986** [comment]
The API is very much still active at both https://api.mojang.com/profiles/minecraft for name to UUID mapping and https://sessionserver.mojang.com/session/minecraft/profile/<uuid> for UUID to profile/name mapping. I can provide the PHP code I used to verify if needed.

**Comment by drnixon** [comment]
Verifying that same behavior occurred in the new 1.17 render. Same error, player locations are shown but skin is replaced with a generic icon and player name listed as “None”.

**Comment by drnixon** [comment]
Any chance it’s a missing dependency on my end? I moved to Python3.9 prior to most recent renders, had to rebuild Overviewer 0.16 before it would run, and it was missing a few items (pillow, numpy). I’d expect if there was anything else required it would throw an error when trying to call the method.

**Comment by CounterPillow** [comment]
No, overviewer has no dependencies besides Pillow and Numpy. This might've been a temporary API hiccup, hard to really know for sure. I can look into making it more robust and not just throwing out the whole cache when that happens.

**Comment by drnixon** [comment]
Have been trying to figure it out. Only pattern I can see is that the 3 player name/icons that appear correctly are players who have not been on the server since the last update. (One has been offline for about 2 months, 2 are players that were last on a year or more ago.) genPOI.py lines 261-300 seem to include a time check for verifying player cache info; with the existing cache from prior successful renders present, the script is only throwing errors for players who were on server since that render.

**Comment by drnixon** [comment]
After a lot of checking I thought through everything that I knew had changed since last successful render. Could not find any issues with the API calls, manually plugging in UUID into URL used by Overviewer returned everything correctly. Ended up fully removing Python3 and all installed packages, removing prior Overviewer builds, then reinstalling Python3 (including verifying urllib3n was installed) and rebuilding the Overviewer. UUID issue was resolved at that point.

So short answer: If you get this error, clear out any conflicting Python builds, start clean, and run it again.
