### ISSUE TITLE
1.17 Cave And Cliffs Preview Minecraft Error

### ISSUE THREAD

**Issue by Byllfighter** [overviewer/Minecraft-Overviewer#1951]
Overviewer doesn't works in 1.17 with **_Cave and Cliffs Preview_** by Mojang.

**Comment by CounterPillow** [comment]
What version of Overviewer are you using, and which precise snapshot? Also, define "doesn't work". Is there an error? Please provide more information.

**Comment by Byllfighter** [comment]
Now it works, but I have other error. Blocks under 0 height are invisible. Here image: https://cdn.discordapp.com/attachments/822112877883162675/856105289060188160/bugprev.png
My overviewer version: 0.17.20

**Comment by CounterPillow** [comment]
Yes, there isn't any support for Y levels below 0 yet.

**Comment by CounterPillow** [comment]
Closing this in favour of #1954
