### ISSUE TITLE
Debian 10 upgrading; unmet dependencies for Python3

### ISSUE THREAD

**Issue by gotkube** [overviewer/Minecraft-Overviewer#1952]
Forgive me if this is the incorrect place to bring this up.
I'm attempting to upgrade on my Debian 10 system but am getting a dependency issue:
`minecraft-overviewer : Depends: python3 (< 3.6) but 3.7.3-1 is to be installed`
I currently have Python 3.7.3 installed and it appears overviewer requires 3.6? 
Does this need to be fixed or should I just downgrade to 3.6?
Thx

**Comment by eminence** [comment]
Sorry, we're in the process of rebuilding our build robots to support debian 10.  But until that's done, our pre-built .deb packages won't work.  Your best bet right now is to build overviewer from source: http://docs.overviewer.org/en/latest/building/#linux

**Comment by gotkube** [comment]
Awesome! Will do!
Thank you!
