### ISSUE TITLE
Pngnq Not Found

### ISSUE THREAD

**Issue by Ben2445Fun** [overviewer/Minecraft-Overviewer#1960]
I've been trying to do a quick render with overviewer and tried using pngnq, but whenever I run it, it says:

Optimization programs '['pngnq-s9', 'pngnq', 'pngnq-s9.exe', 'pngnq.exe']' were not found!

I've looked around for the past few hours to see if I could find a reason for this but got nothing. Any suggestions?

**Comment by CounterPillow** [comment]
Did you download and install pngnq?

**Comment by Ben2445Fun** [comment]
> Did you download and install pngnq?

I have installed both pngnq and pngnq-s9

**Comment by CounterPillow** [comment]
You only need one, and it needs to be in a directory that's within your `%PATH%`. If you can open a command line and type "pngnq-s9" or "pngnq" without any cd-ing or prefixing, then you've done it correctly.

**Comment by Ben2445Fun** [comment]
> You only need one, and it needs to be in a directory that's within your `%PATH%`. If you can open a command line and type "pngnq-s9" or "pngnq" without any cd-ing or prefixing, then you've done it correctly.

Does this include cd-ing to the overviewer folder (I'm quite new to this command line stuff but can get a hang of it quickly).

**Comment by CounterPillow** [comment]
> Does this include cd-ing to the overviewer folder (I'm quite new to this command line stuff but can get a hang of it quickly).

No, it should work in any folder.

Just placing the applications within overviewer's folder will not work for overviewer to pick it up, as far as I'm aware.

**Comment by Ben2445Fun** [comment]
> No, it should work in any folder.
> 
> Just placing the applications within overviewer's folder will not work for overviewer to pick it up, as far as I'm aware.

Then it would appear my issue is most likely with the installation of pngnq-s9. At the current moment I've extracted its .zip file and have it sitting in my downloads folder. Are there any other steps that I'm missing to downloading it? As of right now I don't entirely understand how any of the stuff beyond this works.

**Comment by CounterPillow** [comment]
Create a folder somewhere to put the .exe in, then edit your path environment variable to have that directory appended to it. You can also do this from within the command line [as explained e.g. here](https://cat.pdx.edu/platforms/windows/user-environment/edit-path-variable-in-win-10/).
