### ISSUE TITLE
"No level.dat file in 'C:\worlds\RoFT'. Are you sure you have the right path?"

### ISSUE THREAD

**Issue by MisterVideosoEx** [overviewer/Minecraft-Overviewer#1962]
Every time I try to set up the config, it always gives me this:

`No level.dat file in 'C:\worlds\RoFT'. Are you sure you have the right path?`

There is a level.dat file in the world's folder. I have no idea why I'm getting this error.

Here is my config.py file if it helps:

```
worlds["roft"] = "/worlds/RoFT"

renders["normalrender"] = {
    "world": "roft",
    "title": "RoFT (Daytime)",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

renders["nightrender"] = {
    "world": "roft",
    "title": "RoFT (Night)",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

renders["netherrender"] = {
    "world": "roft",
    "title": "RoFT (Nether)",
    "rendermode": nether_smooth_lighting,
    "dimension": "nether",
}

outputdir = "/renders"

**Comment by MisterVideosoEx** [comment]
Figured it out from the sample config file. Apparently you can't put a slash at the beginning of a directory, so instead of `/worlds/RoFT` it has to be `worlds/RoFT`

**Comment by CounterPillow** [comment]
Slash at the beginning is an absolute path, that's why.
