### ISSUE TITLE
Python3 < 3.6 requirement - Debian bullseye Python3.9

### ISSUE THREAD

**Issue by nerthazrim** [overviewer/Minecraft-Overviewer#1973]
Hi,

I've just upgraded my Minecraft server on Debian bullseye, which bumped Python3 to version 3.9.

It seems the minecraft-overwiever deb packages are configured with a Python3 < 3.6 requirement, which prevents me to update.

Is it done on purpose? If not, can you please fix it?
If yes, is there any ETA on Python3.9 compatibility?

Thanks!

**Comment by gregpechiro** [comment]
Having this same issue on Ubuntu server. I have python 3.8.10 installed and I get this error

```
Selecting previously unselected package minecraft-overviewer.
(Reading database ... 123117 files and directories currently installed.)
Preparing to unpack overviewer-0.17.39.deb ...
Unpacking minecraft-overviewer (0.17.39-0~overviewer1) ...
dpkg: dependency problems prevent configuration of minecraft-overviewer:
 minecraft-overviewer depends on python3 (<< 3.6); however:
  Version of python3 on system is 3.8.2-0ubuntu2.
 minecraft-overviewer depends on python3-pil; however:
  Package python3-pil is not installed.
 minecraft-overviewer depends on python3-numpy; however:
  Package python3-numpy is not installed.

dpkg: error processing package minecraft-overviewer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 minecraft-overviewer
```

Python version

```
$ python3 --version
Python 3.8.10
```

I did not want to downgrade my python version so I started a docker container with python 3.6 installed and I still get an error. Though inside the docker container overviewer says I have 3.7 installed but the system says I have 3.6 installed

Inside docker container

```
Selecting previously unselected package minecraft-overviewer.
(Reading database ... 24613 files and directories currently installed.)
Preparing to unpack test/overviewer-0.17.39.deb ...
Unpacking minecraft-overviewer (0.17.39-0~overviewer1) ...
dpkg: dependency problems prevent configuration of minecraft-overviewer:
 minecraft-overviewer depends on python3 (<< 3.6); however:
  Version of python3 on system is 3.7.3-1.
 minecraft-overviewer depends on python3-pil; however:
  Package python3-pil is not installed.
 minecraft-overviewer depends on python3-numpy; however:
  Package python3-numpy is not installed.

dpkg: error processing package minecraft-overviewer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 minecraft-overviewer
```
python version inside container

```
# python3 --version
Python 3.6.14
```

**Comment by CounterPillow** [comment]
Overviewer supports Python 3.9, but our Debian builds don't because they're made on an old version of Debian.

For now, please remove the repository and its package, and [build from source](https://docs.overviewer.org/en/latest/building/#linux).

**Comment by CounterPillow** [comment]
> Do you have an approximate ETA for the fix on the Debian packages?

The ETA is "whenever someone fixes it". There are no daily SCRUM meetings here.

**Comment by nerthazrim** [comment]
Hi,

Sorry, didn't mean to be pressing or ungrateful. I was wondering if that was already in your pipes, nothing more :)

Thanks!

Should I close this issue or leave it open so you can notify us of the fix here?

**Comment by CounterPillow** [comment]
No worries. :) We can leave this open for now

**Comment by codesource** [comment]
Any ETA on this?

**Comment by CounterPillow** [comment]
@codesource no

**Comment by andresbott** [comment]
@CounterPillow would you be able to point me to the build / release process / code?
i will have a look (no promises ) 
I have seen there is a gitlab-ci file and a travis.ci what is being used nowadays ?

**Comment by CounterPillow** [comment]
@andresbott https://github.com/overviewer/Overviewer-Web/tree/master/buildbot
