### ISSUE TITLE
~~overviewer not making leaflet.js.map~~ PSA if you use Nginx it needs the mime.types to run the css and js files

### ISSUE THREAD

**Issue by TechNaWolf** [overviewer/Minecraft-Overviewer#1976]
When mapping is done a leaflet.js.map is not made and I believe this is interfering with the display of the map

![chrome_2021-09-01_18-14-11](https://user-images.githubusercontent.com/30179566/131753507-a8a04b78-7fd1-4207-b86a-c6830d1f7189.png)

**Comment by TechNaWolf** [comment]
It seems like CSS or some other script isnt loading properly causing it to look like this, that or im missing some vars in my conf file.

![chrome_2021-09-01_22-42-39](https://user-images.githubusercontent.com/30179566/131773248-d41fe077-cccd-4261-bd2c-5ac2f99d22f0.png)

![chrome_2021-09-01_22-42-47](https://user-images.githubusercontent.com/30179566/131773246-b7ba136f-c768-40fd-92c7-d5bd7097f272.png)

**Comment by TechNaWolf** [comment]
The settings im currently working with

```python
import os

from .observer import JSObserver

worlds['worldname'] = '/opt/mscs/backups/worldname/worldname-original' if os.path.exists('/opt/mscs/backups/worldname/worldname-original') else '/opt/mscs/backups/worldname/worldname'

renders['overworld-render'] = {
  'world': 'worldname',
  'title': 'Overworld',
  'dimension': 'overworld',
  'rendermode': 'smooth_lighting'
}

renders['overworld-caves-render'] = {
  'world': 'worldname',
  'title': 'Caves',
  'dimension': 'overworld',
  'rendermode': 'cave'
}

renders['nether-render'] = {
  'world': 'worldname',
  'title': 'Nether',
  'dimension': 'nether',
  'rendermode': 'nether_smooth_lighting'
}

renders['end-render'] = {
  'world': 'worldname',
  'title': 'End',
  'dimension': 'end',
  'rendermode': 'smooth_lighting'
}

processes = 4
outputdir = '/usr/share/nginx/maps/worldname'
```

**Comment by CounterPillow** [comment]
Your config looks totally normal to me, not sure what's causing what you're seeing. Do you have a link to your map so I can take a look to see if I can reproduce this issue?

**Comment by TechNaWolf** [comment]
the Minecraft map or the web browser link

**Comment by TechNaWolf** [comment]
heres a recent copy of the world
[map.zip](https://github.com/overviewer/Minecraft-Overviewer/files/7095854/map.zip)

**Comment by TechNaWolf** [comment]
Another thing that i see in the test map you have running i can see it using the `overviewer.css` where as my site isnt even trying to use it at all.

after typing that and googling a bit more ive found and fixed the issue. 
It was a problem with my NGINX conf as I was not using `/etc/nginx/mime.types` which allowd the webserver to use CSS and Js amongst other things. The app now works as expected.

Thanks for rubber ducking lol

![chrome_2021-09-01_23-53-04](https://user-images.githubusercontent.com/30179566/131779208-ec8813e1-0463-492a-aeb7-16ea92d49a93.png)

**Comment by cnkeats** [comment]
I had this exact same issue and I am just commenting to say thank you @TechNaWolf - I needed to add `include mime.types` to my nginx conf file.
