### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by crlang44** [overviewer/Minecraft-Overviewer#1977]
Hi, can anyone explain when my overviewer render doesn't produce a 0,1,2,3 folder in each subfolder. at the root level there is all of them, but for example under map/0/ there is only 2/ and 3/ but no 0/ or 1/ folders. I've read the documentation and it seems to me that there should be all for subdivisions at each level.

**Comment by jobe1986** [comment]
Each one of the folders 0, 1, 2 and 3 represent a corner of the map image at a certain zoom level, I forget which order, but the corners being top left, top right, bottom left and bottom right, forming a 2x2 grid of images.

At the outer zoom there is usually something in all 4 corner images, as the map is usually cantered across all 4, however the more you zoom in (the deeper in the directory tree you get), the more you will get to areas where there was simply no need to render an image as there were no chunks in that corner of the image.

**Comment by crlang44** [comment]
Wow yep, that is it! I think the thing that threw me off was thinking about how the quadtree is generated from the bottom up (highest zoom) and somehow that made me think there would have to be 4 folders at each level. Thank you for your help

**Comment by eminence** [comment]
Yup.  If there's nothing to show in a given quadrant, then there will not be a folder for that corner, since it would just be empty.
