### ISSUE TITLE
Windows defender detects overviewer.exe as Uwamson.A!ml 

### ISSUE THREAD

**Issue by Mega-Godzilla3000** [overviewer/Minecraft-Overviewer#1979]
I downloaded overviewer 32 bit from https://overviewer.org/downloads.

It downloaded succesfully but the moment it downloaded windows defender detected a virus, I quarantined it and said its the overviewer.exe.

![image](https://user-images.githubusercontent.com/81327810/132909858-65c411d2-0f46-4d8c-b0ca-3044f9d66d6f.png)

**Comment by jobe1986** [comment]
I've just scanned both the 32 and 64 bit versions of 0.17.39 n my windows 10 computer using windows defender and neither files were listed as infected for me.

Also in my case the protection updates were last updated today for me. So it may just be a case of needing to update windows defender. If that doesn't work then I strongly suspect something else is drastically wrong.

**Comment by CounterPillow** [comment]
This is not our issue, but Microsoft's issue. They just keep re-flagging it as something different even after they remove the false-positive detection. There's nothing we can do about it.

**Comment by Mega-Godzilla3000** [comment]
> I've just scanned both the 32 and 64 bit versions of 0.17.39 n my windows 10 computer using windows defender and neither files were listed as infected for me.
> 
> Also in my case the protection updates were last updated today for me. So it may just be a case of needing to update windows defender. If that doesn't work then I strongly suspect something else is drastically wrong.

Yup, It didnt work, what can I do? I also tested it on Virustotal.
![image](https://user-images.githubusercontent.com/81327810/132925634-a05c8073-fe77-4827-b0f6-7d76898b659d.png)

**Comment by CounterPillow** [comment]
report it as a false positive here https://www.microsoft.com/en-us/wdsi/filesubmission
link to this repository so they can look at the source code if they want.
