### ISSUE TITLE
Issue With Documentation Versus Implementation

### ISSUE THREAD

**Issue by EvilSupahFly** [overviewer/Minecraft-Overviewer#1991]
On a clean install of Linux Mint 20.2 x64, Python 3.8.10 is installed as the system default, and when attempting to install Overviewer from the repository (`deb https://overviewer.org/debian ./`), apt fails saying Overviewer requires Python 3.6.

Not a big deal, since I was able to build from source without any issue, however, when running Overviewer with a config file, I got the following error:

```
2021-11-11 00:46:34 E NameError parsing 'server_world.conf'.
2021-11-11 00:46:34 E The traceback below will tell you which line referenced the non-existent variable.

2021-11-11 00:46:34 E Partial traceback:
Traceback (most recent call last):
  File "/home/seann/Minecraft-Overviewer/overviewer_core/config_parser.py", line 85, in parse
    exec(compile(settings_file_handle.read(), settings_file, 'exec'),
  File "server_world.conf", line 22, in <module>
    dict(name="Chests", filterFunction=chestFilter, icon="chest.png", createInfoWindow=true),
NameError: name 'true' is not defined
```

According to the documentation at https://docs.overviewer.org/en/latest/signs/, my config file should look like this:

```
renders['ServerDay'] = {
        'world': 'Server World',
        'title': "Server World - Day Time",
        'markers': [dict(name="All signs", filterFunction=signFilter),
                    dict(name="Chests", filterFunction=chestFilter, icon="chest.png", createInfoWindow=true),
                    dict(name="Players", filterFunction=playerIcons)],
        'rendermode': smooth_lighting,
        'dimension': "overworld",
        'optimizeimg':[pngnq(sampling=1), optipng(olevel=3)],
}
```

The problem here (at least for me), is that it fails unless I put the `TRUE` for `createInfoWindow` in quotes:

```
renders['ServerDay'] = {
        'world': 'Server World',
        'title': "Server World - Day Time",
        'markers': [dict(name="All signs", filterFunction=signFilter),
                    dict(name="Chests", filterFunction=chestFilter, icon="chest.png", createInfoWindow="true"),
                    dict(name="Players", filterFunction=playerIcons)],
        'rendermode': smooth_lighting,
        'dimension': "overworld",
        'optimizeimg':[pngnq(sampling=1), optipng(olevel=3)],
}
```
Once that was done, it started fine:
```
seann on black-beast Thu Nov 11 12:49 AM
[~/Minecraft-Overviewer] $ ./overviewer.py --config=server_world.conf
2021-11-11 00:49:48  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2021-11-11 00:49:48  Generating textures...
2021-11-11 00:50:24  Preprocessing...
2021-11-11 00:56:33  Rendering 877844 total tiles.
 25% [==============                                                                               ] 227108 8.25t/s eta 21h 53m 55s
```

Is this because I built Overviewer with a newer version of Python, or a side effect of converting the project from Python 2 which escaped notice when the documentation was reviewed?

**Comment by eminence** [comment]
I think this is just a typo in the documentation.  It should say `True` (with a capital T) instead of `true`

**Comment by EvilSupahFly** [comment]
It seems to work fine both ways, as `True` and as `"true"`.

**Comment by ArchmageInc** [comment]
I don't see any reference to `true` in the linked documentation. The closest reference I can see is where it says `False` and that line hasn't been updated in 10 years:

https://github.com/overviewer/Minecraft-Overviewer/blame/master/docs/signs.rst#L196

IMO, this issue should be closed.
