### ISSUE TITLE
Size needed

### ISSUE THREAD

**Issue by theovanrooij** [overviewer/Minecraft-Overviewer#1998]
Hello I just have a quick question and I did not find an answer on the docs or your github. I apologize if this is not the right place. My question is : how much storage does a rendered world take ? Let's imagine I have a 5 GB world, how much free space do I need ?

Thanks !

**Comment by CounterPillow** [comment]
That depends on the world and your overviewer settings, but a good rule of thumb seems to be that the rendered map is 4 to 5 times as big as the world. You can make it smaller by rendering as JPEG or by using image optimisation programs.

**Comment by theovanrooij** [comment]
Thanks a lot !
