### ISSUE TITLE
1.18 - No blocks rendering below y=0

### ISSUE THREAD

**Issue by spacegriffin** [overviewer/Minecraft-Overviewer#1999]
I'm using Overviewer 0.17.41 and while the new surface features of 1.18 seem to be rendering fine, it looks like the height range hasn't been updated as nothing is rendered below y=0. I haven't tested for blocks over y=256, but I wonder if those would also be cut off since they're outside of the old height limit.

![image](https://user-images.githubusercontent.com/15514690/144626349-425f08a8-211a-4108-b587-8c4f963dff92.png)

**Comment by BenKennish** [comment]
I placed a signpost below Y=0 yesterday and the genpoi step of the render doesn't appear to have added it to the map.  I'm not 100% sure whether there are other signs **above** Y=0 tho (i.e. idk whether it's skipped all signs or just those below Y=0)  I will take a look on the world and report back tomorrow after the overnight render

**Comment by morsik** [comment]
There is issue already for that as I can see → https://github.com/overviewer/Minecraft-Overviewer/issues/1954

**Comment by CounterPillow** [comment]
Closed as duplicate then
