### ISSUE TITLE
Blocks above y=254 do not render

### ISSUE THREAD

**Issue by jack-webb** [overviewer/Minecraft-Overviewer#2003]
I think related to #1954, blocks at or above 255 aren't rendering on my 1.18 world. I'm using master a5b36f5. This also doesn't render below y=0

| Render | In-game |
| - | - | 
| ![UUIsA](https://user-images.githubusercontent.com/23270214/145108403-ba7b0e1d-5f31-4f9c-9fff-682aa5bba288.png) | ![4f9NA](https://user-images.githubusercontent.com/23270214/145108861-fcb41410-6e7d-4bcd-a569-73646ea363a2.png) |

**Comment by greatmastermario** [comment]
Looks like there are some hardcoded references to max height (formerly 255) and/or max y for sections. Section data can now go as low as -4 and as high as 19 (inclusive), so any references to these boundaries will need to be looked for. I am taking a look, and if I find all the references I will open a PR.

**Comment by greatmastermario** [comment]
https://github.com/overviewer/Minecraft-Overviewer/pull/2012

I got the fix working. Also fixes Issue 1954

**Comment by Daanay** [comment]
@greatmastermario sorry to bother you. How I can use your bugfix/2003_1.18_Increased_Height with fixed render above 254 height to render my world?

**Comment by greatmastermario** [comment]
@Daanay After you check out my branch, you need to recompile the C libraries. Follow the instructions in the documentation to do this. I did it with Python 3.9 with option 2 for compiling, but you should be able to use whatever works for you and the platform you are compiling on. Once that's done, run as normal.

**Comment by Daanay** [comment]
Thank you so much!

**Comment by jobe1986** [comment]
This bug does make me wonder about custom dimension types, which if I read correctly can have Y coordinates ranging from -2032 to 2031 (looking at min_y and height from custom dimension types on https://minecraft.fandom.com/wiki/Custom_dimension?so=search#Dimension_type ) Though as yet I havent tested how accurate that info is on the available options.

**Comment by greatmastermario** [comment]
Since this issue was fixed with my PR and merged to the main branch, can we close this issue?
