### ISSUE TITLE
Crash 1.18 render

### ISSUE THREAD

**Issue by TillW99** [overviewer/Minecraft-Overviewer#2008]
I get the following error:

overviewer:660     1275 2021-12-14 12:49:08 ERROR    An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer", line 653, in <module>
    ret = main()
  File "/usr/bin/overviewer", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/local/src/Minecraft-Overviewer/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'

when i try to run:

overviewer --config=/var/www/overviewer/config

on my proxmox vm running "Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-91-generic x86_64)"
with
config file:

worlds["normal"] = "/var/www/overviewer/world"

renders["survivalday"] = {
    "world": "normal",
    "title": "1.18.1 Overworld",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

outputdir = "/var/www/overviewer/"
texturepath = "/var/www/overviewer/1.18.1.jar"

I updated my mc server to paper v1.18-74
**the renderer workes perfectly fine with the "old" paper1.17.1** - a cronjob runs the command every day at 12:00 o clock
The only line i changed was:
texturepath = "/var/www/overviewer/1.17.1.jar"
to
texturepath = "/var/www/overviewer/1.18.1.jar"

what do i wrong, or is this a bug?
-sorry for my bad english :(

**Comment by dalandis** [comment]
Try to build the latest version. It seems there was something similar when trying to start the overviewer right after the update to 1.18

**Comment by TillW99** [comment]
Yes, this works for me, thanks a lot!
