### ISSUE TITLE
Ability to limit rendering (crop) by y axis

### ISSUE THREAD

**Issue by BafDyce** [overviewer/Minecraft-Overviewer#2016]
The `crop` option allows us to limit a render by the `x` and `z` axis. However, it would be nice if we could also add a limit for the `y` axis. E.g., when rendering just a city we might not be interested in any layers below the ground (especially with the upcoming fix for 1.18 worlds where we will render up to 120 layers below the ground).

Maybe there already is a way to do this but I haven't found anything by looking at the documentation, the code, and past (opened & closed) issues.

I would also be able to implement it myself, I'm just not sure how to correctly approach this. (Just changing the existing `crop` option would very likely break existing configs..)

**Comment by jmaximusix** [comment]
You can already do that using a custom rendermode. See "The Configuration File -> Custom Rendermodes and Rendermode Primitives -> The Rendermode Primitives -> Depth" in the documentation (http://docs.overviewer.org/en/latest/)

**Comment by BafDyce** [comment]
Oh thanks! I missed that one then.
