### ISSUE TITLE
Not installable - Up to Python 3.6 only

### ISSUE THREAD

**Issue by Justman10000** [overviewer/Minecraft-Overviewer#2032]
The error comes that MO is only compatible up to Python 3.6! Useless for people like me since I'm using Python 3.9! Suggest upgrading to the latest Python...

**Comment by arren-ru** [comment]
I have installed the latest overviewer 0.17.47 with Python 3.10.2 and it works fine

**Comment by CounterPillow** [comment]
This is a problem with our pre-built Debian packages, not with the application itself. I suggest building from source instead.
