### ISSUE TITLE
Overviewer cant find a file with a space in its directory

### ISSUE THREAD

**Issue by Mega-Godzilla3000** [overviewer/Minecraft-Overviewer#2036]
I suspect the issue is with the space in the directory name because the error message goes: "The settings file you specified ('C:/users:/José') does not exist, or is not a file.", the entire thing should be: "C:/Users/José Ignacio/Desktop/confi/config.cfg". 

I should mention I am using the version 0.17.39, i am not trying to render a 1.18 world.

**Comment by CounterPillow** [comment]
Use "quotes" in your command.

```
overviewer.exe --config="C:/Users/José Ignacio/Desktop/confi/config.cfg"
```
