### ISSUE TITLE
forgot how to use python

### ISSUE THREAD

**Issue by MariusDarkblade** [overviewer/Minecraft-Overviewer#2039]
its been a while since i last used overviewer and i dont remember a damn thing how to create the map using python. i managed to find the code to create the map, managed to find the process in which to get command prompt to use that python file i created, and when i plugged it into command prompt i got "error: too many arguments". i thought maybe because the file name had spaces it caused an issue so i removed those and now i'm getting syntax errors. i'm not big on coding, i have no clue what i am doing wrong here. i literally had to get this code from someone on here a while back and from what i understand its a really basic code to begin with. heres a picture of everything i'm getting on command prompt https://imgur.com/a/vFUumfT and heres the code i have been using, just dont mind my shit naming sense. how do i get this to work?

```python
worlds["amped but not amped"] = "C:\Users\Nick\AppData\Roaming\.minecraft\saves\amped but not amped"
my_nether_lighting = [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.4)]
my_end_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.4)]

outputdir = "E:\MinecraftMaps\Amped but not amped"

# Renders overworld
renders["survivalday"] = {
    "world": "amped but not amped",
    "title": "Overworld Daytime",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

# Renders overworld, at night
renders["survivalnight"] = {
    "world": "amped but not amped",
    "title": "Overworld Night",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

# Renders nether
renders["survivalnether"] = {
    "world": "amped but not amped",
    "title": "Nether",
    "rendermode": my_nether_lighting,
    "dimension": "nether",
}

# Renders The End
renders["survivalend"] = {
    "world": "amped but not amped",
    "title": "The End",
    "rendermode": my_end_lighting,
    "dimension": "end",
}
```

(Edited by @eminence to fix formatting)

**Comment by vilhok** [comment]
Please can you edit the post to surround the code parts with triple ticks? Now it renders as markdown.

**Comment by vilhok** [comment]
Also, it seems to complain about the space? I'm not familiar with your keyboard, but did you perhaps press alt/shift or whatever when you typed `= "` and accideltally held the modifier key down while typing the space? Maybe the space in the middle is not an actual space but some non-visible special character

**Comment by vilhok** [comment]
Hey, if you use windows -formatted paths, such as C:\something, you must escape the backslash like so: \\

**Comment by vilhok** [comment]
Nothing to do about code! 

Tick is \`. So tripletick is \`\`\`. Alternatively use the tools available: 
![image](https://user-images.githubusercontent.com/15260537/168649339-60bc7e0e-58ae-4f69-8a48-5b8404c64e3f.png)


So when you do:

 \`\`\`
my_number = 4
my_string = "test"
 \`\`\`
 
 It looks like


 ```
my_number = 4
my_string = "test"
 ```

**Comment by MariusDarkblade** [comment]
worlds["amped but not amped"] = "C:\Users\Nick\AppData\Roaming\.minecraft\saves\amped but not amped"
my_nether_lighting = [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.4)]
my_end_lighting = [Base(), EdgeLines(), SmoothLighting(strength=0.4)]

outputdir = "E:\MinecraftMaps\Amped but not amped"

# Renders overworld
renders["survivalday"] = {
    "world": "amped but not amped",
    "title": "Overworld Daytime",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
}

# Renders overworld, at night
renders["survivalnight"] = {
    "world": "amped but not amped",
    "title": "Overworld Night",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

# Renders nether
renders["survivalnether"] = {
    "world": "amped but not amped",
    "title": "Nether",
    "rendermode": my_nether_lighting,
    "dimension": "nether",
}

# Renders The End
renders["survivalend"] = {
    "world": "amped but not amped",
    "title": "The End",
    "rendermode": my_end_lighting,
    "dimension": "end",
}
``

**Comment by vilhok** [comment]
Missing one backtick. Please edit the original post, don't post again.


Also I already provided you the solution: https://github.com/overviewer/Minecraft-Overviewer/issues/2039#issuecomment-1127913433

**Comment by MariusDarkblade** [comment]
but where am i not applying that correctly? like i said, i never type these out when i use command prompt. i copied them from here into a notepad and then i copy paste from there into command prompt. everything has been copy pasted. the file locations i went into the window drop bar and copied the location straight from there. i dont type anything out specifically to not make mistakes.

**Comment by vilhok** [comment]
![image](https://user-images.githubusercontent.com/15260537/168650521-c77fa56d-97f6-4f95-9446-7aca349ae10f.png)
Right there in your code you are not applying it correctly. You must escape the slashes.

**Comment by MariusDarkblade** [comment]
so i need to add 2 slashes every time? i dont understand what escape the slashes means but thats what i'm guessing from what you said earlier.

**Comment by MariusDarkblade** [comment]
did overviewer change in between .16 and .17? when i created that string i literally copy pasted from a previous string that was created. i have several maps i make so i just modified the string to match the locations each time and created a new py file. those were the same codes in the last one that was working fine in .16. once i changed every \ to \\ it started running.

**Comment by vilhok** [comment]
Yes, add another, or turn every \\ to a /. 

I explained why as well in the very same comment (recently added a minor extra detail): https://github.com/overviewer/Minecraft-Overviewer/issues/2039#issuecomment-1127913433

>did overviewer change in between .16 and .17?

I don't know, I'm just a regular user and haven't looked at the code. How ever, my guess is that this is not something that overviewer did, this is just how python works. I guess that it's possible the config file was somehow handled differenly, but maybe someone who knows better might answer it. 

Now that this issue is solved, are you able to close this issue yourself or do we need to wait someone who has the correct rights?

**Comment by CounterPillow** [comment]
If it's solved I can close it no problem. Thanks for helping out!

Overviewer didn't change the way it handled configs lately. Python interprets a single `\` as the start of an escape sequence, so whatever comes after the `\` determines what the escape sequence is. We try to filter out some for the ease of our users, but that means the behaviour very much depends on what the exact letter after the `\` was. In general, please do not use `\` in Python strings unless you're trying to actually use an escape sequence or you're following it up with a second `\` to make a literal `\` with `\\`.
