### ISSUE TITLE
Higher zoom level than 8?

### ISSUE THREAD

**Issue by dkim19375** [overviewer/Minecraft-Overviewer#2042]
How do I increase the zoom level? (Since the highest I can get is zoom level 8 which gives a 12x12 block resolution)
Changing `overviewerConfig.js` just makes higher zoom levels black.
Changing `config.py` and adding the line `maxzoom = 9` doesn't seem to change anything either.

In the docs, it says:
> Note: This does not change the number of zoom levels rendered

but then how do I change the number of zoom levels rendered? Or is zoom level 8 the maximum?

**Comment by CounterPillow** [comment]
The resolution at which the most zoomed in level is rendered is fixed, there is no way to change it and it wouldn't be easy to implement this due to how overviewer is designed.
