### ISSUE TITLE
Issue with level.dat from a downloaded world, Throwing an error only with --genpoi

### ISSUE THREAD

**Issue by catagris** [overviewer/Minecraft-Overviewer#2055]
This is the error I am getting:

2022-07-15 09:21:21 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:

```
Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 168, in main
  File "overviewer_core\aux_files\genPOI.py", line 601, in main
  File "overviewer_core\aux_files\genPOI.py", line 338, in handlePlayers
AttributeError: 'dict' object has no attribute '_name'
```

Find attached my level.dat file in a zip.
[level.zip](https://github.com/overviewer/Minecraft-Overviewer/files/9116753/level.zip)

**Comment by catagris** [comment]
Data file info:
`TAG_Compound: 1 entries
{
    TAG_Compound("Data"): 36 entries
    {
        TAG_Compound("WorldGenSettings"): 4 entries
        {
            TAG_Compound("dimensions"): 3 entries
            {
                TAG_Compound("minecraft:the_end"): 2 entries
                {
                    TAG_String("type"): minecraft:the_end
                    TAG_Compound("generator"): 4 entries
                    {
                        TAG_Long("seed"): 0
                        TAG_String("type"): minecraft:noise
                        TAG_Compound("biome_source"): 2 entries
                        {
                            TAG_Long("seed"): 0
                            TAG_String("type"): minecraft:the_end
                        }
                        TAG_String("settings"): minecraft:end
                    }
                }
                TAG_Compound("minecraft:the_nether"): 2 entries
                {
                    TAG_String("type"): minecraft:the_nether
                    TAG_Compound("generator"): 4 entries
                    {
                        TAG_Long("seed"): 0
                        TAG_String("type"): minecraft:noise
                        TAG_Compound("biome_source"): 3 entries
                        {
                            TAG_Long("seed"): 0
                            TAG_String("type"): minecraft:multi_noise
                            TAG_String("preset"): minecraft:nether
                        }
                        TAG_String("settings"): minecraft:nether
                    }
                }
                TAG_Compound("minecraft:overworld"): 2 entries
                {
                    TAG_String("type"): minecraft:overworld
                    TAG_Compound("generator"): 4 entries
                    {
                        TAG_Long("seed"): 0
                        TAG_String("type"): minecraft:noise
                        TAG_Compound("biome_source"): 3 entries
                        {
                            TAG_Long("seed"): 0
                            TAG_String("type"): minecraft:multi_noise
                            TAG_String("preset"): minecraft:overworld
                        }
                        TAG_String("settings"): minecraft:overworld
                    }
                }
            }
            TAG_Byte("generate_features"): 1
            TAG_Long("seed"): 0
            TAG_Byte("bonus_chest"): 0
        }
        TAG_Compound("GameRules"): 6 entries
        {
            TAG_String("doWeatherCycle"): false
            TAG_String("spectatorsGenerateChunks"): false
            TAG_String("doMobSpawning"): false
            TAG_String("randomTickSpeed"): 0
            TAG_String("mobGriefing"): false
            TAG_String("doFireTick"): false
        }
        TAG_Compound("Player"): 2 entries
        {
            TAG_String("Dimension"): minecraft:overworld
            TAG_List("Pos"): 3 entries of type TAG_Double
            {
                TAG_Double: -224.000000
                TAG_Double: 76.000000
                TAG_Double: 0.000000
            }
        }
        TAG_Int("DataVersion"): 3105
        TAG_Double("BorderSize"): 60000000.000000
        TAG_String("LevelName"): world
        TAG_Double("BorderWarningTime"): 15.000000
        TAG_Long("LastPlayed"): 1657792501848
        TAG_Double("BorderSafeZone"): 5.000000
        TAG_Int("version"): 19133
        TAG_Byte("thundering"): 0
        TAG_Int("clearWeatherTime"): 0
        TAG_Int("SpawnX"): -224
        TAG_Byte("DifficultyLocked"): 0
        TAG_Byte("hardcore"): 0
        TAG_Int("SpawnZ"): 0
        TAG_Int("thunderTime"): 696969
        TAG_Int("rainTime"): 696969
        TAG_Int("SpawnY"): 76
        TAG_Long("SizeOnDisk"): 0
        TAG_Byte("allowCommands"): 1
        TAG_Byte("initialized"): 1
        TAG_Long("DayTime"): 0
        TAG_Compound("Version"): 3 entries
        {
            TAG_Byte("Snapshot"): 0
            TAG_String("Name"): 1.19
            TAG_Int("Id"): 3105
        }
        TAG_Double("BorderSizeLerpTarget"): 60000000.000000
        TAG_Double("BorderWarningBlocks"): 5.000000
        TAG_Double("BorderDamagePerBlock"): 0.200000
        TAG_Double("BorderCenterX"): 0.000000
        TAG_Byte("MapFeatures"): 1
        TAG_Int("GameType"): 0
        TAG_Long("Time"): 0
        TAG_Byte("raining"): 0
        TAG_Long("BorderSizeLerpTime"): 0
        TAG_Byte("Difficulty"): 1
        TAG_Double("BorderCenterZ"): 0.000000
        TAG_Long("RandomSeed"): 0
    }
}`

**Comment by catagris** [comment]
Fixed by deleting player location data. Deleting this:
![image](https://user-images.githubusercontent.com/1514273/179124146-5b8429e3-ce69-4657-914e-70d1409fc651.png)

I also manually moved the spawn location but might be unrelated.

**Comment by eminence** [comment]
This fix is now available, if you want to try it out:   https://overviewer.org/builds/win64/200/overviewer-0.19.6.zip

**Comment by sethborg** [comment]
I'm using 0.19.9 and still having this issue https://github.com/overviewer/Minecraft-Overviewer/issues/2072

**Comment by CounterPillow** [comment]
> No explanation given as to why

yes there was. It completely broke all player handling. It wasn't a real fix, it just messed up player handling in general.
