### ISSUE TITLE
Minecraft overviewer doesn't find "assets/minecraft/textures/colormap/foliage.png" 

### ISSUE THREAD

**Issue by Lemonaigo** [overviewer/Minecraft-Overviewer#2058]
Hello everyone,

When I found that overviewer existed I immediately wanted to use it in my server so I searched for many tutorials to render my server's world. 

![imatge_2022-07-27_080936648](https://user-images.githubusercontent.com/110084717/181173863-324a613b-337d-4e4f-8cab-d97e23039f62.png)

As you can see in the image you see that the overviewer doens't find "assets/minecraft/textures/colormap/foliage.png" and I've been serching for the route but THERE IS NO ROUTE for that (and that's why it doesn't find it). I've tried to create it manually by creating the folders myself but it's still useless and while I search for the "foliage.png" file in internet there's absolutely nothing. And yes, I'VE TRIED EVERY SUGGESTION THAT THE CMD GIVES, but still nothing...

I would love someone gave me a solution, thank you.

**Comment by CounterPillow** [comment]
Make sure the Minecraft 1.19 client is installed for the user you're running overviewer as.

**Comment by CounterPillow** [comment]
yes, just start the launcher normally and download version 1.19.

Alternatively, save [this jar](https://overviewer.org/textures/1.19) as `%APPDATA%/.minecraft/versions/1.19/1.19.jar`

**Comment by Lemonaigo** [comment]
THANK YOU FOR YOUR HELP!!! It finally worked :D
