### ISSUE TITLE
Generate textures is called for every 'northdirection'

### ISSUE THREAD

**Issue by alandamore** [overviewer/Minecraft-Overviewer#2067]
My config file has 4 renders, which are identical except for their name and each is using a different 'northdirection'. "Generating textures..." is shown 4 times at the start of the run, is that a bug or is it necessary? Only one "texturepath=" is defined. Each texture generation only takes 30 seconds so not a big deal in the scheme of things. Version 0.19.9 running on Windows 11.

**Comment by eminence** [comment]
This is expected, since each texture looks different from each of the 4 northdirections
