### ISSUE TITLE
how to import to website

### ISSUE THREAD

**Issue by deboi238** [overviewer/Minecraft-Overviewer#2073]
i was wondering how i can use my rendered world to a website, if so how
and what website should i use that is free?

**Comment by deboi238** [comment]
i want to use profreehost.com

**Comment by CounterPillow** [comment]
Helping you setting up a website is outside of the scope of this project. Overviewer generates static HTML files, any decent webhost should allow you to serve those.

**Comment by deboi238** [comment]
> Helping you setting up a website is outside of the scope of this project. Overviewer generates static HTML files, any decent webhost should allow you to serve those.

I figured it out how to import the file to a website but thanks

**Comment by deboi238** [comment]
> Helping you setting up a website is outside of the scope of this project. Overviewer generates static HTML files, any decent webhost should allow you to serve those.

@CounterPillow can you provide any website?
