### ISSUE TITLE
Custom markers not signs but ones you add in before render

### ISSUE THREAD

**Issue by Revenger** [overviewer/Minecraft-Overviewer#441]
I have asked this before back in April along with other stuff which has been addressed and implemented.

But I want the ability to add markers in that are not signs but show up as either warps or tourist attractions or build sites.

It needs it will need to be implemented before a render and be a static file in web assets or the config somewhere holding the info.

So it will show custom markers not signs on the map,

like (build town 1/2/etc)  (Site-seeing bridge/etc)

**Comment by CounterPillow** [comment]
Has been implemented with manual POIs.
