### ISSUE TITLE
Alternatives to Google Maps?

### ISSUE THREAD

**Issue by NotTarts** [overviewer/Minecraft-Overviewer#494]
Have other mapping libraries like [Seadragon](http://gallery.expression.microsoft.com/SeadragonAjax) or [OpenLayers](http://openlayers.org/) been considered as an alternative to Google Maps? The sources for both are freely available, unlike Google Maps, where I assume you need to hook into an API in order to load tiles (could be wrong there). Seadragon, too, is more suited for the quick panning and zooming (I've got an example [here](http://tarts.luma.mx/renders/largeWorld/)); the biggest problem I have with Google Maps is the fashion in which the screen goes blank if you zoom in too quickly or too far, though this happens in OpenLayers, too.

**Comment by CounterPillow** [comment]
Overviewer now uses leaflet.
