### ISSUE TITLE
Excluding Cave Spider spawners

### ISSUE THREAD

**Issue by dreniarb** [overviewer/Minecraft-Overviewer#750]
Anyone have a suggestion for excluding Cave Spider spawners from the map?  There are so dang many of them they clog up the screen!  :)

I have this right now:

<pre>
def spawnerFilter(poi):
    "Mobspawners"
    if poi["id"] == "MobSpawner":
        poi["Text1"] = "[MobSpawner] "
        poi["Text2"] = poi["EntityId"]
        poi["Text3"] = poi["Text4"] = ""
        return True
    else:
        return False
</pre>

I thought something like this would work but it errors out on the first if statement:

<pre>
def spawnerFilter(poi):
    "Mobspawners"
    if poi["EntityId"] == "Cave Spider":
        return False
    elif poi["id"] == "MobSpawner":
        poi["Text1"] = "[MobSpawner] "
        poi["Text2"] = poi["EntityId"]
        poi["Text3"] = poi["Text4"] = ""
        return True
    else:
        return False
</pre>

Any help is much appreciated.

**Comment by kuc** [comment]
Update for newest version:

```
def spawnerFilter(poi):
    if poi["id"] == "MobSpawner" or poi["id"] == 'minecraft:mob_spawner':
        if "EntityId" in poi:
            monster = poi["EntityId"]
        elif "SpawnPotentials" in poi:
            monster = poi["SpawnPotentials"][0]["Entity"]["id"]
        else:
            return None

        if monster == "CaveSpider" or monster == "minecraft:cave_spider":
            return None

        return monster
```

**Comment by cliffmeyers** [comment]
This could potentially be a useful contribution to the docs section on markers?

**Comment by NakedSkull1991** [comment]
I'm sorry, but now it doesn't work :/

![изображение](https://user-images.githubusercontent.com/49948586/170867313-ea319f2f-ea24-459f-af57-ccb4c6200734.png)
