### ISSUE TITLE
Feature Request: Allow more than one crop region

### ISSUE THREAD

**Issue by laszabine** [overviewer/Minecraft-Overviewer#816]
Would be great if under "crop" you could specify an array of tuples of coordinates to render. I would like to be able to render various parts of my map that are not connected to each other. 
(Alternatively some functionality would help that would either make it possible to display different renders simultaneously, or to allow overlays of Base() rather than only ClearBase() type. But I guess that would lead to problems if the specified crops overlap.)

**Comment by CounterPillow** [comment]
Has been implemented, see the docs for usage information.
