### ISSUE TITLE
Feature request : generate a single PNG file instead of a google map

### ISSUE THREAD

**Issue by Ezwen** [overviewer/Minecraft-Overviewer#826]
Hello !

I think that it would be nice to have other output possibilities than google maps. For instance, being able to generate a big single PNG file would be nice. I like to create timelapses using them :).

Thanks for your work on overviewer by the way, it's awesome.

**Comment by NPCtom** [comment]
Issue using png-it.py here https://github.com/overviewer/Minecraft-Overviewer/issues/1503
