### ISSUE TITLE
Insane renderd map size resulted from a 6gb world

### ISSUE THREAD

**Issue by salehram** [overviewer/Minecraft-Overviewer#834]
Hi
I have a VPS running a vanilla instance
I tried to use the overviewer to render my 6gb world (12,000 dia fully explored map)
The issue was the render failed at 45% and the remaining 30gb space on my VPS was all used for only 45% of the render

This is insane, out of 6gb I will need more than 10 times space for it to be rendered
Any solution I can apply to reduce this massive space usage for the render?

**Comment by CounterPillow** [comment]
Duplicate of #312
