### ISSUE TITLE
Cant render manual POIs

### ISSUE THREAD

**Issue by Staric1982** [overviewer/Minecraft-Overviewer#886]
Iam trying to render manual pois like in the manual. But no results. I see dropdown list on the map, can select Towns or Signs. Signs renders ok, but Towns - not. 
My overviewer.conf:

worlds["Staric"] = "/home/staric/minecraft/world"

def townFilter(poi):
    if poi['id'] == 'Town':
      try:
        return (poi['name'], poi['description'])
      except KeyError:
        return poi['name'] + '\n'

def signFilter(poi):
    if poi['id'] == 'Sign':
        return "\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']])

renders["survivalday"] = {
    "world": "Staric",
    "title": "Day",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    'poititle':"Markers",
    "markers": [dict(name="Towns", filterFunction=townFilter, checked=True),
                dict(name="All signs", filterFunction=signFilter)],
    'manualpois':[{'id':'Town', 'x':-259, 'y':64, 'z':150, 'name':'Ponyville'},
                    {'id':'Town','x':-200,'y':64,'z':100,'name':'Fillydelphia'}],
}

renders["survivalnight"] = {
    "world": "Staric",
    "title": "Night",
    "rendermode": smooth_night,
    "dimension": "overworld",
}

renders["survivalnether"] = {
    "world": "Staric",
    "title": "Survival Nether",
    "rendermode": nether_smooth_lighting,
    "dimension": "nether",
}

outputdir = "/home/staric/minecraft/worldmap/25d"
texturepath = "/home/staric/minecraft/"

**Comment by CounterPillow** [comment]
Closing this as per @MasterofJOKers comment.
