### ISSUE TITLE
keep rendering if dimension missing

### ISSUE THREAD

**Issue by A-Smith** [overviewer/Minecraft-Overviewer#913]
This is a feature request. I've just set up Overviewer on a new server, using a custom config file to render the three main dimensions. However, as the server is brand new, the Nether and End don't exist yet. Overviewer prints this message and then immediately exits:

    2013-03-22 22:45:06 E Sorry, you requested dimension 'nether' for nether, but I couldn't find it

It would be better if it just printed a warning, skipped that renderer, and moved on to the next one. As it is now, it exits early so that none of the dimensions are viewable. (Remember, this is a fresh install, so it hasn't copied the web assets yet, etc.)

My workaround is just to comment out the sections of my config file that refer to non-existent dimensions, but that means I have to watch to see when a user first visits one of the other dimensions so that I know when to update the config.

**Comment by CounterPillow** [comment]
Seems to have been fixed a while ago. Gonna close this.
