### ISSUE TITLE
Uknown syntax error when generating POIs

### ISSUE THREAD

**Issue by ghost** [overviewer/Minecraft-Overviewer#940]
Error:

F:\Minecraft\0.TOOLS\OVERVIEWER>overviewer.exe --config=Config.txt --genpoi
2013-06-06 04:51:28 E Syntax error parsing Config.txt
2013-06-06 04:51:28 E The traceback below will tell you which line triggered the
 syntax error

2013-06-06 04:51:28 E Partial traceback:
Traceback (most recent call last):
  File "overviewer_core\configParser.pyc", line 78, in parse
  File "Config.txt", line 19
    'markers': [dict(name="Town", filterFunction=townFilter)],}
            ^
SyntaxError: invalid syntax

---

The syntax error appears at the ' at the end of 'markers'. This is directly copied from the wiki. I have no experience with python, so i might be missing something somewhere...

Running Windows 7 64-bit, if that has anything to say.

![syntaxerror](https://f.cloud.github.com/assets/4630148/617764/b4f5b8c6-cea0-11e2-9632-51cd00dbdc08.jpg)

---

My config:

``` python
worlds["DkFurs"] = "F:/Minecraft/1.DKFURS/world"
outputdir = "Z:/HTTPx/my shared folder/DkFurs"

def townFilter(poi):
    if poi['id'] == 'Town':
      try:
        return (poi['name'], poi['description'])
      except KeyError:
        return poi['name'] + '\n'


renders["DkFurs"] = { 'world': 'DkFurs', 'title': 'DkFurs Server Map', 'rendermode': 'smooth_lighting',
'manualpois':[
        {'id':'Town','x':64,'y':64,'z':64,'name':'TownName'}
         ]



'markers': [dict(name="Town", filterFunction=townFilter)],}
```

(edited by @eminence for formatting)

**Comment by fhavio** [comment]
Hello there,
I'm having the same problem but the comma is fixed :) I already try several things but can't figure out what is the problem on that line

overviewer version 0.12.137 (7a0930a)

config.py file
![image](https://user-images.githubusercontent.com/26770387/29519648-13588f74-8676-11e7-8f47-256412cccc79.png)

command line
![image](https://user-images.githubusercontent.com/26770387/29519692-2e1e55dc-8676-11e7-95fe-c892c9bf4378.png)

**Comment by CounterPillow** [comment]
@fhavio the line previous to the return is your issue, `%` isn't a string append operator.

**Comment by fhavio** [comment]
Hi thanks for the answer, however even if i change the error is the same

![image](https://user-images.githubusercontent.com/26770387/29528328-8e2a64a8-8693-11e7-8170-56f2133c0208.png)

i'm not used to python so if you can help me i would really apreciate..
down below my batch file in case of something wrong on it

batch file
![image](https://user-images.githubusercontent.com/26770387/29528356-ad79f15c-8693-11e7-9db8-a7722c330ccb.png)

**Comment by CounterPillow** [comment]
Are you absolutely sure it's the same error?

**Comment by fhavio** [comment]
Yes, but now i split the items to check and it starts rendering, althought after that when he runs the genpoi command it gives a new error

![image](https://user-images.githubusercontent.com/26770387/29529043-165bb1f4-8696-11e7-9221-433af874d96f.png)

![image](https://user-images.githubusercontent.com/26770387/29529086-286e8ccc-8696-11e7-8750-7547fc7fd36a.png)

**Comment by CounterPillow** [comment]
because you're checking every single possible POI for a field called `type`, which doesn't exist in any of them.

**Comment by fhavio** [comment]
That was a dumb error 👎 

But i also had to change the method because of the return function, i split into 2 (for some reason he wasnt working) and also change icon string because it was giving some errors 

But now is ok, i post down below the final code. Thanks for your help 👍 

![image](https://user-images.githubusercontent.com/26770387/29541227-a87df590-86ca-11e7-82df-7909e81b5ac8.png)
