### ISSUE TITLE
Wrong color for grass/water because some texture not sought in right directory

### ISSUE THREAD

**Issue by joe-mojo** [overviewer/Minecraft-Overviewer#973]
Since I upgraded Minecraft server, Mincraft client and my favourite texture pack (John Smith Legacy 1.1) to v1.6.2 and Minecraft-Overviewer to fit this version, some texture of the texture pack are not used (especially foliage/grass colors, but some others too).

The reason why is that texture.py is not looking for the right file name. It is looking for "foliagecolor.png" thought my 1.6 compatible texture pack displaying nicelyin the game is holding this texture as "assets/minecraft/textures/colormap/foliage.png".

Same for "grasscolor.png" wich is found -- like "foliagecolor.png" -- in the default data set of Minecraft-Overviewer instead of the existing path "assets/minecraft/textures/colormap/foliage.png" in my texturepack.

Other errors : 
All _chest_.png who should be picked in "assets/minecraft/textures/entity/chest/" dir, file names are differents

**Comment by CounterPillow** [comment]
Something was merged, did this resolve the issue or not?

**Comment by joe-mojo** [comment]
Sorry for leaving this issue open so long, I'd rather open a new one if I see any issue next time I see somthing wrong. Thx for merging !
