### ISSUE TITLE
Gap between stairs

### ISSUE THREAD

**Issue by alexschrod** [overviewer/Minecraft-Overviewer#992]
Unlike most other blocks, it seems that Overviewer is having trouble stitching together stairs, as you can see in this picture:
![stair-gap](https://f.cloud.github.com/assets/767490/1188362/30190f52-23ca-11e3-83c0-19c1e01b7e88.png)

I'm using Overviewer 0.10.92 for this render.

**Comment by eminence** [comment]
Closed by #1285 !

**Comment by NoxNebula** [comment]
It's not fixed, slabs still have this issue, and they look weird:
![Slabs](http://i.imgur.com/lYOFmgJ.png)
These are all sandstone slabs, but double slabs (full blocks) are lower

**Comment by Socolin** [comment]
For slab see #1286

**Comment by NoxNebula** [comment]
thanks
